- .tx/config
- src/example/ExamplePage.jsx
> adds transifex config and test string

- package-lock.json
- package.json
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Please review.
This is the PR to add error handling and spinner to the proctoring exam settings page. 
This is the error screen when the user do not have enough permission to access the page:
This is the error screen when we suffered any other connection errors.
This is the screen when the page is loading
> Add error handling and spinner to the Exam settings page. 

- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Please review so we fix tests.
> This change would fix tests so they are actually doing the testing job

- src/proctored-exam-settings/ProctoredExamSettings.jsx
@edx/masters-devs-cosmonauts This is the message provided by Deen.
> Update the error messages based on copy

- package-lock.json
- package.json
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
- src/setupTest.js
@edx/masters-devs-cosmonauts This is the PR to switch the unit tests framework from `enzyme` to `@testing-library/react`. The example tests are easy to follow now.
> Switch from enzyme to testing-library/react

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts In this PR, I am adding state unit tests for `Spinner`, `Connection error` and `Permission error` states 
Please help review
> Add unit tests for connection states of the component

- src/data/services/StudioApiService.js
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Please review
This is the functionality to save the proctored settings. 
Save error:
> MST-334 Implement the settings post back functionality

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
Added unit tests for [MST-293](https://openedx.atlassian.net/browse/MST-293) and [MST-320](https://openedx.atlassian.net/browse/MST-320)
> Added unit tests for validation and defaults

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Please review. This is adding treatments for submission in progress state and disable the submit button.
See screenshot:
> MST-334 Add submission in progress treatment to submit button

- package-lock.json
- package.json
- src/proctored-exam-settings/ProctoredExamSettings.jsx
Updated Paragon version in order for checkboxes and radio buttons to have visual focus indicators
> Updated Paragon version for added focus indicators

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
> Prevent non edX staff from requesting changes to certain settings via POST request

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.messages.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
> Translation Support

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
Added focus to alerts that are associated with the save status of a form, and also removed unnecessary help text.
> Improve focus management and help text

- src/pages-and-resources/index.scss
- src/pages-and-resources/pages/PageCard.jsx
The PageCard code wasn’t updated to match the right props - it was still expecting “coursePage” when the new prop was “page”.  It was also lacking some other misc refactoring from earlier.
> fix: forgot to update PageCard to match new props

- src/pages-and-resources/discussions/AppList.jsx
- src/pages-and-resources/discussions/messages.js
https://openedx.atlassian.net/browse/TNL-8139
> feat: when there are no providers, show an error message

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/PagesAndResourcesProvider.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.jsx
Cleans up a TODO from prior commits.  Best reviewed with whitespace changes turned off.
> refactor: adding a provider for the pages and resources path

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigFormApplyButton.jsx
- src/pages-and-resources/discussions/app-list/AppListNextButton.jsx
[TNL-8115](https://openedx.atlassian.net/browse/TNL-8115)
This PR contains fix for footer back button in step 2 to be on left.
> [8]: Position Fixed For Back Button in Step 2 to be on left always

- package-lock.json
- package.json
- src/generic/FormSwitchGroup.jsx
In order to use IconButton from Paragon in [TNL-8124](https://openedx.atlassian.net/browse/TNL-8124), there is a need to bump paragon to the latest version. 
This PR bumps the version and fixes compatibility issues.
> build: bump edx paragon to 14.7.0

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
Accidentally refactored it out.
> feat: add the stepper header back in

- src/generic/FormSwitchGroup.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AnonymousPostingFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
[TNL-8135](https://openedx.atlassian.net/browse/TNL-8135)
Updated the cohorts sections to match the Figma design
Expected design in Figma
> Fixed cohorts section step 2

- src/pages-and-resources/pages/PageCard.jsx
- src/pages-and-resources/resources/ResourcesList.jsx
replace strict classNames with themeable className.
> fix: replace strict classNames with themeable className.

- src/index.scss
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/AppList.scss
- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
1. Updated background colour to white 
2. Center aligned icon
> Fixed color and alignment in data table

- package-lock.json
- package.json
Updating paragon to the latest. 
FYI @davidjoy
> Bump: edx paragon to 14.9.0

- src/pages-and-resources/discussions/app-list/FeatureList.test.jsx
- src/pages-and-resources/discussions/app-list/FeaturesList.jsx
TNL-8276: Mobile view feature list test cases added
> TNL-8276: Mobile view feature list test cases added

- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/FeatureList.test.jsx
- src/pages-and-resources/discussions/app-list/FeaturesList.jsx
- src/pages-and-resources/discussions/app-list/messages.js
Added new discussions providers  messages.js list, and minor style fix to accommodate small text descriptions
Note: Will be merged in sync with  https://github.com/edx/edx-platform/pull/27561
> Added new messages for new discussion providers

- package-lock.json
- package.json
> chore: bump paragon

- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
- src/pages-and-resources/discussions/app-list/FeaturesTable.test.jsx
- Add test cases for features table component
https://openedx.atlassian.net/browse/TNL-8250
> test: add features table test cases

- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
> feat: Add Incomplete error state in stepper

- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
https://openedx.atlassian.net/browse/TNL-8346
1.  Deletion functionality will not available for default general topic.
2. Deletion functionality will available for 
Additional discussion topic.
> feat: remove deletion functionality for default discussion topic

- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
https://openedx.atlassian.net/browse/TNL-8382
> test: add test cases for discussion topics

- package-lock.json
- package.json
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-list/AppCard.test.jsx
Upgrade paragon to the latest
[TNL-8399](https://openedx.atlassian.net/browse/TNL-8399)
> chore: upgrade paragon

- src/pages-and-resources/discussions/app-config-form/apps/shared/AppExternalLinks.jsx
- header thickness fix for External links separator 
- remove launch icon prop for hyperlink
> style: LTI form review fixes

- package-lock.json
- package.json
> refactor: upgrade frontend-platform

- package-lock.json
- package.json
> Bump Paragon to latest

- package-lock.json
- package.json
https://openedx.atlassian.net/browse/TNL-8406
Updated Paragon version to 14.16.7
> chore: updated paragon version

- src/pages-and-resources/data/api.js
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/app-list/messages.js
- src/pages-and-resources/discussions/messages.js
https://openedx.atlassian.net/browse/TNL-8404
Updated messages to match Figma
> fix: updated messages

- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/app-list/messages.js
https://openedx.atlassian.net/browse/TNL-8404
Remove edx-next related messages and updated some more messages to match figma
This requires https://github.com/edx/edx-platform/pull/28059 to be merged and deployed first
> fix: remove edx-next messages, updated messages

- src/CourseAuthoringPage.jsx
- src/CourseAuthoringPage.test.jsx
- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/data/selectors.js
- src/pages-and-resources/data/slice.js
- src/pages-and-resources/data/thunks.js
https://openedx.atlassian.net/browse/TNL-8149%22
Added permission alert in case of 403 from course API
> feat: Added permission alert in pages

- package-lock.json
- package.json
Paragon Features: 
* add more spacers that land on design spec
Paragon Fixes:
* remove last margin of elements in Alert 
* remove opacity on stateful button
* fixes alert heading style
* remove support for component labels in Pagination
frontend-build
* use NewRelicSourceMapPlugin to upload source maps to New Relic
> build: upgrade frontend-build to v7 and paragon to v16

- package-lock.json
- package.json
- src/CourseAuthoringPage.test.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
- src/pages-and-resources/discussions/data/redux.test.js
- src/utils.js
- Implemented settings modal by using modal dialog in place of modal layer which fixes both version mobile and web version of design according to Figma
Ticket ID : [TNL-8477](https://openedx.atlassian.net/browse/TNL-8477) 
screen design Web
screen design Mobile
also bumped paragon to latest (16.3.2) for ensuring it works as expected
> style: design fix implemented by using modal dialog 

- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
1.  Refactor discussion topics test cases
2.  Add test cases for topic items
https://openedx.atlassian.net/browse/TNL-8520
> refactor: discussion topic test cases

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/messages.js
Ticket https://openedx.atlassian.net/browse/TNL-8515
- mobile view fix and vertical-align setting, and typo fix for live button
> style: live button style fixes

- src/pages-and-resources/PagesAndResources.jsx
> style: padding reduced to fix design issue

- src/pages-and-resources/pages/PageGrid.jsx
https://openedx.atlassian.net/browse/TNL-8475
> fix: updated grid styling on smaller devices

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.test.jsx
Ticket Id: [TNL-8436](https://openedx.atlassian.net/browse/TNL-8436)
In reference to the work done for legacy form fields validation, test cases are added for the use cases.
following test cases will be covered in this PR.
-duplicate errors
-required field errors
-help text use case
-topic list rendering
-stepper error
> test: test cases for discussion UI

- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/AppCard.test.jsx
- src/pages-and-resources/discussions/app-list/FeatureList.test.jsx
- src/pages-and-resources/discussions/app-list/FeaturesTable.test.jsx
- src/pages-and-resources/discussions/app-list/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
Updates "Partial Support" to "Basic Support"
Changes "edX" to Full Support.
Uses data from the api for support level.
Refactor some app messages.
https://openedx.atlassian.net/browse/TNL-8546
Related BE: https://github.com/edx/edx-platform/pull/28315
> fix: Update discussion provider featues

- src/CourseAuthoringPage.jsx
- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/FeaturesList.jsx
- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
- src/pages-and-resources/discussions/app-list/FeaturesTable.scss
- src/pages-and-resources/pages/PageCard.jsx
- src/pages-and-resources/pages/PageCard.scss
- src/utils.js
[TNL-8565](https://openedx.atlassian.net/browse/TNL-8565)
[TNL-8567](https://openedx.atlassian.net/browse/TNL-8567)
[TNL-8569](https://openedx.atlassian.net/browse/TNL-8569)
[TNL-8571](https://openedx.atlassian.net/browse/TNL-8571)
[TNL-8570](https://openedx.atlassian.net/browse/TNL-8570)
[TNL-8573](https://openedx.atlassian.net/browse/TNL-8573)
[TNL-8568](https://openedx.atlassian.net/browse/TNL-8568)
1.  Add spacing between footer and body content
2. Prevent app card selection when user click on show/hides supported feature in mobile view
3. Update page & resources title spacing for mobile view
4. Correct error state transition for blackout date field in legacy form
5. Set page & resources margin-left and right for mobile view
6. Feature list text and icon should not intersect in mobile …
> style: 1.4 content and style fixes 

- src/generic/FormSwitchGroup.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.scss
Modal dialog CSS issue fixed for scrollable content
> style: modal dialog issue

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
- src/proctored-exam-settings/data/thunks.js
Fixes an issue where the header was stuck in a loading state on the old proctored exam settings page.
> fix: update header loading state from old proctored exam settings

- src/pages-and-resources/data/thunks.js
TNL TICKET: https://openedx.atlassian.net/browse/TNL-8791
Pages and resources sorting updated to match with acceptance criteria.
> fix: fixed the ordering of pages and resources cards

- src/generic/FieldFeedback.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesInput.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/data/constants.js
Tickets: https://openedx.atlassian.net/browse/TNL-8802 and https://openedx.atlassian.net/browse/TNL-8809
> fix: transition fix and status fix added

- package-lock.json
- package.json
- src/data/constants.js
- src/generic/CollapsableEditor.jsx
- src/generic/FormikErrorFeedback.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/teams/GroupEditor.jsx
- src/pages-and-resources/teams/Settings.jsx
- src/pages-and-resources/teams/messages.js
This fixes the following issues:
TNL-8737: Description field should be larger
TNL-8738: Increase right and left padding in expanded card
TNL-8739: Expand/Collapse icon should have fixed position
TNL-8741: Remove field helper text on field error state
TNL-8742: Use consistent spacing between field and helper text
TNL-8743: Too much spacing above Save button
TNL-8744: remove field error states when re-focusing on field
TNL-8762: Copy changes to team configuration
TNL-8763: Radio button rendering issues
TNL-8764: Use lowercase "M" for "Public managed" and "Private managed" labels
TNL-8766: Match style of labels in collapsed card
https://user-images.githubusercontent.com/118837/135065152-5f4120e2-1fa9-40af-931e-ab0f452a164c.mp4
https://user-images.githubusercontent.com/118837/135065168-557955e …
> fix: improve styling and behaviour to match mockups [BD-38] [TNL-8730]

- package-lock.json
- package.json
- src/generic/DeletePopup.jsx
- src/generic/Loading.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/AppCard.test.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/pages/PageCard.jsx
- src/pages-and-resources/pages/PageCard.scss
- src/pages-and-resources/pages/PageGrid.jsx
[TNL-9692](https://openedx.atlassian.net/browse/TNL-9692)
- upgrade paragon version to 19.9.0
- Fix paragon card component breaking changes 
- Fix Spinner render text
**After paragon upgrade:**
> chore: upgrade paragon version

- Makefile
- package-lock.json
- package.json
[PROD-2472](https://openedx.atlassian.net/browse/PROD-2742) for reactifex update.
> feat: add edx/reactifex support

- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/data/api.js
- src/pages-and-resources/live/data/slice.js
- src/pages-and-resources/live/data/thunks.js
- src/store.js
Created the integration for course live
Ticket link
https://openedx.atlassian.net/browse/TNL-9606
> feat: course live integration

- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/data/api.js
- src/pages-and-resources/live/factories/mockApiResponses.jsx
Test cases added for live app settings.
Ticket:
https://openedx.atlassian.net/browse/TNL-9663
> test: live settings test cases

- package-lock.json
- package.json
v1.12 had an issue with the code button being removed instead of the code sample button.
> feat: frontend-lib-content-component v1.13

- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/data/thunks.js
- src/pages-and-resources/live/factories/mockApiResponses.jsx
- src/pages-and-resources/live/messages.js
Reverts openedx/frontend-app-course-authoring#296
Depends on backend change
> Revert "fix: remove PII sharing flag from live configuration"

- .github/workflows/validate.yml
JIRA: https://2u-internal.atlassian.net/browse/BOM-3412
> chore!: Dropped support for Node 12

- package-lock.json
- package.json
frontend-component-footer v10.1.6 -> v11.1.1
frontend-platform v1.15.5 -> v2.4.0
> Feat  dependency updates

- package-lock.json
- package.json
- src/pages-and-resources/live/BBBSettings.jsx
- src/pages-and-resources/live/BbbSettings.test.jsx
- src/pages-and-resources/live/LiveCommonFields.jsx
- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/ZoomSettings.jsx
- src/pages-and-resources/live/ZoomSettings.test.jsx
- src/pages-and-resources/live/constants.js
- src/pages-and-resources/live/data/api.js
- src/pages-and-resources/live/factories/mockApiResponses.jsx
- src/pages-and-resources/live/messages.js
Figma: https://www.figma.com/file/SeNpRff5HxzdpCgoD5pmlQ/Apps-and-resources-landing-page?node-id=6581%3A79582
TNL Ticket: https://2u-internal.atlassian.net/browse/INF-207
UI Screens
> feat: bbb screens integrated in live

- src/pages-and-resources/live/data/api.js
https://2u-internal.atlassian.net/browse/INF-478
> fix: fix crash issue on accessing undefined keys

- src/pages-and-resources/live/BBBSettings.jsx
- src/pages-and-resources/live/BbbSettings.test.jsx
- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/data/api.js
- src/pages-and-resources/live/factories/mockApiResponses.jsx
https://2u-internal.atlassian.net/browse/INF-487
don't show the free tier in options if the free tier is not available
> fix: dont show free tier in options if no free tier available

- renovate.json
Bad commit message, but this should make automerge work
> feat: set schedule to automerge minor changes

- README.rst
This updates the README to include brief documentation on the purpose of this MFE, the main features it provides, as well as their configuration and external requirements.
> docs: Document current feature-set of this MFE

- src/CourseAuthoringPage.jsx
Completes https://2u-internal.atlassian.net/browse/TNL-10242. Took path of least resistance.
> feat: remove default background color for editors

- package-lock.json
- package.json
YKTV releasing changes to editors (new PE widgets)
> feat: update FLCC to 1.99.0

- package-lock.json
- package.json
> feat: upgrade FLCC to 1.101.3

- package-lock.json
- package.json
chore: update frontend-lib-content-components to 1.113.0.
> chore: update frontend-lib-content-components to 1.113.0.

- package-lock.json
- package.json
chore: upgrade frontend-lib-content-components to 1.124.0.
> chore: upgrade frontend-lib-content-components to 1.124.0.

- src/CourseAuthoringRoutes.jsx
Small change to allow using video editor for uploading videos in a course.
> [BB-7157] Make blockid parameter optional

- src/CourseAuthoringRoutes.jsx
- src/CourseAuthoringRoutes.test.jsx
- src/selectors/VideoSelectorContainer.jsx
- src/selectors/__snapshots__/VideoSelectorContainer.test.jsx.snap
This branch adds some changes need to use the new video editor flow.
Internal Jira task: [FAL-3383](https://tasks.opencraft.com/browse/FAL-3383)
**Testing instructions**
- This branch is used to test https://github.com/openedx/edx-platform/pull/32024 and https://github.com/openedx/frontend-lib-content-components/pull/326
**Additional context**
- This branch was internal reviewed here: https://github.com/open-craft/frontend-app-course-authoring/pull/1#pullrequestreview-1392500946
**Release notes**
- Merge after https://github.com/openedx/frontend-lib-content-components/pull/326
> [FAL-3383] Implement new video UX flow on new video editor

- package-lock.json
- package.json
feat: update frontend-lib-content-components to v1.151.2
> feat: update frontend-lib-content-components to v1.151.2

- src/pages-and-resources/progress/Settings.jsx
This PR is a cherry picked from commit 51e5e7126c9ea6aa3dfa79469dec40cf23cd14fb merged in PR #495
> fix: cast progress graph configuration to string

- package-lock.json
- package.json
> feat: update flcc to 1.62.0

- src/pages-and-resources/xpert-unit-summary/appInfo.js
> fix: Change wording to not crowd xpert tile in preferences page

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/xpert-unit-summary/XpertUnitSummarySettings.jsx
- src/pages-and-resources/xpert-unit-summary/settings-modal/ResetIcon.jsx
- src/pages-and-resources/xpert-unit-summary/settings-modal/SettingsModal.jsx
- src/pages-and-resources/xpert-unit-summary/settings-modal/SettingsModal.scss
1. https://jira.2u.com/browse/ACADEMIC-16289
2. https://jira.2u.com/browse/ACADEMIC-16422
Settings modal UI fixes:
Hide badge when switch is off
> fix: xpert unit sumamries settings ui fixes

- src/grading-settings/GradingSettings.jsx
- src/grading-settings/assignment-section/assignments/AssignmentItem.jsx
- src/grading-settings/assignment-section/index.jsx
- src/grading-settings/grading-scale/GradingScale.jsx
JIRA Ticket: [TNL-10975](https://2u-internal.atlassian.net/browse/TNL-10975)
1. Remove `<hr>` from under assignment type header  
2. Fix sidebar wrap  
3. Change assignment type delete button to variant="outline-primary"  
4. Change new assignment type button to variant="primary"  
5. Fix skipped tests in src/CourseAuthoringRoutes.test.jsx
6. Add percent sign as a trailingIcon to assignment type weight  
7. Add button should have a tooltip that says “Add new grading segment”
> fix: grading page UI bugs

- src/generic/help-sidebar/messages.js
- src/schedule-and-details/ScheduleAndDetails.test.jsx
- src/schedule-and-details/basic-section/index.jsx
- src/schedule-and-details/details-section/index.jsx
- src/schedule-and-details/index.jsx
- src/schedule-and-details/introducing-section/introduction-video/messages.js
- src/schedule-and-details/license-section/license-selector/index.jsx
- src/schedule-and-details/requirements-section/index.jsx
- src/schedule-and-details/schedule-section/certificate-display-row/CertificateDisplayRow.jsx
JIRA Ticket: [TNL-10946](https://2u-internal.atlassian.net/browse/TNL-10946)
1. update sidebar to say schedule and details instead of details and schedule  
2. fix sidebar wrapping (look back at advanced settings)  
3. using dropdown backgrounds clear, change to white
4. size of invite students button 
5. size of course summary page 
6. read more settings button
fix color  
change icon to outline version  
fix top padding (16 px)  
7. Change youtube placeholder text to “YouTube video ID”  
8. Cert warning text should be above that line break, not below it.
> fix: schedule and details UI bugs

- src/course-team/CourseTeam.jsx
- src/course-team/add-team-member/AddTeamMember.jsx
- src/course-team/constants.js
- src/course-team/course-team-member/CourseTeamMember.jsx
- src/course-team/course-team-member/CourseTeamMember.scss
- src/course-team/course-team-member/messages.js
- src/course-team/info-modal/InfoModal.jsx
- src/course-team/info-modal/messages.js
- src/course-team/utils.js
JIRA Ticket: [TNL-10982](https://2u-internal.atlassian.net/browse/TNL-10982)
1. Change add team member variant to primary
2. Change delete user button to an icon button with tooltip
3. Change delete confirmation to use primary colors
4. Update badge colors to be `primary-700` for admin and `gray-500` for staff
> fix: course team UI bugs

- src/studio-header/HeaderBody.jsx
- src/studio-header/utils.js
JIRA Ticket: [TNL-11083](https://2u-internal.atlassian.net/browse/TNL-11083)
This PR fixes the title typo for the link to course team in the setting dropdown. Additionally this PR adds the missing user menu on the home page.
> fix: missing header items

- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/scss/AdvancedSettings.scss
- src/course-team/CourseTeam.jsx
- src/course-team/CourseTeam.scss
- src/generic/help-sidebar/HelpSidebar.scss
- src/grading-settings/GradingSettings.jsx
- src/grading-settings/scss/GradingSettings.scss
- src/schedule-and-details/ScheduleAndDetails.scss
- src/schedule-and-details/index.jsx
- fixed top margin for Sidebar component (Advanced settings, Course team, Grading settings, Schedule and details).
> fix: fixed sidebar margin top

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/index.scss
- src/files-and-videos/videos-page/VideosPage.jsx
JIRA Tickets: [TNL-11089](https://2u-internal.atlassian.net/browse/TNL-11089), [TNL-11090](https://2u-internal.atlassian.net/browse/TNL-11090), [TNL-11214](https://2u-internal.atlassian.net/browse/TNL-11214)
> 1. Page color should be Light 200 from Paragon system
> 2. Page left/right margins should match what we are using on new MFE pages, ok to follow Advanced settings page as an example -  275px margin on each side.
> 3. There are 24px between cards vertically and horizontally
Before
After
> fix: general page layout and colors

- src/files-and-videos/generic/FileMenu.jsx
- src/files-and-videos/generic/messages.js
- src/files-and-videos/generic/table-components/table-custom-columns/MoreInfoColumn.jsx
- src/files-and-videos/index.scss
JIRA Ticket: [TNL-11213](https://2u-internal.atlassian.net/browse/TNL-11213)
> Make menu dropdown in the list view match the style of the menu dropdown in the card view (see image below for desired styles)
> ![image](https://github.com/openedx/frontend-app-course-authoring/assets/42981026/f83a7572-fca3-447d-bae5-d218bb87ee4f)
Before
After
> fix: list more info menu styles

- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/data/api.js
- src/generic/data/api.test.js
- src/studio-home/organization-section/OrganizationSection.test.jsx
This is a backport to Quince of https://github.com/openedx/frontend-app-course-authoring/pull/706.
> [Quince backport] fix: Fix data API URL handling

- package-lock.json
- package.json
This PR bumps @edx/frontend-component-ai-translations-edx package
> fix: bump ai translations component

- package-lock.json
- package.json
Reverts openedx/frontend-app-course-authoring#695
> Revert "chore(deps): update dependency @edx/frontend-build to v13.0.14"

- package-lock.json
- package.json
Addresses `App configuration error: AI_TRANSLATIONS_BASE_URL` console error log issue that occurs when frontend-component-ai-translations-edx is being loaded into the app
> fix: bump frontend-component-ai-translations-edx version

- package-lock.json
- package.json
This upgrade includes the fix for uploading videos in the video editor
> feat: bump frontend-lib-content-components

- src/CourseAuthoringPage.jsx
- src/advanced-settings/AdvancedSettings.jsx
- src/advanced-settings/AdvancedSettings.test.jsx
- src/advanced-settings/setting-card/SettingCard.jsx
- src/course-team/CourseTeam.jsx
- src/course-team/CourseTeam.test.jsx
- src/course-team/hooks.jsx
- src/course-updates/CourseUpdates.jsx
- src/course-updates/CourseUpdates.test.jsx
- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/generic/create-or-rerun-course/factories/mockApiResponses.jsx
- src/generic/data/api.js
- src/generic/data/api.test.js
- src/generic/hooks.jsx
- src/header/Header.jsx
- src/header/utils.js
- src/header/utils.test.js
- src/pages-and-resources/PagesAndResources.jsx
- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
This PR is to check the right user permissions on the following pages:
- Course Updates and Handouts
- Pages & Resources (Files & Videos)
- Advanced Settings
Note: This is a PR to a feature branch.
> [ROLES-41] Permission checks

- jest.config.js
- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/PagesAndResources.test.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/learning_assistant/Settings.jsx
- src/pages-and-resources/learning_assistant/Settings.test.jsx
- src/pages-and-resources/learning_assistant/messages.js
- src/pages-and-resources/utils.test.jsx
**Jira**: [COSMO-136](https://2u-internal.atlassian.net/browse/COSMO-136) and [COSMO-137](https://2u-internal.atlassian.net/browse/COSMO-137)
**NOTE**: This pull request should not be merged until the we receive privacy-approved copy.
This pull request adds a page and a settings modal for the Xpert Learning Assistant feature to the Pages and Resources page.
This pull request also contains refactoring necessary to include this page on the Pages and Resources page.
Note that this pull request is related to the backend changes to add a `CourseApp` for this feature: https://github.com/edx/learning-assistant/pull/52.
https://github.com/openedx/frontend-app-course-authoring/assets/11871801/cce74ac9-8be0-4ad0-9a6b-a39487a7dc22
> Add settings modal for Xpert Learning Assistant feature.

- jest.config.js
- package-lock.json
- package.json
- src/editors/EditorContainer.test.jsx
- src/head/Head.test.jsx
- src/pages-and-resources/ora_settings/Settings.test.jsx
- src/pages-and-resources/ora_settings/__snapshots__/Settings.test.jsx.snap
- src/selectors/VideoSelectorContainer.test.jsx
- src/setupTest.js
This PR migrates the `enzyme` to `RTL` and `@edx/react-unit-test-utils`.
> feat: migrate enzyme to RTL and react-unit-test-utils

- src/export-page/CourseExportPage.scss
- src/export-page/export-stepper/ExportStepper.scss
Fixed UI problem in discussions settings stepper. This bug made in this PR https://github.com/openedx/frontend-app-course-authoring/pull/586
Before fix
After fix
> fix: Paragon stepper fix inside discussions settings

- src/files-and-videos/generic/table-components/sort-and-filter-modal/SortAndFilterModal.jsx
- src/generic/SelectableBox/SelectableBoxSet.jsx
- src/generic/SelectableBox/getInputType.jsx
- src/generic/SelectableBox/index.jsx
step 1 for trying fixes for the stage bug. Here I just replace the paragon component with our identical copy to see what that changes. Followup steps are to change this component until hopefully the problem gets fixed.
> fix: replace paragon checkbox select set with copy to debug

- CODEOWNERS
Continuing maintainership updates for 2U 2024.
> chore: update CODEOWNERS with new team

- package-lock.json
- package.json
This PR upgrade `@edx/frontend-lib-content-components`. See frontend-lib-content-components PR #[465](https://github.com/openedx/frontend-lib-content-components/pull/465) for details
> feat: upgrade frontend-lib-content-components

- src/course-rerun/hooks.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/create-or-rerun-course/hooks.jsx
- src/studio-home/card-item/index.jsx
Corrected a possible error that periodically appears after clicking the "Create rerun" button.
Issue: https://github.com/openedx/frontend-app-course-authoring/issues/977
https://github.com/openedx/frontend-app-course-authoring/assets/93188219/a527f164-ca6f-46d2-87c0-57629794a126
> fix: fixed rerun link

- src/grading-settings/deadline-section/DeadlineSection.test.jsx
- src/grading-settings/deadline-section/index.jsx
Backport https://github.com/openedx/frontend-app-course-authoring/pull/1064 for the redwood release. 
Resolves https://github.com/openedx/wg-build-test-release/issues/365
> fix: allow grace period minutes only (#1064)

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/data/api.js
- src/course-outline/messages.js
- src/header/utils.js
Cherry pick of https://github.com/openedx/frontend-app-course-authoring/pull/995 to Redwood
> [Cherry pick] feat: Show toast when exporting course tags

- package-lock.json
- package.json
FLCC version update for 
https://github.com/openedx/frontend-lib-content-components/pull/475
> feat: flcc to 2.2.0

- plugins/course-apps/proctoring/Settings.test.jsx
- src/certificates/layout/header-buttons/HeaderButtons.test.jsx
- src/course-checklist/ChecklistSection/ChecklistItemComment.jsx
- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/generic/table-components/GalleryCard.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/modal-dropzone/ModalDropzone.test.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DiscussionRestriction.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-restrictions/RestrictDatesInput.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-restrictions/RestrictionSchedules.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/schedule-and-details/ScheduleAndDetails.test.jsx
- src/studio-home/StudioHome.test.jsx
- src/studio-home/collapsible-state-with-action/CollapsibleStateWithAction.test.jsx
- src/studio-home/organization-section/OrganizationSection.test.jsx
- src/studio-home/processing-courses/course-item/CourseItem.test.jsx
- src/taxonomy/TaxonomyLayout.test.jsx
- src/taxonomy/taxonomy-card/TaxonomyCard.test.jsx
- src/taxonomy/taxonomy-detail/TaxonomyDetailSideCard.test.jsx
This PR fixes a number of issues that raise warnings in the tests. These issues were revealed while working on https://github.com/openedx/frontend-app-course-authoring/pull/1052, but can be fixed independently of that upgrade.
Private-ref: [FAL-3750](https://tasks.opencraft.com/browse/FAL-3750)
Manual testing shouldn't be needed -- code review + CI passing should be sufficient.
See individual commits for explanations of the changes made.
> Fix some test warnings

- src/course-outline/data/thunk.js
- src/course-outline/page-alerts/PageAlerts.jsx
- src/course-outline/page-alerts/messages.js
Displays generic error message similar to legacy on server error and only shows unique errors.
Closes: #1073
`Private-ref`: [BB-8944](https://tasks.opencraft.com/browse/BB-8944)
Refer test instructions in https://github.com/openedx/frontend-app-course-authoring/pull/972
> refactor: show generic message on studio server error

- package-lock.json
Reverts openedx/frontend-app-course-authoring#1140
Reverts effect of https://github.com/openedx/frontend-lib-content-components/pull/490
> Revert "fix(deps): update dependency @edx/frontend-lib-content-components to v2.4.3"

- package-lock.json
- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/generic/clipboard/paste-component/components/WhatsInClipboard.jsx
- src/generic/clipboard/paste-component/index.jsx
- src/search-modal/SearchFilterWidget.tsx
- src/search-modal/SearchResult.tsx
This is a revised version of the version bump PR https://github.com/openedx/frontend-app-course-authoring/pull/1130 but with additional fixes for the type errors.
> Version bump for Paragon to 22.6.1, with stricter typing

- .github/workflows/lockfileversion-check.yml
Workflow for version check on lockfile updated
> perf: lockfile version check workflow file updated

- src/library-authoring/library-info/LibraryInfoHeader.tsx
- src/library-authoring/library-sidebar/LibrarySidebar.tsx
Fix the UI issues commented in: https://github.com/openedx/frontend-app-course-authoring/issues/1041#issuecomment-2317756727
Github Issue: https://github.com/openedx/frontend-app-course-authoring/issues/1041#issuecomment-2317756727
Internal ticket: [FAL-3822](https://tasks.opencraft.com/browse/FAL-3822)
- Open a library in studio to go to the library home.
- Open the library info sidebar and verify that the issues are fixed
> style: Nits on Library Info Sidebar [FC-0059]

- src/search-manager/FilterByBlockType.tsx
Fix the inconsistency with the select all functionality in problem capa type filter
Reported issue: https://github.com/openedx/frontend-app-authoring/issues/1196#issuecomment-2339361630
Internal ticket: [FAL-3844](https://tasks.opencraft.com/browse/FAL-3844)
- Follow the same steps of the [video](https://github.com/openedx/frontend-app-authoring/issues/1196#issuecomment-2339361630) and verify that the issue is gone
> fix: inconsistency with the select all functionality [FC-0059]

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/add-content/AddContentWorkflow.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/messages.ts
- src/studio-home/StudioHome.tsx
- src/studio-home/hooks.jsx
Backports https://github.com/openedx/frontend-app-authoring/pull/1449 to sumac.
See https://github.com/openedx/frontend-app-authoring/pull/1449
> [sumac] Hide / error on Libraries v2 pages if !librariesV2Enabled [FC-0062]

- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
Backports https://github.com/openedx/frontend-app-authoring/pull/1468 to sumac.
Relates to: https://github.com/openedx/frontend-app-authoring/issues/1456
Private-ref: [FAL-3873](https://tasks.opencraft.com/browse/FAL-3873)
See https://github.com/openedx/frontend-app-authoring/pull/1468
> [sumac] fix: show a more detailed error on Bad Request [FC-0062]

- src/hooks.ts
This PR fixes the infinite scroll, which doesn't fetch new data if all the components from the first load fit on the page.
- https://github.com/openedx/frontend-app-authoring/issues/1479
1. Before checking out this branch, reproduce the bug from https://github.com/openedx/frontend-app-authoring/issues/1479 (you will need a library with more than 20 components).
2. Checkout this branch, and check if it fixes the issue
___
Private ref: [FAL-3942](https://tasks.opencraft.com/browse/FAL-3942)
> fix: infinite scroll bug on library page [FC-0062]

- README.rst
This is just a minor documentation improvement.
> docs: minor README improvements

- src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.tsx
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
Backport of https://github.com/openedx/frontend-app-authoring/pull/1534
Cherry-pick of https://github.com/openedx/frontend-app-authoring/commit/a0f6f4357efec543031692a6b18e49d3d4f74f68
> [sumac] fix: Show published OLX in Library Content Picker [FC-0062] (#1534)

- src/library-authoring/LibraryAuthoringPage.tsx
- src/search-manager/SearchManager.ts
Backport of: https://github.com/openedx/frontend-app-authoring/pull/1530
> fix: avoid changing url when removing filters (#1530)

- src/generic/processing-notification/ProcessingNotification.test.jsx
- src/generic/processing-notification/index.jsx
- src/generic/toast-context/index.test.tsx
- src/library-authoring/library-team/LibraryTeam.test.tsx
- src/library-authoring/library-team/LibraryTeam.tsx
- src/library-authoring/library-team/messages.ts
Backport of https://github.com/openedx/frontend-app-authoring/pull/1543
Cherry-pick of https://github.com/openedx/frontend-app-authoring/commit/d2d753203fb9cfd60059c488f0f2c0783a4b021a
> [sumac] fix: Update error messages when adding user to library [FC-0062] (#1543)

- src/search-manager/data/api.ts
Just a small update to a comment in the code, now that Meilisearch has new functionality that implements a feature we need.
> docs: clarify/update a TODO comment about Meilisearch functionality

- src/generic/create-or-rerun-course/hooks.jsx
- src/library-authoring/create-library/CreateLibrary.test.tsx
- src/library-authoring/create-library/CreateLibrary.tsx
- src/studio-home/__mocks__/studioHomeMock.js
Backports https://github.com/openedx/frontend-app-authoring/pull/1582 + https://github.com/openedx/frontend-app-authoring/pull/1689 to Sumac.
* Part of: https://github.com/openedx/frontend-app-authoring/issues/1577
* Depends on: https://github.com/openedx/edx-platform/pull/36288
* Private-ref: [FAL-4089](https://tasks.opencraft.com/browse/FAL-4089)
1. Ensure you're running https://github.com/openedx/edx-platform/pull/36288 in your sumac dev stack.
1. See https://github.com/openedx/frontend-app-authoring/pull/1582 for testing instructions.
2. See https://github.com/openedx/frontend-app-authoring/pull/1689 for testing instructions.
> [sumac] fix: allow user provided value if can auto-create orgs [FC-0076]

- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/create-unit/CreateUnitModal.tsx
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/units/LibraryUnitPage.tsx
Ooops, somehow GitHub/CI didn't catch that https://github.com/openedx/frontend-app-authoring/pull/1812 would cause errors when merged, due to some conflicts. I have fixed those conflicts here in this PR.
> fix: merge errors in previous commit

- src/course-libraries/CourseLibraries.tsx
- src/course-libraries/ReviewTabContent.tsx
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/hooks.js
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
- src/editors/containers/ProblemEditor/data/OLXParser.js
- src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
- src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
- src/editors/containers/ProblemEditor/data/SettingsParser.js
- src/editors/data/redux/problem/reducers.ts
- src/editors/data/redux/thunkActions/problem.ts
- src/editors/data/redux/thunkActions/video.js
- src/editors/sharedComponents/TypeaheadDropdown/FormGroup.jsx
- src/files-and-videos/generic/table-components/TableActions.jsx
- src/generic/course-upload-image/index.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-restrictions/DiscussionRestrictionItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/utils.js
- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
Incorrect lodash imports are causing MFEs to import the entire lodash library. This change shaves off a few kB of every MFE compressed build.
> feat: lighter build by rewriting lodash imports

- src/pages-and-resources/pages/PageSettingButton.jsx
- src/pages-and-resources/pages/PageSettingButton.test.jsx
Reverts openedx/frontend-app-authoring#1831
> Revert "fix: use navigate instead of Link from react-dom"

- package-lock.json
- package.json
ticket: [TNL-11947](https://2u-internal.atlassian.net/browse/TNL-11947)
> chore: upgrade footer version

- plugins/course-apps/live/BBBSettings.jsx
- plugins/course-apps/live/LiveCommonFields.jsx
- plugins/course-apps/live/Settings.jsx
- plugins/course-apps/live/ZoomSettings.jsx
- plugins/course-apps/proctoring/Settings.jsx
- plugins/course-apps/progress/Settings.jsx
- plugins/course-apps/teams/GroupEditor.jsx
- plugins/course-apps/teams/Settings.jsx
- plugins/course-apps/wiki/Settings.jsx
- plugins/course-apps/xpert_unit_summary/Settings.jsx
- plugins/course-apps/xpert_unit_summary/settings-modal/SettingsModal.jsx
- src/CourseAuthoringRoutes.jsx
- src/custom-pages/CustomPageCard.jsx
- src/custom-pages/CustomPages.jsx
- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/pages/PageGrid.jsx
- injectIntl is deprecated, Used useIntl() hook instead.
- It was causing below error in `page and resources` Page.
using 
- ErrorLog
```
React Router caught the following error during render TypeError: r is not a function {
"componentStack": "
at A (https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:5259944)
at Suspense
at d (https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:65420)
at t (https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:7316739)
at g (https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:8043115)
at w (https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:4746781)
at div
at https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:6453516
at div
at https://course-authoring.edx.org/817.bfc0047cf532fb354633.js:2:7 …
```
> fix: TypeError r is not a function

- src/course-libraries/ReviewTabContent.tsx
(cherry picked from commit bc18fffedf4be5be45a29d8c921840af86dbaab7)
Backport of https://github.com/openedx/frontend-app-authoring/pull/1865
> refactor: remove custom order function from course libraries list

- src/library-authoring/data/apiHooks.ts
Backports https://github.com/openedx/frontend-app-authoring/pull/1925 to teak.
* Part of https://github.com/openedx/frontend-app-authoring/issues/1871
* Depends on https://github.com/openedx/edx-platform/pull/36687
* Private ref: [FAL-4156](https://tasks.opencraft.com/browse/FAL-4156)
See https://github.com/openedx/frontend-app-authoring/pull/1925
> [TEAK] fix: invalidate search results when publishing all changes in library [FC-0083]

- src/generic/DraggableList/SortableItem.jsx
- src/library-authoring/components/BaseCard.scss
- src/library-authoring/components/BaseCard.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/index.scss
Backport of https://github.com/openedx/frontend-app-authoring/pull/1918
- https://github.com/openedx/frontend-app-authoring/issues/1792
Check https://github.com/openedx/frontend-app-authoring/pull/1918
___
Private ref: [FAL-4144](https://tasks.opencraft.com/browse/FAL-4144)
> fix: improve focus/selected style on library authoring [teak]

- src/course-outline/subsection-card/SubsectionCard.jsx
Implements: https://github.com/openedx/frontend-app-authoring/pull/1938#discussion_r2085075202
> chore: add comment to prevent course search reload on type

- catalog-info.yaml
Per https://discuss.openedx.org/t/frontend-app-authoring-maintanership-transfer/15786 I am taking over maintainership of this repo from 2U TNL.
> docs: update maintainer to me in catalog-info.yaml

- src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
- src/generic/inplace-text-editor/index.tsx
- src/library-authoring/collections/CollectionInfoHeader.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/containers/ContainerInfoHeader.tsx
- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.test.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
Backport of https://github.com/openedx/frontend-app-authoring/pull/1953
- Related to https://github.com/openedx/frontend-app-authoring/issues/1849
Check https://github.com/openedx/frontend-app-authoring/pull/1953
___
> fix: change InplaceTextEditor style and add optimistic update [teak]

- src/library-authoring/generic/status-widget/index.tsx
- src/library-authoring/library-info/LibraryPublishStatus.tsx
- src/library-authoring/library-info/messages.ts
Backport of #1993 and #2016 
- Related to https://github.com/openedx/frontend-app-authoring/issues/1467 and https://github.com/openedx/frontend-app-authoring/issues/1467#issuecomment-2897986744
Check #2016
___
> fix: rename library publish button [teak]

- src/course-outline/CourseOutline.test.jsx
- src/course-outline/hooks.jsx
[INF-1906](https://2u-internal.atlassian.net/browse/INF-1906)
I have passed the course ID to the syncDiscussionsTopics function and fixed all related test cases.
> fix: passed course id and fixed test cases

- src/library-authoring/components/BaseCard.scss
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/index.scss
Backport of https://github.com/openedx/frontend-app-authoring/pull/2045
Related to: https://github.com/openedx/frontend-app-authoring/issues/1792#issuecomment-2894950598
Check  https://github.com/openedx/frontend-app-authoring/pull/2045
> fix: selection card wiggle [teak]

- src/generic/inplace-text-editor/index.tsx
- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
Backport of https://github.com/openedx/frontend-app-authoring/pull/2008
- Related to https://github.com/openedx/frontend-app-authoring/issues/1878
Check https://github.com/openedx/frontend-app-authoring/pull/2008
___
Private ref: [FAL-4158](https://tasks.opencraft.com/browse/FAL-4158)
> fix: set unit preview readonly on sidebar [teak]

- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/files-and-videos/videos-page/VideoThumbnail.test.jsx
Backports https://github.com/openedx/frontend-app-authoring/commit/0117c1eae367db05e5fc3875256d29c1237f8917 to release/teak.
> [backport] fix: allow thumbnail upload on Videos page if no thumbnail (#2388)
