- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
- src/setupTest.js
- Sets “Create Zendesk tickets for suspicious proctored exam attempts” to 'false' by default if “proctortrack” is selected as proctoring provider. 
- Sets “Create Zendesk tickets for suspicious proctored exam attempts” to 'true' by default if “software_secure” is selected as proctoring provider.
> Add Frontend Proctoring Provider Specific Defaults for Exam Settings

- package-lock.json
- package.json
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
- src/setupTest.js
If user is not edX Staff and the current date is after the course start date, modifications to the proctoring provider is not allowed
- this is done by marking non-selected options as disabled. I chose the disabled attribute because aria-disabled still allows options to be chosen/clickable. By disabling only certain options, a screen reader will still be able to focus on the proctoring provider field and read the option that is selected, but the field itself will not be modifiable (because only one option is enabled).
- Users that have the administrator role are always allowed to modify this field. In getAuthenticatedUser(), administrator denotes GlobalStaff permissions.
If proctortrack is the chosen provider, a valid email must be provided
- After feedback from David Joy, I chose to use …
> Add existing validation logic to Proctored Exam Settings Page for Parity

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Pleas review.
This is the PR to hide the Proctortrack Escalation Email field if the backend is not proctortrack.
> MST-335 Hide the Proctortrack Escalation Email field if the Provider backend is not Proctortrack

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
If a user is not edX staff, the fields "Enable Proctored Exams" and "Create Zendesk Tickets for Suspicious Proctored Exam Attempts" will not be displayed. 
I did not change the order of the fields because UX said that the correct context is more important than grouping fields that will be hidden together.
> Changes what fields are displayed depending on user role

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
@edx/masters-devs-cosmonauts Please review
In this PR, we hide all the other form fields if the "Enable Proctored Exams" radio button is selected as false.
See screenshot:
> MST-342 Hide all other fields if enableProctoredExam is false

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
Prevents a page reload when the enter key is pressed in an input field, and instead submits the form.
> Submit form when enter key is pressed

- src/CourseAuthoringRoutes.jsx
- src/discussion-tool-selector/DiscussionToolSelector.scss
- src/discussion-tool-selector/DiscussionToolSelector.test.jsx
- src/discussion-tool-selector/DiscussionToolSelectorContainer.jsx
- src/discussion-tool-selector/discussion-tool-selector/DiscussionToolSelector.jsx
- src/discussion-tool-selector/discussion-tool-selector/discussion-tool-option/DiscussionToolOption.jsx
- src/discussion-tool-selector/discussion-tool-selector/features-table/FeaturesTable.jsx
- src/discussion-tool-selector/messages.js
- src/index.jsx
- src/index.scss
This is an initial implementation of the discussion tool selection page.  It doesn't do anything yet, and can't open modals for configuring selected tools.
This incorporates commits from @aayushagra's PR here: #36. 
I've rebased it on master and tweaked the route URL scheme, then made some cursory styling tweaks and stubbed out a "Configure forums" button.  
This page will be accessible only by knowing the URL to it, so it's safe to merge to master even though it's not done.
FYI @xitij2000
> Discussion tool selection page skeleton

- src/pages-and-resources/discussions/DiscussionAppCard.jsx
- src/pages-and-resources/discussions/DiscussionAppList.jsx
- src/pages-and-resources/discussions/DiscussionAppList.scss
- src/pages-and-resources/discussions/FeaturesTable.jsx
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/data/thunks.js
- src/pages-and-resources/discussions/messages.js
- src/store.js
This pulls all the data loading logic out of the React components and makes it significantly more flexible.
- Both apps and features have IDs and can be looked up in the store.
- The API layer is currently just returning hard coded data.
- LOADED and LOADING statuses are available to implement loading spinners and feedback.
- The taxonomy has been changed a bit - “forums and “tools” are now consistently referred to as “apps” - this code is almost completely agnostic to discussions, meaning that it could easily be repurposed for other kinds of apps, such as proctoring providers.
> Backing discussions with data API/thunks/reducer.

- src/pages-and-resources/discussions/AppCard.jsx
- src/pages-and-resources/discussions/ConfigFormContainer.jsx
- src/pages-and-resources/discussions/FeaturesTable.jsx
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/data/thunks.js
- src/pages-and-resources/discussions/messages.js
Prior to this, the list of providers in the UI was hardcoded in the api.js layer.
This commit hooks that up to our actual API endpoint, allowing us to load the provider list from the server.
It also - out of necessity - changes the way the AppCards are displayed, and what content is in them.  This was somewhat opportunistic as our design for them simplified anyway, no longer requiring a logo or a few of the other fields.
Because the actual API sends us less display-oriented data (i.e., no names or descriptions for things), we had to modify FeaturesTable and AppCard to fetch these strings from the messages file based on the app and feature IDs.
I’m not super thrilled with this approach, since it’s somewhat brittle.  Unexpected providers won’t display properly.  In the long run, I expect …
> feat: hook discussions provider list up to API

- package-lock.json
- package.json
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
- src/setupTest.js
- This uses a new function in frontend-platform 1.9.0 that sets up a mock application for use in test suites.
- The ProctoredExamSettings.test.jsx tests have been refactored to use axios-mock-adapter and initializeMockApp.
- A tweak was made to ProctoredExamSettings to use error.response.status instead of error.customAttributes.httpErrorStatus - the former is a more canonical way of getting at this data, rather than using the customAttributes object we add to our errors.  It also means the code will work with the MockAuthService instead of AxiosJwtAuthService.
> refactor: using initializeMockApp in ProctoredExamSettings tests

- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/proctored-exam-settings/ProctoredExamSettings.test.jsx
Prevent frontend errors for invalid proctoring escalation email if proctoring is disabled. This should be merged after the [PR for backend validation](https://github.com/edx/edx-platform/pull/27166) has been merged and deployed.
> Prevent frontend errors for escalation email if proctoring is disabled

- jest.config.js
- package-lock.json
- package.json
- src/generic/FormSwitchGroup.jsx
- src/pages-and-resources/discussions/ConfigFormContainer.jsx
- src/pages-and-resources/discussions/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/apps/legacy/LegacyConfigForm.test.jsx
- src/pages-and-resources/discussions/apps/shared/AnonymousPostingFields.jsx
- src/pages-and-resources/discussions/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/apps/shared/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/data/thunks.js
- src/setupTest.js
This PR is best reviewed commit-by-commit.
It refactors LegacyConfigForm in preparation for creation of "StandardConfigForm", which will be for configuring our new discussions MFE.  It also adds tests for LegacyConfigForm and fixes some issues in the data layer about how we were treating "displayed" vs. "active" app configs.  See relevant commits for more information.
> fix: improve app config forms, refactor LegacyConfigForm, add tests

- src/pages-and-resources/discussions/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/apps/shared/messages.js
The three fields in LtiConfigForm each get their validation/feedback hooked up properly, and the blackout dates field in LegacyConfigForm now uses a regex-based validator for blackout date strings.
> feat: adding form validation to LtiConfigForm and LegacyConfigForm

- src/pages-and-resources/discussions/Discussions.jsx
- src/pages-and-resources/discussions/messages.js
https://openedx.atlassian.net/browse/TNL-8096
“applied” and “applying” instead of “saved” and “saving”
> fix: consistent apply button labels

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/messages.js
Button is no longer included on the page, as per latest mocks.  Removing!
> fix: removing View Live button

- src/pages-and-resources/discussions/messages.js
[TNL-8108](https://openedx.atlassian.net/browse/TNL-8108)
Updated the heading text to match the Miro board
Before:
After:
> Updated heading text

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/app-list/data/api.js
- src/pages-and-resources/discussions/app-list/data/slice.js
This defaults our discussions provider to legacy if one was not specified by the backend.
It also fixes a few navigation and provider selection bugs that I encountered in testing the above.
Fixes: 
- https://openedx.atlassian.net/browse/TNL-8114
- https://openedx.atlassian.net/browse/TNL-8120
> fix: default discussions provider to legacy

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AnonymousPostingFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AppConfigFormDivider.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/app-list/messages.js
- src/pages-and-resources/discussions/messages.js
This fixes three issues:
1. The Stepper's first step was named incorrectly, it should be "Provider selection"
2. The form title should be inside the card and smaller
3. There should be horizontal dividers between all sections of the LegacyConfigForm, and one at the top of the LtiConfigForm.
This fixes or addresses parts of:
https://openedx.atlassian.net/browse/TNL-8119 - step names
https://openedx.atlassian.net/browse/TNL-8136 - dividers between card sections
https://openedx.atlassian.net/browse/TNL-8127 - headers above cards on step 2
> Update step names, form titles, and add dividers

- src/pages-and-resources/discussions/app-list/AppList.jsx
[TNL-8109](https://openedx.atlassian.net/browse/TNL-8109)
Updated heading styles to match the figma hifi. 
Figma expected headline
> Fixed heading styles

- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/messages.js
[TNL-8110](https://openedx.atlassian.net/browse/TNL-8110)
Updated card styles to match the Figma hifi. Also updated the text to match figma hifi.
Figma expected card style:
After changes
> Fixed card styles

- src/pages-and-resources/discussions/app-list/AppList.jsx
[TNL-8111](https://openedx.atlassian.net/browse/TNL-8111)
Updated vertical spacing above and below heading to match figma design
Figma screen (Expected):
> Fixed header margin

- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
[TNL-8113](https://openedx.atlassian.net/browse/TNL-8113)
Updated Check box color to match figma
Figma screen:
> Fixed icon color

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
[TNL-8116](https://openedx.atlassian.net/browse/TNL-8116)
Remove back button on step one
Figma screen (expected):
> Remove back button on step one

- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
[TNL-8123](https://openedx.atlassian.net/browse/TNL-8123)
Display remove icon in case feature is not available. Currently if a feature is available it displays a check icon and if it is not available it does not display anything.
Currently:
Figma design (expected):
> Added feature not available icon

- src/generic/Loading.jsx
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/setupTest.js
- src/studio-header/Header.jsx
We don’t have any need for a custom data-testid attribute, so removing it so it matches documentation and doesn’t confuse future testers.
> test: Use the standard data-testid attribute instead of a custom one

- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/FeaturesList.jsx
- src/pages-and-resources/discussions/app-list/messages.js
TNL-8268: Hide features table on mobile view and update mobile design according to figma.
new mobile designs in collapsed state
in expand state
figma design
-web design will remain unchanged and the  feature table will be hidden on mobile view
> TNL-8268: Hide features table on mobile view

- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
The application was expecting a different API shape than the server was sending.  I have _no_ idea how this made it through, as it’s blatantly broken.  I don’t see any changes in this code in the past few weeks.
Anyway, the client was expecting a “features” array inside an app (provider), which simply didn’t exist.  The app itself is the array.  This PR udpates the shape in `normalizeApps` and also the associated test, which was also equally as wrong.  Somehow.
> fix: update discussions API handler to match shape from server

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
> Fixed padding in discussion settings modal

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/messages.js
description
- Update piazza configuration form with paragon new form elements
- Use new floating form control element as input field
- Display incomplete error message on step 2 when validation fails 
Before
After new hifi design
Figma design
> style: update piazza config form according to hifi design

- package-lock.json
- package.json
Bump paragon to 14.11.2
This fixes the following
* update `statefulbutton` icons
* update Proptypes to avoid errors
> chore: bump paragon

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigFormSaveButton.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
This PR adds the following changes.
* Fixes a bug in `satefullbutton`
* Updates labels of `fullscreenmodal`
**Next**
**Save**
**Saving**
https://openedx.atlassian.net/browse/TNL-8320
> refactor: update full screen modal

- package-lock.json
- package.json
- src/pages-and-resources/discussions/app-config-form/AppConfigFormSaveButton.jsx
- src/pages-and-resources/discussions/app-list/AppListNextButton.jsx
- Removed unnecessary margins from buttons.
This pr originally contained design fixes for header/footer/stepper but after integrating stepper from paragon those changes become invalid, hence only these classes applied on next/apply buttons which were serving no purpose are removed from code.
- bumped paragon version to 14.11.4
screen after version update is attached
> style: margins removed from footer buttons.

- package.json
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/data/thunks.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
- Add UI for General discussion topics
- Modify formik form for handing the topic field 
- normalize discussion_topics response into formik required format
- de-normalise discussion_topics payload for post request
- Manage discussion_topics data in redux modal
- Store all discussionTopicsIds in discussion reducer
**Updated UI design screenshots:**
> feat: Add UI for Add Topics

- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
Replaced icon with button icon for the following actions in topics
1. expand
2. collapse
3. delete
Figma guidelines about using icon button is attached.
> style: added icon buttons for fixing hover styling for topic actions

- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AppExternalLinks.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
LTI config form title fixed for app providers and eternal link heading fixes for app provider which don't have any external link/contact email.
Ticket: Ticket: https://openedx.atlassian.net/browse/TNL-8401
Parent Ticket: https://openedx.atlassian.net/browse/TNL-7832
1. external links were implemented for app providers but some app providers were missing any external link. which creates undesired UI headings to fix that this PR is generated so that the external links section will only be visible for that provider which has external documentation links/contact emails.
2. a console error started appearing on UI since new providers were added, due to missing app names in i18n messages structures. the missing title has also been added to remove the issue.
> fix: LTI config form UI Fixes in App providers titles and external links.

- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
https://openedx.atlassian.net/browse/TNL-8257
1- If the discussion topic input field has a duplicate name or an empty input field error. It will not collapse the discussion topic card.
2- Empty input field discussion topic name will not be available in divideByCohorts section.
3- General discussion topic has help text.
4- Add topic button has interactive Plus icon
> feat: add collapsible card validation for empty field

- package-lock.json
- package.json
- src/pages-and-resources/discussions/DiscussionsSettings.jsx
In reference to this [ticket](https://openedx.atlassian.net/browse/TNL-8405) the shadow was appearing under the setting page content in the modal. to fix that update is made in paragon and course authoring MFE is bumped to the latest(14.16.9) paragon version and a class is removed which was creating an issue in the shadow position. 
The new screen is shown below.
> Update paragon to fix shadow under content issue 

- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigFormProvider.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/utils.js
- Display valid discussion topics in divide by cohorts section.
- Valid discussion topic will automatically added into cohorts section when use focus out from the discussion topic input field.
- Deleted discussion topic will also removed from divide by cohorts section. 
- Firstly created discussion topic will be shown in duplicate discussion topic.
> fix: display valid discussion topics in divide by cohorts section

- src/generic/FormSwitchGroup.jsx
- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
Styling fix for Calculator setting dialog.
> fix: styling fix to Calculator setting dialog.

- src/generic/status-badge/StatusBadge.jsx
Fix the badges within `frontend-app-course-authoring` to be consistent with Paragon badges.
https://paragon-edx.netlify.app/components/badge/
> fix: remove padding from badges to stay consistent with Paragon badges design.

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/messages.js
Ticket ID: [TNL-8515](https://openedx.atlassian.net/browse/TNL-8515)
-view live button is added to pages and resources screen according to the requirement given in the ticket
Screen after adding view live button
> feat: view live button added to pages and resources screen

- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
When fetching details for discussion providers from the API,
the `messages` field is used if available and
displayed in the configuration page for each provider.
The `messages` field is introduced in edx/edx-platform#28092
Related tickets:
* [TNL-8339](https://openedx.atlassian.net/browse/TNL-8339)
* [BB-4249 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4249)
Using a backend that includes edx/edx-platform#28092:
1. Open the discussion settings for a course
2. Select Discourse (the only provider with messages at the time of writing)
3. Verify that the config form displays the message "Discourse requires that LTI advanced sharing be enabled for your course, as this provider uses email address and username to personalize the experience. Please contact support@edx.org to enable …
> [BD-38][TNL-8339] feat: Use `messages` field from API

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/pages/PageCard.jsx
If an app has a legacy link and has no explicit support in the MFE,
a link is now rendered instead of the settings button.
After marking the `calculator` and `discussion` apps as supported, and running the backend with the changes in edx/edx-platform#28098, the page grid now looks like this:
Related tickets:
* [TNL-8438](https://openedx.atlassian.net/browse/TNL-8438)
* [BB-4416 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4416)
Using the backend changes in edx/edx-platform#28098:
1. Open the pages and resources page for the demo course
2. Verify that:
1. the settings button appears for "supported" apps (e.g. `calculator` and `discussion`)
2. the link to studio appear for non-supported apps with legacy links (e.g. `texbooks`)
3. Nothing appears for non-supported apps without …
> [BD-38][TNL-8438] Replace settings button with link for non-supported apps with legacy links

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
Adds a new UI to enable/disable sharing of PII for discussion providers if PII sharing is enabled for the course.
**Testing instructions**:
- Set up LTI discussions for a course by going to http://localhost:2001/course/{course_id}/pages-and-resources/discussion
- For this test the values supplied above don't matter
- Now visit http://localhost:18000/admin/lti_consumer/courseallowpiisharinginltiflag/ and create a new flag for the course and enable it
- Visit http://localhost:2001/course/{course_id}/pages-and-resources/discussion again and configure the discussion provider. 
- You should see options to disable or enable sharing the username and email. 
- You should be able to change these values, and have them persist on the server
- If you now disable or delete the flag at …
>  feat: add support for enabling/disabling LTI PII sharing  [BD-38] [BB-4511] [TNL-8529]

- src/pages-and-resources/pages/PageCard.jsx
Update textbooks card arrow icon to iconButton with perfect hover colour
> fix: Change textbooks card arrow icon to iconButton

- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/calculator/Settings.jsx
- src/pages-and-resources/calculator/messages.js
This updates the app settings page to use a link returned by the backend instead of using a hard-coded link in the frontend.
**JIRA tickets**: TNL-8446
**Dependencies**: https://github.com/edx/edx-platform/pull/28327
**Screenshots**: Always include screenshots if there is any change to the UI.
**Merge deadline**: "None" 
**Testing instructions**:
1. Test the associated edx-platform change: https://github.com/edx/edx-platform/pull/28327
2. Check that the URL in the calendar app matches the url returned by the API
3. Try changing the edx-platform help url for calendar and see that it's updated in the frontend
**Reviewers**
> feat: Get learn more links from the backend instead of hard-coding it in the frontend [BD-38] [TNL-8446] [BB-4462]

- src/pages-and-resources/proctoring/Settings.jsx
- src/pages-and-resources/proctoring/Settings.test.jsx
- src/pages-and-resources/proctoring/messages.js
[MST-859](https://openedx.atlassian.net/browse/MST-859)
Take the existing proctored exam settings form and add it to pages and resources as a modal. The code is largely taken directly from [ProctoredExamSettings.jsx](https://github.com/edx/frontend-app-course-authoring/blob/master/src/proctored-exam-settings/ProctoredExamSettings.jsx), with some modifications for readability.
> [MST-859] add proctoring settings modal to card view

- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/data/api.js
- src/pages-and-resources/data/selectors.js
- src/pages-and-resources/data/slice.js
- src/pages-and-resources/data/thunks.js
- src/pages-and-resources/edxnotes/Settings.jsx
- src/pages-and-resources/edxnotes/messages.js
- src/pages-and-resources/progress/Settings.jsx
- src/pages-and-resources/progress/messages.js
- src/pages-and-resources/wiki/Settings.jsx
- src/pages-and-resources/wiki/messages.js
- src/utils.js
This PR adds config forms for edxnotes, progress and wiki.
**JIRA tickets**: TNL-8101, TNL-8451, TNL-8452, TNL-8455
**Dependencies**: None
**Screenshots**: 
https://user-images.githubusercontent.com/118837/129155397-dcc8bb84-1db1-4338-a4fa-1d640ab00af2.mp4
Wiki settings
**Merge deadline**: None
**Testing instructions**:
The changes in this PR are currently visual only, and non-functional, so they mainly need to be compared with the mockups. 
(Note: wiki is currently not marked as configurable, but you can trigger its dialog here: http://localhost:2001/course/course-v1:edX+DemoX+Demo_Course/pages-and-resources/wiki/settings)
**Reviewers**
> feat: Adds settings pages for edxnotes, progress and wiki [BD-38] [TNL-8101] [TNL-8451] [TNL-8452] [TNL-8455]

- package-lock.json
- package.json
- src/generic/CollapsableEditor.jsx
- src/generic/DeletePopup.jsx
- src/generic/FieldFeedback.jsx
- src/generic/FormikFieldFeedback.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/LegacyConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/BlackoutDatesField.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesInput.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/CollapseCardHeading.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/messages.js
- src/pages-and-resources/discussions/app-config-form/utils.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/constants.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/utils.js
- User can add blackout dates range using paragon UI components
- Date and time field will use to select a blackout date range
- Each Field will validate and display corresponding helper/error messages
- User can add multiple blackout dates
- User can delete any blackout dates at any time
- Dates will order by status and dates
New UI:
Note:
- Test cases will be added in separate PR.
> feat: add blackout dates new UI and validation

- src/pages-and-resources/discussions/app-list/FeatureList.test.jsx
- src/pages-and-resources/discussions/app-list/FeaturesList.jsx
- src/pages-and-resources/discussions/app-list/SupportedFeature.jsx
- src/pages-and-resources/discussions/app-list/SupportedFeature.test.jsx
[TNL-8092](https://openedx.atlassian.net/browse/TNL-8092)
FeatureList Component Only renders in mobile view.
- Update responsive provider selection UI "features" layout
- Display only supported features in collapse card on mobile view
- Hide feature tables in mobile view
> fix: display only supported features in mobile view

- src/pages-and-resources/discussions/data/api.js
fix: undefined key fixed in case of empty lti configs
> fix: undefined key fixed in case of empty lti configs

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
https://openedx.atlassian.net/browse/TNL-9416
in LTI course discussion configuration different form Instructions messages were shown for admin and other accounts. So to align form instructions messages for every type of accounts. The admin will now be shown the following messages attached in the screenshot.
The experience for others will remain same as before
view for non admin accounts
> UI update for warnings and messages

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
PII values were passed in post API based on the PII keys returned from backend API, This has now been changed to PII flag value returned from API and changes are aligned with this backend PR
https://github.com/edx/edx-platform/pull/29628
> fix: pii sharing fields values are fixed in accordance with backend flag

- src/data/api.js
- src/data/thunks.js
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
[TNL-9420](https://openedx.atlassian.net/browse/TNL-9420)
Added username to the course detail api query params. The username query param is required and if not sent the api assumes that the requesting user is Anonymous
> fix: fixed course detail api params

- src/pages-and-resources/discussions/app-config-form/utils.js
Frontend was crashing on some edge cases of invalid blackout dates formats. This issue has been handled on frontend and screenshots are attached for both before and after condition, with same data returned from API.
Before Fix
After Fix Mocking same data returned in first case
TNL TICKET : [TNL-9404](https://openedx.atlassian.net/browse/TNL-9404)
> fix: blackout date frontend crash fix

- src/studio-header/DesktopHeader.jsx
- src/studio-header/Header.jsx
- src/studio-header/Header.messages.jsx
[TNL-9441 ](https://openedx.atlassian.net/browse/TNL-9441)
dropdown items font size is changed to 14px for matching studio header
header max-width class removed
missing menu items certificates added and **publisher omitted for now -- will be added in a separate PR**
> TNL-9441 : Course Authoring header fixes

- src/pages-and-resources/teams/GroupEditor.jsx
https://openedx.atlassian.net/browse/TNL-9463
Context: 
groups: teamsConfiguration?.teamSets || teamsConfiguration?.topics
groups can be team_sets or topics coming from already configured team sets from legacy UI. in case of topics the type field is missing in group data and types can be either `public` `private` or `open`
one such example of such course which is rendering error on MFE is https://course-authoring.edx.org/course/course-v1:edX+victor101+2017Run/pages-and-resources/teams/settings
all such topics having missing type fields in their data are rendered public for now to avoid UI crash.
> fix: team page crash issue fix

- src/studio-header/Header.jsx
- src/studio-header/Header.test.jsx
- src/studio-header/MobileHeader.jsx
https://openedx.atlassian.net/browse/TNL-9461
Improvements made in the desktop header -- set width to 25% so course name exceeding beyond the limit can be contained inside provided space. and tooltip is added on hover to view the full course name.
Course name removed from mobile header view to make it according to the Figma designs.
> fix: header improvements

- src/studio-header/Header.jsx
- src/studio-header/header.scss
Tooltip color changed to dark and name line-height improvement.
> fix: header course name ui improvement

- src/studio-header/header.scss
- Add space between course outline and title lines in the header
-  Update span line-height: 1rem to line-height:1.375rem and remove the unnecessary a tag line-height.
Before fix
After fix
> fix: line height of header course title

- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesItem.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- Add UTC timezone in time's field helper text and label. 
Before the update 
After the update
> feat: add UTC timezone in blackout date range

- package-lock.json
- package.json
An error in the content components caused the new html editor not to save. This will make it so it won't encode the destination uri twice.
> fix: update f-l-c-c version for editor save

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigFormSaveButton.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
[TNL-9511](https://openedx.atlassian.net/browse/TNL-9511)
- PII sharing fields are hidden for all LTI providers
- PII sharing option is not visible to any user (Global staff, educators)
- `enableEmailsharing` and `enableUsername` sharing depends on `allowPiiSharing flag`
**Global staff**
- LTI form fields are only visible to Global staff.
- LTI form message is updated to `This configuration will require sharing usernames and emails of learners and the course team with {providerName}`.
- LTI form instructions are visible.
- Save button is active for Global staff.
**Educators**
- LTI form fields are not visible to Educators.
- LTI form message is updated to `{providerName} can only be configured by {platformName} administrators. Please contact {supportEmail} to enable this feature. This …
> feat: hide PII sharing fields for LTI config

- src/pages-and-resources/teams/GroupEditor.jsx
> fix: revert gate to hide/show team TYPE configuration

- package-lock.json
- package.json
- src/CourseAuthoringPage.jsx
- src/CourseAuthoringPage.test.jsx
- src/CourseAuthoringRoutes.jsx
- src/setupTest.js
Because we are moving the v2 editor pages to be "fake" modals, which have no z-index, we need to discard the course authoring "loading" wheel for the header and footer. We also need to bump the version of f-l-c-c to bring in the new editor changes.
> feat: remove loading on editor pages

- src/generic/CollapsableEditor.jsx
- src/pages-and-resources/pages/PageCard.jsx
With the upgrade of the paragon, the version is bumped beyond https://github.com/edx/paragon/tree/v16.16.1 which added the default `onClick` param for `IconButton`. In this PR we are removing the unessassry `onClick` params. 
Quick Links:
https://github.com/openedx/paragon/pull/872
https://github.com/openedx/paragon/commit/2fef5ae49d2550389dee37f5c0ea92c597c5322c
> refactor: code for iconbutton usage

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/legacy/index.js
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigFormProvider.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/index.js
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.test.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/app-list/AppCard.test.jsx
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
- src/pages-and-resources/discussions/app-list/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/data/slice.js
- src/pages-and-resources/discussions/data/thunks.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
This adds support for configuring the new Open edX discussion provider. It expands on the features of the legacy configuration by adding additional ways to configure discussions.
Depends on: https://github.com/openedx/edx-platform/pull/29863
> feat: Add support for the new Open edX discussion provider [BD-38] [TNL-8622]

- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
[TNL-9598](https://openedx.atlassian.net/browse/TNL-9598)
- Display the same message for everyone (educators, global staff) during discussions provider (LTI) configuration
> fix: display same message for everyone during discussions provider configuration

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/app-list/messages.js
Both providers should have the same name.
> fix: remove new and legacy from discussion app names [BD-38]

- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
Updated message on discussion provider LTI configuration page.
> fix: modify message on discussion provider LTI configuration page

- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/messages.js
Split message into separate paragraphs on discussion provider LTI configuration page.
> fix: split message on discussion provider LTI configuration page

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
[TNL-9738](https://openedx.atlassian.net/browse/TNL-9738)
- use case update ->  lti config fields will only be visible for all if the pii sharing is allowed 
- test case update according to the new use case. 
view when pii sharing is disabled.
> Update: lti config fields will only be visible for all if the pii sharing is allowed 

- Makefile
- package-lock.json
- package.json
* Removes custom `browserslist` configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
* Removes `is-es5` check in CI since ES5 was only needed for IE 11 support which is dropped. The supported browsers defined by the shared configuration all [natively support ES6](https://caniuse.com/?search=es6).
This change reduces the resultant asset bundle size.
> build: use shared browserslist config

- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/ReportedContentEmailNotifications.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.test.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
[TNL-9797](https://openedx.atlassian.net/browse/TNL-9797)
- Add reported email notifications toggle in legacy discussions
- It would be false by default
- Toggle value depends on `reported_email_notifications`
- `reported_email_notifications` is integrated with reported email notification toggle
- Update relevant Test case.
> feat: add reported email notifications setting in legacy discussions

- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AnonymousPostingFields.jsx
TNL TIcket : [9469](https://openedx.atlassian.net/browse/TNL-9469)
This PR is a part of the change mentioned in the above ticket, more related PRs in different repos are linked.
Discussion MFE PR: https://github.com/openedx/frontend-app-discussions/pull/118
https://github.com/openedx/edx-platform/pull/30189
updated screen after removing allow anonymous post for all.
checkout in all the three mentioned branches in different repos
- configure discussion provider will no longer show toggle-switch to post anonymously
- add post both using new MFE and legacy experience post anonymously options is removed
- for courses already configured to allow post anonymous feature still won't show the option to post anonymously
> feat: removed the support of allow anonymous to all from discussion configs

- src/pages-and-resources/app-settings-modal/AppSettingsModal.jsx
- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/data/api.js
- src/pages-and-resources/live/data/slice.js
- src/pages-and-resources/live/data/thunks.js
- src/pages-and-resources/live/factories/mockApiResponses.jsx
- PII sharing enable message will not be visible if the PII is not required to configure the provider. The user will directly configure the settings. 
- PII sharing enable message will only be visible if PII is required to configure the provider and the PII flag is disabled. The user will not directly configure the settings. 
- Update the redux structure to support multiple providers.
- Unsave configuration will save as a draft.
https://www.loom.com/share/b3c1a7740e84482fb655f95ae7be4c0d
> feat: update the pii sharing flow for live app

- src/pages-and-resources/discussions/app-config-form/AppConfigFormSaveButton.jsx
- requestSubmit() is not supported in safari. requestSubmit() alternative is form.submit(). submit() does not dispatch submit event and run the validation as compare to requestSubmit(). To resolve this issue, I dispatch the submit event manually.
- [requestSubmit offers a way to validate a form before submit](https://www.stefanjudis.com/today-i-learned/requestsubmit-offers-a-way-to-validate-a-form-before-submitting-it/) 
- [submit() on form element doesn't trigger onSubmit · Issue #6796 · facebook/react](https://github.com/facebook/react/issues/6796) 
- [FIrefox doesn't preventing dispatched submit event](https://stackoverflow.com/questions/49587933/firefox-doesnt-preventing-dispatched-submit-event)
> fix: requestSubmit() is not a function in safari

- package-lock.json
- package.json
Version 1.23.0 of frontent-lib-content-components was causing npm install to fail due to a peer dependency issue with paragon. Version 1.24.0 contains the correct version range for the paragon peer dependency.
> fix: upgrade frontend-lib-content-components version

- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
Implements the following changes:
1. Following toggles will be removed:
* Allow visibility configuration for each course unit
* In-context discussion
2. Following toggles will be renamed:
* "Graded unit pages" will be renamed to "Enable discussions on units in graded subsection"
1. The test setup uses the demo course setup in devstack and the app running in `localhost:2001`
2. Change the Discussion `provider` value to `openedx` in http://localhost:18000/admin/discussions/discussionsconfiguration/ for the demo course
3. Go to http://localhost:2001/course/course-v1:edX+DemoX+Demo_Course/pages-and-resources/discussion/configure/openedx
4. Check the changes are implemented as expected.
> Simplify in-context discussion toggles [BD-38]

- src/pages-and-resources/live/LiveCommonFields.jsx
- src/pages-and-resources/live/Settings.jsx
course live API was returning the password in plain text, now as requirements change it is modified to return `****` instead of a password. `****` is returned with the same length as the original password so the user can have some idea while copy-pasting.
https://2u-internal.atlassian.net/browse/INF-527
In course authoring app go to live settings and observe that password is not visible and API is not returning plain text client secret.
> fix: changed client secret input type to password

- src/pages-and-resources/discussions/data/api.js
We had a course report that the Discussion Provider selection page was failing to load with `Technical Error` banner. It was because the backend API was returning `null` in blackout dates. 
This PR address this issue.
> fix: handle null blackout dates

- src/pages-and-resources/proctoring/Settings.jsx
- src/pages-and-resources/proctoring/Settings.test.jsx
A repeat of #356 but for the newer version of this component.
Why are there two components? Well it looks like we rolled out this new view behind a waffle flag but we never went back and updated the default behavior to use this new version or cleaned up the old component. So at the moment the default behavior w/o the `course_apps.proctoring_settings_modal_view` waffle flag is still to use the ProctoredExamSettings component in #356. edx.org however _does_ have this flag enabled.
old view: https://course-authoring.stage.edx.org/course/course-v1:edX+cheating101+2018T3/proctored-exam-settings
new view: https://course-authoring.stage.edx.org/course/course-v1:edX+cheating101+2018T3/pages-and-resources/proctoring/settings
> feat: configure lti providers on exam settings modal

- src/pages-and-resources/live/BBBSettings.jsx
- src/pages-and-resources/live/messages.js
- Update the helper text for the big blue button free plan to
`The free plan is pre-configured, and no additional configurations are required. By selecting the free plan, you are agreeing to Blindside Networks` [privacy policy](https://bigbluebutton.org/privacy-policy/).
> fix: update helper text for bigBlueButton free plan

- src/pages-and-resources/pages/PageCard.scss
**TL;DR -** fixes a forward arrow in **pages & resources > page card** that wasn't mirrored for RTL.
**Details**
- the mirroring is done within the PageCard.scss file where a `transform: scaleX(-1)` CSS property is used on an RTL selector. It's much cleaner and lighter than editing JS code.
**Screenshots**
The forward arrow button should follow text direction
| LTR for reference | RTL before fix | RTL after fix |
| ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/10594967/194274080-34b0555c-e35d-4f77-a94b-f5dd181cb39d.png) | ![Screenshot from 2022-10-06 10-10-58](https://user-images.githubusercontent.com/10594967/194274171-50138bca-ea3e-4497-b6ed-63f3bd91f0b8.png) | ![Screenshot from 2022-10-06 10-10-23](https://user-images.githubusercontent.com/10594967/194275383- …
> Fix [RTL]: mirror legacy page card arrow

- src/pages-and-resources/live/Settings.jsx
- src/pages-and-resources/live/ZoomSettings.jsx
- src/pages-and-resources/live/ZoomSettings.test.jsx
Zoom Live Settings are now moved behind `pii_sharing`. If `pii_sharing` is enabled, only then the Zoom Settings will be available.
`launchEmail` field is also now an optional field for Zoom Live.
> fix: show Zoom settings when pii sharing is enabled and make launch email optional

- src/pages-and-resources/data/api.js
This chagne make it possible if this module was loaded **then**
the configuration for studio url is changed, then it will pick
the last value.
More context overhangio/tutor-mfe/issues/86
> fix: force studio url to reload if changed

- src/generic/FormSwitchGroup.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/redux.test.js
Cohorts section works differently based on whether or not cohorts are enabled for the course.
**When Enable Cohorts is unchecked in Instructor Dashboard:**
> Divide discussions by cohorts toggle remains disabled AND set to OFF.
> A link to instructor dashboard is visible
**When Eanble Cohorts is checked:**
> Divide discussions by cohorts remains enabled
> State of Divide discussions by cohorts toggle, the nested Divide course-wide discussions topics toggle and checkboxes for topics should RESTORE to previous state.
**Before Fix:**
**After Fix:**
https://user-images.githubusercontent.com/73840786/198981766-e9c28969-6227-41cd-b989-a0328e6e22b9.mp4
> Style: Toggle remains Disabled and Link to instructor dashboard show on Disabled Cohorts

- src/generic/ConfirmationPopup.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/blackout-dates/BlackoutDatesItem.jsx
- src/pages-and-resources/discussions/app-config-form/messages.js
[INF-671](https://2u-internal.atlassian.net/browse/INF-671)
**Confirmation model for the toggle named Enable discussions on units in graded subsections added.**
- When enabling the toggle, the confirmation modal will say: “Enabling this toggle will automatically enable discussion on all units in graded subsections, that are not timed exams.”
- When disabling the toggle, the confirmation modal will say: “Disabling this toggle will automatically disable discussion on all units in graded subsections. Discussion topics containing at least 1 thread will be listed and accessible under “Archived” in Topics tab on the Discussions page.”
- Confirmation modal has 2 buttons: Cancel and Confirm with their respective functions.
**After adding Modal** …
> style: confirmation modal added for in-context discussion toggle

- src/editors/EditorContainer.jsx
Fetching settings directly via `process.env` circumvents the runtime configuration mechanism.  Change the editor page to use `getConfig()` instead.
This is a NOOP for any deployment that does not make use of runtime configuration, so a simple test consists of trying to edit a text block using the new HTML editor.  If it works, this is good.
The actual feature can be similarly tested with Tutor.  Enable the `new_core_editors.use_new_text_editor` waffle flag, and try creating/editing a text block.  If the editor pops up correctly, this is working.
> fix: Editors should support runtime configuration

- src/editors/EditorContainer.jsx
(This is a backport to olive.master of https://github.com/openedx/frontend-app-course-authoring/pull/412.)
Fetching settings directly via `process.env` circumvents the runtime configuration mechanism.  Change the editor page to use `getConfig()` instead.
This is a NOOP for any deployment that does not make use of runtime configuration, so a simple test consists of trying to edit a text block using the new HTML editor.  If it works, this is good.
The actual feature can be similarly tested with Tutor.  Enable the `new_core_editors.use_new_text_editor` waffle flag, and try creating/editing a text block.  If the editor pops up correctly, this is working.
> fix: Editors should support runtime configuration (Olive backport)

- src/pages-and-resources/proctoring/Settings.jsx
- src/pages-and-resources/proctoring/Settings.test.jsx
- src/proctored-exam-settings/ProctoredExamSettings.jsx
Two places because of the old view that should be deprecated in https://2u-internal.atlassian.net/browse/MST-1677
> fix: LTI providers should not be shown unless enabled

- package-lock.json
- package.json
> feat: add problem editor to FLCC

- README.rst
A dependency, node-canvas, is not compatible with macs with M1 processors. I fixed this locally based on https://github.com/Automattic/node-canvas/issues/1733. This Pull Requests documents the fix in the README, so others can follow it.
> docs: add fix for m1 macs to readme

- src/pages-and-resources/discussions/data/api.js
https://2u-internal.atlassian.net/browse/INF-691
the group at the subsection toggle field was not reflecting the actual value returned by the backend this was due to the fact that the key was missing during the normalization process of data and hence it always picked the default value of false. it has now been fixed in this PR and the screenshot is attached reflecting the fix.
> fix: group at subsection field added in redux state

- src/pages-and-resources/discussions/app-list/messages.js
Updated help text for discussion provider "openedx"
Ticket:
[INF-730](https://2u-internal.atlassian.net/browse/INF-730)
After change:
> fix: updated openedx discussion provider help text

- src/CourseAuthoringPage.jsx
Fixed broken "Pages and Resources" page, as a result of changes made in [322](https://github.com/openedx/frontend-app-course-authoring/pull/322). Updated the AppHeader call in course authoring page.
> Fixed broken "Pages and Resources" page

- package-lock.json
- package.json
- public/index.html
- src/head/Head.jsx
- src/head/Head.test.jsx
- src/head/messages.js
- src/index.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/live/BbbSettings.test.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/ZoomSettings.test.jsx
- src/setupTest.js
This PR replace the hardcoded `edx` string in the page head with the `SITE_NAME` value from the configuration.
PR to the olive brunch - https://github.com/openedx/frontend-app-course-authoring/pull/424
> feat: replace hardcoded edx string with site_name from configs

- package-lock.json
- package.json
- public/index.html
- src/head/Head.jsx
- src/head/Head.test.jsx
- src/head/messages.js
- src/index.jsx
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/live/BbbSettings.test.jsx
- src/pages-and-resources/live/Settings.test.jsx
- src/pages-and-resources/live/ZoomSettings.test.jsx
- src/setupTest.js
This PR replace the hardcoded `edx` string in the page head with the `SITE_NAME` value from the configuration.
PR to the master brunch - https://github.com/openedx/frontend-app-course-authoring/pull/425
> feat: replace hardcoded edx string in page head

- src/pages-and-resources/discussions/app-config-form/messages.js
[INF-843](https://2u-internal.atlassian.net/browse/INF-843)
Description
Changed the name of the "openedx" provider from "edx" to "edx (new)"
|Before|
|After|
Merge Checklist
Post-merge Checklist
> fix: changed title of openedx

- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/factories/mockApiResponses.js
[INF-850](https://2u-internal.atlassian.net/browse/INF-850)
**Expected behavior:**
If `discussions.enable_new_structure_discussions` is enabled on stage or prod, only global staff should be able to see 2 edx discussion providers in discussion settings.
Course staff and admins roles should only see the edx provider that they are currently using. 
**Before:**
**After:**
> fix: only global staff can see 2 edx discussion providers in settings

- src/CourseAuthoringRoutes.jsx
- src/CourseAuthoringRoutes.test.jsx
- src/selectors/VideoSelectorContainer.jsx
- src/selectors/VideoSelectorContainer.test.jsx
- src/selectors/__snapshots__/VideoSelectorContainer.test.jsx.snap
**Falcon ticket:** [FAL-3375](https://tasks.opencraft.com/browse/FAL-3375)
**Testing instructions**
See the testing instructions on: https://github.com/openedx/frontend-lib-content-components/pull/278
**Release notes**
> [FAL-3375] Feat: Adding video selection gallery page to the routes

- Makefile
- package-lock.json
- package.json
- src/i18n/index.js
- src/index.jsx
Changes
-------
- Bump frontend-platform to bring `intl-imports.js` script
- Move all i18n imports into `src/i18n/index.js` so `intl-imports.js` can override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
Testing
-------
</details> 
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure …
> feat: use `atlas` in `make pull_translations`

- src/i18n/index.js
- src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/AppList.scss
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
- src/pages-and-resources/discussions/app-list/messages.js
- src/pages-and-resources/discussions/data/api.js
- src/pages-and-resources/discussions/data/hook.js
- src/pages-and-resources/discussions/data/redux.test.js
- src/pages-and-resources/discussions/data/slice.js
[INF-831](https://2u-internal.atlassian.net/browse/INF-831)
We need to provide course teams the ability to hide discussions tab, similar to how they can hide Live and Wiki using course authoring MFE.
Hiding the discussion tab will also disable posting in discussions, indefinitely, if the provider is legacy or openedx. 
The UI for this toggle is presented in this mockup: [Apps and resources landing page](https://www.figma.com/file/SeNpRff5HxzdpCgoD5pmlQ/Apps-and-resources-landing-page?node-id=7486-82287&t=3wNjbliHJfVSi2bU-4) 
If a user decides to enable this toggle, a confirmation dialog will appear. If they confirm, the:
1. Discussion tab will no longer be visible in course navigation
2. Posting in discussions will be disabled if the provider is legacy or openedx. …
> feat: implemented hide discussion functionality

- src/data/services/StudioApiService.js
If a runtime configuration (https://github.com/openedx/frontend-platform/pull/335) is used this config will likely load and be stored in memory before the runtime overrides are merged in since that relies on a network request. This impacts anyone using Tutor locally because the wrong domain (localhost) will be used for studio requests.
> feat: load up-to-date config on studio fetch

- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
[INF-832](https://2u-internal.atlassian.net/browse/INF-832)
Added Following test cases:
1. Successfully shows the disable toggle state of the Hide Discussion Tab by default.
2. Successfully enable the toggle state of the Hide Discussion Tab when the user will click on the OK button.
3. Successfully revert the enable toggle state to disable toggle state when user will click on the cancel button.
**Test**
Tested via "npm run test" command
> test: added test cases for hide discussion tab

- src/files-and-uploads/FileThumbnail.jsx
- src/files-and-uploads/FilesAndUploads.jsx
- src/files-and-uploads/data/utils.js
- src/files-and-uploads/table-components/GalleryCard.jsx
- src/files-and-uploads/table-components/ListCard.jsx
JIRA Ticket: [TNL-10951](https://2u-internal.atlassian.net/browse/TNL-10951)
expected: 
Test
1. Navigate to the assets page
2. In the default view all the images should have the same width and height
3. Switch to the list view
4. All the images should have the same width and height
> fix: width and height of asset preview

- src/custom-pages/EditModal.jsx
JIRA Ticket: [TNL-10981](https://2u-internal.atlassian.net/browse/TNL-10981)
Test:
1. Create a custom page
2. Edit the custom page
3. Add a lot of text to the editor
4. Editor should scroll as content is add an expands past the viewport
5. Save content
6. Reopen edit view of page
7. Should be able to scroll and see all of content
> fix: overflow-y scroll behavior

- src/index.scss
- src/pages-and-resources/PagesAndResources.scss
- src/pages-and-resources/data/selectors.js
- src/pages-and-resources/data/slice.js
- src/pages-and-resources/xpert-unit-summary/XpertUnitSummarySettings.jsx
- src/pages-and-resources/xpert-unit-summary/XpertUnitSummarySettings.test.jsx
- src/pages-and-resources/xpert-unit-summary/data/api.js
- src/pages-and-resources/xpert-unit-summary/data/thunks.js
- src/pages-and-resources/xpert-unit-summary/settings-modal/SettingsModal.jsx
- src/pages-and-resources/xpert-unit-summary/settings-modal/SettingsModal.scss
- src/pages-and-resources/xpert-unit-summary/settings-modal/messages.js
* Update modals to support reset and delete course xpert summary settings when is disabled
* Add radio buttons to specify the default value for the xpert course summary settings
> feat: add xpert summaries configuration by default for units

- src/files-and-uploads/FileInfo.jsx
- src/files-and-uploads/FileThumbnail.jsx
- src/files-and-uploads/data/utils.js
JIRA Ticket: [TNL-10953](https://2u-internal.atlassian.net/browse/TNL-10953)
This PR makes addresses the following ui bugs in the file info modal:
1. Makes the file preview a fixed height and width
2. Adjusts the date added to use the localized version of the time instead of utc
> fix: file info bugs

- src/custom-pages/messages.js
- src/files-and-uploads/ApiStatusToast.jsx
- src/files-and-uploads/FileInput.jsx
- src/files-and-uploads/FileMenu.jsx
- src/files-and-uploads/FilesAndUploads.jsx
- src/files-and-uploads/FilesAndUploads.test.jsx
- src/files-and-uploads/messages.js
- src/files-and-uploads/table-components/GalleryCard.jsx
- src/files-and-uploads/table-components/ListCard.jsx
- src/files-and-uploads/table-components/TableActions.jsx
JIRA Ticket: [TNL-10954](https://2u-internal.atlassian.net/browse/TNL-10954)
When a delete action is called via bulk actions or asset menus, there should be a delete confirmation that appears.
> feat: add delete confirmation modal

- package-lock.json
- package.json
- src/generic/WysiwygEditor.jsx
This should be merged after https://github.com/openedx/frontend-lib-content-components/pull/379. It will need to update FLCC to the newer version, then.
> fix: Pass correct prop to TinyMceWidget and update FLCC

- src/files-and-uploads/FileInfo.jsx
- src/files-and-uploads/FilesAndUploads.jsx
- src/files-and-uploads/table-components/GalleryCard.jsx
- src/files-and-uploads/table-components/ListCard.jsx
JIRA Ticket: [TNL-10959](https://2u-internal.atlassian.net/browse/TNL-10959)
A temporary fix while Paragon resolves the bug in the component.
Testing
1. Navigate to the assets page
2. All cards should have the same length
3. Open the file info
4. There should be no horizontal scrolling
> fix: add word break style for long words

- README.rst
The README of the MFE's need to be updated because the frontend app template has been updated
Issue related: https://github.com/openedx/wg-frontend/issues/169
> [DOCS] Readme updated according OEP-55

- src/help-urls/data/api.js
- src/help-urls/data/selectors.js
- src/help-urls/data/slice.js
- src/help-urls/data/thunks.js
- src/help-urls/hooks.jsx
- src/store.js
Added utilities for fetching documentation urls from backend.
Backend PR: https://github.com/openedx/edx-platform/pull/33073
> feat: add help-urls

- src/advanced-settings/AdvancedSettings.jsx
- src/course-team/CourseTeam.jsx
- src/course-updates/CourseUpdates.jsx
- src/custom-pages/CustomPages.jsx
- src/files-and-uploads/FilesAndUploads.jsx
- src/generic/utils.js
- src/generic/utils.test.js
- src/grading-settings/GradingSettings.jsx
- src/pages-and-resources/PagesAndResources.jsx
- src/proctored-exam-settings/ProctoredExamSettings.jsx
- src/schedule-and-details/index.jsx
JIRA Ticket: [TNL-10949](https://2u-internal.atlassian.net/browse/TNL-10949)
This PR updates the tab title for a page to match the page title and include the course name. The new tab title pattern matches the legacy tab title pattern.
> feat: change head title depending on page

- src/pages-and-resources/discussions/app-list/AppList.jsx
- src/pages-and-resources/discussions/app-list/AppList.test.jsx
- src/pages-and-resources/discussions/app-list/messages.js
[INF-1074](https://2u-internal.atlassian.net/browse/INF-1074)
Updated the toggle state of Hide discussion tab on API response.
> fix: update toggle state based on api response

- src/course-updates/CourseUpdates.jsx
- src/course-updates/CourseUpdates.test.jsx
- src/course-updates/course-handouts/CourseHandouts.jsx
- src/course-updates/course-handouts/CourseHandouts.test.jsx
- src/course-updates/course-update/CourseUpdate.jsx
- src/course-updates/course-update/CourseUpdate.test.jsx
- src/course-updates/delete-modal/DeleteModal.jsx
- src/course-updates/delete-modal/DeleteModal.test.jsx
- src/course-updates/delete-modal/messages.js
- src/course-updates/messages.js
- src/course-updates/update-form/UpdateForm.jsx
- src/course-updates/update-form/UpdateForm.scss
JIRA Ticket: [TNL-11025](https://2u-internal.atlassian.net/browse/TNL-11025)
Test the following items
> fix: course updates UI bugs

- src/advanced-settings/scss/AdvancedSettings.scss
- src/advanced-settings/scss/_variables.scss
- src/advanced-settings/setting-card/SettingCard.jsx
JIRA Ticket: [TNL-10991](https://2u-internal.atlassian.net/browse/TNL-10991), [TNL-11013](https://2u-internal.atlassian.net/browse/TNL-11013)
This PR left aligns the advanced settings card title and width of text area to be consistent for all cards
> fix: advanced settings card alignment

- src/export-page/CourseExportPage.test.jsx
- src/export-page/data/thunks.js
- src/export-page/export-stepper/ExportStepper.jsx
This PR fixes the export link differences between relative export paths and absolute export paths. Currently all export path received from the api are treated as relative paths so the port for the page is prepended to the relative path. However, not all the export paths from the api are guaranteed to be relative paths. In the case that export path is an absolute path, the file will fail to download because the absolute path was prepended with unnecessary port.  This PR a checks if the export path is relative or absolute and prepends the port accordingly.
Testing
1. Navigate to the export mfe page
2. Export a course
3. Click the download button
4. File downloads as expected
> fix: export download link prefix

- src/assets/scss/_form.scss
- src/course-rerun/course-rerun-sidebar/CourseRerunSidebar.test.jsx
- src/course-rerun/course-rerun-sidebar/index.jsx
- src/course-rerun/course-rerun-sidebar/messages.js
- src/course-rerun/index.jsx
- src/course-rerun/messages.js
- src/export-page/export-modal-error/ExportModalError.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/create-or-rerun-course/constants.js
- src/generic/create-or-rerun-course/factories/mockApiResponses.jsx
- src/generic/create-or-rerun-course/hooks.jsx
- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
- src/studio-home/__mocks__/studioHomeMock.js
- src/studio-home/card-item/index.jsx
- src/studio-home/collapsible-state-with-action/index.jsx
- src/studio-home/messages.js
- src/studio-home/organization-section/index.jsx
- src/studio-home/processing-courses/course-item/index.jsx
- src/studio-home/processing-courses/index.jsx
- src/studio-home/scss/StudioHome.scss
- src/studio-home/tabs-section/courses-tab/index.jsx
- src/studio-home/tabs-section/index.jsx
JIRA Ticket: [TNL-11054](https://2u-internal.atlassian.net/browse/TNL-11054)
> 1. Update re-run side bar section 1 description to use local time instead of UTC
> 2. Make the error message in new course and course rerun forms font larger.
> 3. Update colors used for error/denied, pending, and in-progress/unrequested card alerts
>   i. error/denied - `bg-danger-100` and `text-gray-700`
>   ii. pending - `bg-warning-100` and `text-gray-700`
>   iii. in-progress - `bg-light-100` and `text-gray-700`
> 4. Add New library button that links to legacy library tab. When LA MFE is enabled it will direct to the create page  
> 5. Fix spacing and font size when using org search
> 6. Update create course redirect to point at legacy outline page
Create Library
1. Navigate to the [home …
> fix: studio home UI bugs

- src/pages-and-resources/progress/Settings.jsx
Without this change, an error msg is displayed till the request runs, i.e. it is not waiting for the request to complete.
This issue was discovered while testing/reviewing https://github.com/openedx/frontend-app-learning/pull/1194
> fix: await async saveSetting func to remove unwanted err msg

- src/files-and-uploads/FilesAndUploads.jsx
- src/files-and-uploads/FilesAndUploads.test.jsx
- src/files-and-uploads/table-components/table-custom-columns/AccessColumn.jsx
- src/files-and-uploads/table-components/table-custom-columns/ActiveColumn.jsx
- src/files-and-uploads/table-components/table-custom-columns/MoreInfoColumn.jsx
- src/files-and-uploads/table-components/table-custom-columns/StatusColumn.jsx
- src/files-and-uploads/table-components/table-custom-columns/ThumbnailColumn.jsx
- src/files-and-uploads/table-components/table-custom-columns/index.js
This PR updates the "list" view of assets to use a table layout. The current version lays the assets out in a list but uses cards to show the asset. With this change, a user can select all the assets in view for a bulk action and more easily sort the table's columns.
Testing
1. Switch to list view and see that the table renders
2. Click the more icon
3. Check that each of the items in menu function as expected.
> feat: update list view to be table

- renovate.json
Renovate changes explanation:
- made normal deps updates only weekly - otherwise hard to deal with
- edx or openedx deps updates daily
- as discussed, FLCC update should happen more or less 24/7
- disable automerge for now because first I need to get access to repo setting and require all pipeline checks to pass
> chore: adjust renovate config

- public/index.html
The favicon is not currently displaying in Safari. After our investigation, we have found a way to fix it. We used the same approach as what was done in the account mfe. We changed the favicon inclusion in the index.html file, and now the favicon is being displayed in Safari.
> fix: Missed favicon in Safari (backport from master)

- src/files-and-uploads/FilesAndUploads.jsx
- src/files-and-uploads/table-components/FilterStatus.jsx
Changed the filter status text on the files and uploads table to display also the number of files, even when a filter is applied.
https://2u-internal.atlassian.net/browse/TNL-11086 (internal ticket)
I just copied most of paragon's `FilterStatus` component, made some adjustments, and then overrode the default component.
> feat: change filter status text

- src/schedule-and-details/hooks.jsx
- src/schedule-and-details/index.jsx
- src/schedule-and-details/utils.js
- src/schedule-and-details/utils.test.js
JIRA Ticket: [TNL-11164](https://2u-internal.atlassian.net/browse/TNL-11164)
>The Schedule and details page shows a permanent "You've made some changes, but there are some errors". Not sure what the issue is, but the old experience does not have the same issue.
The validator for the Schedule and details page checks if the course end date is after the certificate available date. There is a default certificate available date, but is not shown to users unless the certificate row is displayed. The error message is only shown in the certificate row, so the user is notified of the error in the parent alert but not the details of the error. Now the validator only checks for the compatibility of the end date and certificate available date when the certificate row is displayed.
Testing
1. Navigate …
> fix: end date error when certificate row not shown

- src/files-and-videos/videos-page/data/api.js
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
This PR fixes the typo in the `transcript_preferences` api. Previous the json passed to the api was 
```
const postJson = {
cielo24_fideltiy: cielo24Fidelity?.toUpperCase(),
cielo24_turnaround: cielo24Turnaround,
global,
preferred_languages: preferredLanguages,
provider,
video_source_language: videoSourceLanguage,
three_play_turnaround: threePlayTurnaround,
};
```
As a result the api threw an error because it was expecting `cielo24_fidelity` instead of `cielo24_fideltiy`.
> fix: fidelity typo in preference api

- src/custom-pages/CustomPages.jsx
This PR fixes the Custom Page modal not closing on cancel and on close not removing `/editor` from the url.
Testing
1. Navigate to the custom pages.
2. Click the pencil icon to edit a page.
3. Click cancel.
4. Modal should close.
5. Footer and header should display as expected.
6. Edit the same page.
7. Make some edits.
8. Click Save.
9. Modal should close.
10. Footer and header should display as expected.
> fix: modal exit redirect

- src/pages-and-resources/proctoring/Settings.jsx
- src/pages-and-resources/proctoring/Settings.test.jsx
This toggle does nothing if an LTI tool is selected. We should hide it in that case.
> fix: opt out is not supported by lti proctoring

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/data/slice.js
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/data/slice.js
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
JIRA Ticket: [TNL-10958](https://2u-internal.atlassian.net/browse/TNL-10958)
> I had 29 files, uploaded 5, and then had 32 files. But it showed this:
> ![image](https://github.com/openedx/frontend-app-course-authoring/assets/42981026/fea8c29b-b0a9-4fad-8827-1e0d6046852b)
Testing
1. Navigate to the Videos Page
2. Add multiple videos
3. Check that row status count equals the expected amount
4. Delete at least two videos
5. Check that row status count equals the expected amount
*repeat for the Files page
> fix: total file count update on add and delete

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/messages.js
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/messages.js
- src/files-and-videos/generic/table-components/FilterStatus.jsx
- src/files-and-videos/generic/table-components/RowStatus.jsx
- src/files-and-videos/generic/table-components/TableActions.jsx
- src/files-and-videos/generic/table-components/index.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/SortAndFilterModal.jsx
- src/files-and-videos/generic/table-components/sort-and-filter-modal/index.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/messages.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.test.js
- src/files-and-videos/generic/table-components/table-custom-columns/StatusColumn.jsx
- src/files-and-videos/generic/table-components/utils.js
- src/files-and-videos/index.scss
- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/data/utils.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
- src/files-and-videos/videos-page/messages.js
JIRA Tickets: [TNL-11055](https://2u-internal.atlassian.net/browse/TNL-11055), [TNL-11069](https://2u-internal.atlassian.net/browse/TNL-11069), [TNL-11032](https://2u-internal.atlassian.net/browse/TNL-11032), [TNL-11168](https://2u-internal.atlassian.net/browse/TNL-11168)
This PR fixes the following:
- Missing filter options
- Filter and sort options not displaying in the same modal
- Filters not displaying to users after they are selected
- File count not updating with filters
Testing
Files page
1. Navigate to the Files page.
2. Click the Sort and filter button
3. Filter options should include: Images, Documents, Code, Audio, Other, Active, Inactive, Public, Locked
4. Select a filter and apply
5. A chip with filter name is shown
6. Click the "x" on the filter chip
7. Chip should be …
> fix: combine filter and sort into one modal

- src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
JIRA Ticket: [TNL-11199](https://2u-internal.atlassian.net/browse/TNL-11199)
> Transcript Settings panel does not automatically select the option with saved values when they exist
> Shows
> ![image](https://github.com/openedx/frontend-app-course-authoring/assets/42981026/89558afe-4693-411f-8303-50918aee8c85)
This PR corrects the loading of the active transcript preferences. Previously the selected transcript option was given the full object of preferences instead of the provider so none of the options were selected on load. Now the correct option is selected when the settings are loaded.
Testing (locally)
*Will need to be fully tested in stage environment where the video pipeline is fully enabled
1. Replace (Lines 30 -34, `TranscriptSettings.jsx`)
```
const {
activeTranscriptPreferences, …
```
> fix: active transcript preference not loading

- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.test.js
- src/files-and-videos/generic/table-components/utils.js
- src/files-and-videos/generic/table-components/utils.test.js
JIRA Ticket: [TNL-11207](https://2u-internal.atlassian.net/browse/TNL-11207)
> I get an error if typing anything into search box. Typing one letter leads to error page.
> ![image](https://github.com/openedx/frontend-app-course-authoring/assets/42981026/2e22cdd3-535b-4fbe-8d0e-b62bd8c4c9f6)
When making the updates to the filter function for display chips and modal, the search bar's filter capabilities were not accounted for. The search bar filters are not associated with a specific column, so when using it and error was thrown because the matching column could not be found. The filter functions now account for when there is not an associated column for the search filter.
Testing
1. Navigate to the Files page.
2. Type something in the search bar
3. A chip with a matching string should …
> fix: table search filter

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/generic/ApiStatusToast.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/messages.js
- src/files-and-videos/generic/table-components/TableActions.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
JIRA Ticket: [TNL-11212](https://2u-internal.atlassian.net/browse/TNL-11212)
> 1. Button should say “add videos” rather than “add files”
> 2. Should say “Delete Videos Confirmation” rather than “Delete Files Confirmation” and also replace “file(s)” with “video(s).
Testing
Videos page
1. Navigate to the Videos page
2. Add button should say "Add videos"
3. Delete a video
4. Confirmation box title should be "Delete video(s) confirmation"
5. Confirm deletion
6. Toast at the bottom should be "Deleting 1 video(s)"
Files page
1. Navigate to the Files page
2. Add button should say "Add files"
3. Delete a file
4. Confirmation box title should be "Delete file(s) confirmation"
5. Confirm deletion
6. Toast at the bottom should be "Deleting 1 file(s)"
> fix: page specific messages

- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/table-components/Footer.jsx
- src/files-and-videos/generic/table-components/index.js
- src/files-and-videos/index.scss
- src/files-and-videos/videos-page/info-sidebar/TranscriptTab.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/Transcript.jsx
JIRA Ticket: [TNL-11033](https://2u-internal.atlassian.net/browse/TNL-11033)
The default pagination style for the `DataTable` footer is the minimal and reduced variants of the `Pagination` component. Now the Files and Videos pages use the default variant for pagination.
Before
After
> fix: pagination style

- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/generic/table-components/sort-and-filter-modal/SortAndFilterModal.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/messages.js
JIRA Ticket: [TNL-11219](https://2u-internal.atlassian.net/browse/TNL-11219)
> The filters stop working whenever I use one of the Sort options in the Sort and filter button. It seems to be an order of operations issue. If I click on that and just change the filters, it works. However, if I change filters and select a sort option, it removes my filters and I can no longer use filters. 
> 
> Additionally, why do we have a filter for Processing but not Failed? Both seem to be possible states.
The calls for updating the sort and filters were not firing in a set order because the sort function is an async function. This PR fixes the order of the calls by adding an `await` on the sort function.
Testing
1. Navigate to the Videos page
2. Select a filter and apply
3. Videos should filter and show …
> fix: filter overwritten by sort

- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/data/api.js
- src/generic/data/api.test.js
- src/studio-home/organization-section/OrganizationSection.test.jsx
All configuration calls must handled asynchronously, otherwise they risk failure in runtime configuration scenarios.
The failure is readily reproducible in `tutor local` nightly or quince deployments.  Simply navigate to a course's "Pages and Resources" page in Studio.  The MFE will fail with a `Uncaught TypeError: URL constructor: course/ is not a valid URL.` at [src/generic/data/api.js on line 7](https://github.com/openedx/frontend-app-course-authoring/blob/master/src/generic/data/api.js#L7).
The fix is to make any and all such config assignments into function calls, so that they're resolved just-in-time, as opposed to at initial load time.
> fix: Fix data API URL handling

- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
JIRA Ticket: [TNL-11234](https://2u-internal.atlassian.net/browse/TNL-11234)
The new library button is not shown on the home screen. This prevents users from creating a new library unless them remember the specific url for the legacy library page.
Testing
1. Navigate to the course-authoring home page
2. Should show "New library" button next to "New course" button
3. Click "New library"
4. Should take you back to the legacy library page
> feat: add new library button

- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/api.js
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/files-page/data/utils.js
- src/files-and-videos/generic/EditFileErrors.jsx
- src/files-and-videos/videos-page/data/utils.js
JIRA Ticket: [TNL-11215](https://2u-internal.atlassian.net/browse/TNL-11215)
> “Active” checkmark does not show up in table view until after the Info modal has been loaded
This PR uses the update API endpoints for the video and file fetch that includes the usage locations for each of the files/videos. Previous, the check mark in the active column on the table view would only appear after a user loaded the corresponding info modal. The table is supposed to provide a quick view to the user for whether or not a video/file is in use. Now the column loads as expected and the rows/cards can properly be filtered on the active value.
This change is dependent on the `edx-platform` PR #[33746](https://github.com/openedx/edx-platform/pull/33746)
Testing
Follow the instructions in the [edx-platform …
> feat: original fetch to includes usage metrics

- src/generic/Loading.jsx
- src/generic/utils.js
- src/taxonomy/TaxonomyListPage.jsx
- src/taxonomy/data/api.js
- src/taxonomy/tag-list/TagListTable.jsx
- src/taxonomy/tag-list/TagListTable.test.jsx
- src/taxonomy/tag-list/data/api.js
- src/taxonomy/tag-list/messages.js
- src/taxonomy/taxonomy-detail/TaxonomyDetailPage.jsx
Ticket: https://github.com/openedx/modular-learning/issues/138
This PR has some minor improvements to the "Taxonomy Detail Page".
* Load child/grandchild tags consistently. (Depends on https://github.com/openedx/openedx-learning/pull/119 but it can be merged even before that one is merged.)
* Allow expanding/collapsing child tags (if any; otherwise don't show).
* Display the # of child tags as a separate column.
* Set the title of the page (just said "Course Authoring")
This is **not** the final UI design and all of this can/will be changed - this just makes sure that users can see _all_ the tags in the taxonomy during our initial round of testing.
Note that you need to have https://github.com/openedx/openedx-learning/pull/119 checked out locally or you may see duplicate results in the …
> feat: display all child tags in the "bare bones" taxonomy detail page [FAL-3529] [FC-0036]

- src/files-and-videos/videos-page/info-sidebar/transcript-item/LanguageSelect.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/Transcript.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/TranscriptMenu.jsx
This PR fixes the visibility of the language dropdown and menu dropdown for transcripts when the height of the transcript tab is less than the height of the dropdown container.
Testing
1. Navigate to the Videos page
2. Open the info modal for a video with five or less transcripts
3. Click on one of the languages
4. The whole dropdown should be visible
5. Click on the menu (...)
6. The whole dropdown should be visible
> fix: visibility of transcript dropdowns

- src/header/utils.js
This PR removes an extra `course-v1` in the Group Configurations href:
https://github.com/openedx/frontend-app-course-authoring/assets/64440265/3169c70c-9336-44bd-8bfc-b9a6ca4027e8
> fix: remove unnecessary course-v1 from courseId string

- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/generic/UsageMetricsMessage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
This PR updates the list items in the usage section of the info modal to be hyperlinks. The links lead to the xblock where the asset/video are located.
JIRA Ticket: [TNL-11158](https://2u-internal.atlassian.net/browse/TNL-11158)
> This list is found on bottom left hand side of info modal. Users can currently see if a given asset is in the course, and how many times it is in the course. What is considered a “game changer” is to make that list clickable so that they can know where in the course the asset is. 
1. Open a course and navigate to the Files page (MFE version)
2. Open the info modal for an asset that you know is used in the course
3. Info modal should show all the locations that the asset is used and on hover show a valid link
4. Click on one of the links
5. Unit page should open …
> feat: update usage metrics to be a hyperlink

- src/grading-settings/assignment-section/AssignmentSection.test.jsx
- src/grading-settings/assignment-section/index.jsx
JIRA Ticket: [TNL-11243](https://2u-internal.atlassian.net/browse/TNL-11243)
> Wrong alert showing for assignment usage
This PR fixes the wrong assignment count when the number of assignments that use the assignment type equals the assignment type's total number. This PR also fixes the number fields for an assignment being saved as a string. This prevented some of the equality checks from returning the correct answer because strings were being compared to numbers.
Testing
1. Open a course where no subsections have their assignment types set
2. In the course outline, navigate to a subsection
3. Click on the gear icon
4. In the "Grade As" section, select an assignment type
5. Navigate to the grading page
6. Find the assignment type that was select for the subsection
7. The assignment type …
> fix: wrong min count alert showing

- src/grading-settings/grading-scale/components/GradingScaleSegment.jsx
JIRA Ticket: [TNL-11260](https://2u-internal.atlassian.net/browse/TNL-11260)
> See image. Notice 14 is in both F and D ranges, etc.
This PR fixes the numeric ranges displayed for a section. Previously the end range for a segment was equal to the start range of the next segment. This can be confusing for the user to know where the grade would actual fall on the scale. With this change, the end range of a segment will be one less than the start range of the next segment.
Before
After
Testing
1. Navigate to the grading page
2. Check that the grading scale segments end range do not equal the next segments start range
> fix: grading segment number ranges

- src/import-page/data/api.js
- src/import-page/data/api.test.jsx
- src/import-page/import-sidebar/ImportSidebar.jsx
JIRA Ticket: [TNL-11163](https://2u-internal.atlassian.net/browse/TNL-11163)
>I was able to import a 60MB course. When I tried to do a 250MB course it broke. I tried a bit smaller and it seemed to break around 100MB. It looked like the percent was going up. The percent got to 99%, then the percentage disappeared and the gear would just spin, see screenshots. The legacy page they can import a 500 MB course but with the new page cannot import 100 MB.
** This PR is dependent on `edx-platform` PR #[33898](https://github.com/openedx/edx-platform/pull/33898) **
Testing
1. Navigate to the Import page
2. If you wan to keep the content of your current course, export it before importing a new one
3. Upload a course zip that is greater than 100 MB
4. File should import
5. Wait for the import to …
> fix: import api to chunk file

- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/messages.js
- src/files-and-videos/generic/table-components/table-custom-columns/MoreInfoColumn.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/data/api.js
- src/files-and-videos/videos-page/data/api.test.js
- src/files-and-videos/videos-page/data/thunks.js
JIRA Tickets: [TNL-11228](https://2u-internal.atlassian.net/browse/TNL-11228), [TNL-11265](https://2u-internal.atlassian.net/browse/TNL-11265)
This PR fixes individual videos not downloading in the list view and multiple video downloads. Previously individual videos would not download in the list video because the `downloadLink` was not passed to the download function. Additionally when trying to download multiple videos, only the first video would download because the file saver would open the videos in a new tab. This forced the users browser to enforce its pop-up blocker. Now the backend downloads the files and puts them in a zipped folder which is downloaded via the frontend.
**This PR is dependent on `edx-platform` PR #[33882](https://github.com/openedx/edx-platform/pull/33882)** …
> fix: video downloads

- src/data/services/ExamsApiService.js
- src/pages-and-resources/proctoring/Settings.jsx
- src/pages-and-resources/proctoring/Settings.test.jsx
- src/pages-and-resources/proctoring/messages.js
[COSMO-39](https://2u-internal.atlassian.net/browse/COSMO-39)
This pull request adds a required escalation email field when the selected provider is an LTI provider. This mimics the behavior when Proctortrack is the selected provider. This commit also renames references to Proctortrack to be more generic.
**Dependencies:**
The changes in https://github.com/edx/edx-exams/pull/221 must be merged to `main` or checked out if not yet merged.
**Happy Path**
https://github.com/openedx/frontend-app-course-authoring/assets/11871801/8cf48764-62ec-4ef9-b461-3bcc77a2f5a0
**Escalation Email Validation**
https://github.com/openedx/frontend-app-course-authoring/assets/11871801/b203c664-3323-40f3-8f04-786c77479d84
**Disabling Proctored Exams**
https://github.com/openedx/frontend-app-course-authoring/asset …
> [COSMO-39] Add escalation email field for LTI-based proctoring providers.

- src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
This fixes an issue where when the `transcriptType` is set to a 3rd party translations service such Cielo or 3playMedia, on clicking the Transcript Settings button/link, the view bypasses the initial view of the settings panel and displays the order component view thereby preventing the option to select/view the ai-translations component.
> fix: update transcript settings default logic

- src/data/constants.js
- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/api.js
- src/files-and-videos/files-page/data/slice.js
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/files-page/factories/mockApiResponses.jsx
- src/files-and-videos/generic/EditFileErrors.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/data/slice.js
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
JIRA Ticket: [TNL-11255](https://2u-internal.atlassian.net/browse/TNL-11255)
> The Files page for large courses takes over 30 seconds to load.  Notice the page size is 13165, and the call eventually fails…
This PR adds missing failure messages to users when the initial fetch of the files and videos fails. Additionally this PR breaks up the initial fetch of the files page into 50 file increments (akin to fetching one page at a time). This segmenting will allow the first page to load quickly and prevent API timeout errors.
Testing
1. Navigate to the Import page
2. Import a course that has over 1000 assets
3. Once the import has completed, navigate to the Files page
4. Page should fetch the first 50 assets (look at the table header for this information)
5. Should continue to fetch assets …
> fix: files page timeout

- package-lock.json
- package.json
- src/course-team/CourseTeam.jsx
- src/course-team/CourseTeam.test.jsx
- src/course-team/course-team-member/CourseTeamMember.jsx
- src/course-team/hooks.jsx
- src/generic/data/api.js
- src/generic/data/api.test.js
- src/generic/data/selectors.js
- src/generic/data/slice.js
- src/generic/data/thunks.js
This PR is to fetch the new (LoggedIn) User Permissions from the endpoint `/api/course_roles/v1/user_permissions/`.
- Add new function on generic data `api, slice, selector and thunk`
- Add a new hook for handling the permissions in the `CourseTeam` component.
- Add `UserPermissionsEnabledFlag` 
- Add specs
To test this code please use this branch for course-authoring and ROLES-2-course_roles_setup for edx-platform
1. Go to LMS admin and enable/create these waffle flags:
- `contentstore.new_studio_mfe.use_new_course_team_page`
- `course_roles.use_permission_checks`
2. Go to a Demo Course as a user with proper access to view CourseTeams in the CMS
3. **As LoggedIn Admin** (Same behavior as current):
- You should see the *+ New team member* and *+ Add a new team member* buttons (Since we're …
> [ROLES-26] Helper function for ingesting permission data

- src/generic/data/api.js
- src/generic/data/apiHooks.js
- src/taxonomy/TaxonomyListPage.jsx
- src/taxonomy/TaxonomyListPage.scss
- src/taxonomy/TaxonomyListPage.test.jsx
- src/taxonomy/data/api.js
- src/taxonomy/data/api.test.js
- src/taxonomy/data/apiHooks.jsx
- src/taxonomy/index.scss
- src/taxonomy/messages.js
This allows for filter taxonomies on the taxonomy list page by selecting organization name, all taxonomies, or unassigned taxonomies.
- Closes https://github.com/openedx/modular-learning/issues/108
1. Make sure you have the latest changes from edx-platform master in your local devstack
2. Make sure you have sample data from https://github.com/open-craft/taxonomy-sample-data/
3. Run the MFE and head to http://localhost:2001/taxonomies
4. Confirm that the select menu appears and defaults to 'All taxonomies', and all taxonomies are listed
5. Confirm that changing the selected filter fetches different taxonomies for each filter selected
____
Private-ref:
- [FAL-3544](https://tasks.opencraft.com/browse/FAL-3544)
> [FC-0036] feat: Add filter taxonomies by orgs

- src/import-page/data/api.js
- src/import-page/data/api.test.jsx
- src/import-page/data/thunks.js
- src/import-page/file-section/FileSection.jsx
- src/import-page/import-stepper/ImportStepper.jsx
JIRA Ticket: [TNL-11308](https://2u-internal.atlassian.net/browse/TNL-11308)
When chunking the uploaded file was introduced, the upload progress percentage began to loop for each chunks upload. The looping of percentages is confusing to users as it seems like the upload is stuck in an infinite loop and they do not know how much the file has successfully uploaded. This PR fixes the progress bar so it updates after each chunk is uploaded.
Test
1. Export the current content of your course
2. Open the network tab in DevTools
3. Import the recently exported file
4. Progress percentage in Uploading step should only reach 100% one time even when the file is chunked multiple times (confirm number of chunks in network tab)
> fix: uploading progress percentage

- src/CourseAuthoringPage.jsx
- src/CourseAuthoringPage.test.jsx
- src/data/constants.js
- src/data/thunks.js
- src/generic/NotFoundAlert.jsx
Shows a "Not found" page when an invalid course key is in the URL.
1. Open a course outline page
2. Change the course key in the URL to a non-existent course
3. See the not found page
4. Open an editor page
5. Change the course key (in the first component of the URL after /course/) to a non-existent course
6. See the not found page
None
Private-ref: https://tasks.opencraft.com/browse/BB-8262
> feat: error page on invalid course key

- src/content-tags-drawer/data/api.js
- src/content-tags-drawer/data/api.test.js
Add support for fetching content data for Library V2 components in content tags drawer.
- Needed for https://github.com/openedx/frontend-app-library-authoring/pull/400
- Follow the testing/setup instructions in https://github.com/openedx/frontend-app-course-authoring/pull/737 and make sure the content tags drawer still functions as expected for course components
- Perform the testing instructions mentioned in https://github.com/openedx/frontend-app-library-authoring/pull/400 to confirm the changes is working correctly
---
Private-ref: [FAL-3599](https://tasks.opencraft.com/browse/FAL-3599)
> feat: Add v2 lib components content tags support

- webpack.dev.config.js
- webpack.prod.config.js
fix: configure webpack to fix paid powerpaste plugin
> fix: configure webpack to fix paid powerpaste plugin

- src/index.jsx
The PR https://github.com/openedx/frontend-app-course-authoring/pull/723 changed how `react-router` is initialized, but introduced a bug where the router `basename` was not set properly. This would not cause issues on edx.org prod nor devstack, but it breaks tutor-based environments where all the MFEs are served from the same host.
Before this fix: http://apps.local.overhang.io:2001/course-authoring/home gives a 404
After this fix: http://apps.local.overhang.io:2001/course-authoring/home shows the Studio home
Same for other URLs.
Screenshot of the error:
Note: the fix just follows [how `frontend-platform` sets the `basename`](https://github.com/search?q=repo%3Aopenedx%2Ffrontend-platform%20PUBLIC_PATH&type=code).
Private-ref: FAL-3537
> fix: react-router basepath was not set, breaking this MFE on tutor instances

- src/files-and-videos/videos-page/data/api.js
JIRA Ticket: [TNL-11350](https://2u-internal.atlassian.net/browse/TNL-11350)
> Users can successfully upload videos, but they never leave the processing stage. Looking at the network tab it looks like the upload to AWS fails, but the user is never notified of the failure.
This PR fixes the `PUT` to AWS to more closely align with the legacy API that uses AJAX and JQuery. This PR allow properly handles the failure state of the `PUT` request when the API return a failure message.
Note: This PR requires a successfully set up video pipeline to properly test
Testing
1. Navigate to the videos page
2. Open network tab
3. Upload a video
4. Video should appear with processing badge on thumbnail
5. Check the network tab to see that that video successfully sent to AWS
6. Reload page and a bit of time …
> fix: video upload api body

- src/export-page/data/thunks.js
- src/export-page/data/thunks.test.js
Internal issue: https://2u-internal.atlassian.net/browse/TNL-11334
The timestamp of the new export page was always showing the current time, not the export time.
- go to export page for a very small course (so export won't take long for you to test)
- create an export. Check timestamp
- wait 1 minute, refresh page
- export should not show current time but previous timestamp
- create new export
- now timestamp should show new time
> fix: export page timestamp

- src/CourseAuthoringPage.jsx
At the moment, editors served from V1 libraries are broken because they use the course authoring MFE url (because they use editors in the same way courses do).
This was introduced here: https://github.com/openedx/frontend-app-course-authoring/pull/761
This fix fixes that.
> fix: dont allow course detail page to break editor

- src/files-and-videos/videos-page/data/utils.js
- src/files-and-videos/videos-page/data/utils.test.js
The previous parser for video file types converted `{'video/*': [.mov]}` to `video/mov`. However `video/mov` is not a valid mime type. `.mov` files actually have the mime type `video/quicktime`. This PR fixes this mime type error.
Testing
1. Navigate to a course that has videos
2. Navigate to the Videos page (ensure that the .env variable `ENABLE_VIDEO_UPLOAD_PAGE_LINK_IN_CONTENT_DROPDOWN` is true)
3. Click "Add Videos"
4. Confirm that both `.mp4` and `.mov` are allowed.
> fix: mov files not being allowed on video upload

- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
- src/files-and-videos/videos-page/transcript-settings/messages.js
JIRA Ticket: [TNL-11261](https://2u-internal.atlassian.net/browse/TNL-11261)
> On the new CA MFE videos page, the Transcript Settings pane has a “Discard Settings” button that should be labeled “Discard Changes”
> 
> Below this should be a small text line saying when the last updated timestamp was.  This is to be in parity with the legacy UI feature.
Testing
1. Navigate to the Videos page (ensure that the .env variable `ENABLE_VIDEO_UPLOAD_PAGE_LINK_IN_CONTENT_DROPDOWN` is true)
2. Click "Transcript settings"
3. Click "Order Transcripts"
4. Click "None"
5. Discard button should read "Discard changes"
6. Click "Update settings"
7. "Last updated {current date / Month Date, Year} " should appear below buttons
> feat: add missing transcript setting update date

- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/data/utils.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
JIRA Tickets [TNL-11354](https://2u-internal.atlassian.net/browse/TNL-11354)
> On Video Page and in Info Modal, hovering over the thumbnail prompts me to “Edit Thumbnail”. However, technically I can’t edit it, only replace it so it is more accurate to say “Replace Thumbnail”.
[TNL-11355](https://2u-internal.atlassian.net/browse/TNL-11355)
> Every tile has a little label that says “Video”. This seems wholly unnecessary on a page that can only have videos. The mocks present the file suffix (MOV, MP4). I’m not sure how valuable that information is either but either way it feels odd.
Testing
1. Open the Videos page
2. After the page loads, make sure you are in the gallery view
3. For each video, check that each card has the correct video type chip (MOV, MP4, Unknown)
* the chip is determined …
> fix: gallery card text and load

- package-lock.json
- package.json
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
This PR replaces `@edx/frontend-component-ai-translations-edx` package with `@edx/frontend-component-ai-translations`. `@edx/frontend-component-ai-translations` is the public version and should be the default for CA MFE. `@edx/frontend-component-ai-translations-edx` will replace `@edx/frontend-component-ai-translations` at build time via `edx-internal`.
> feat: replace ai translations edx component with the openedx version

- src/data/constants.js
- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/thunks.js
- src/files-and-videos/generic/EditFileErrors.jsx
- src/files-and-videos/generic/FileMenu.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/table-components/GalleryCard.jsx
- src/files-and-videos/generic/table-components/table-custom-columns/ActiveColumn.jsx
- src/files-and-videos/generic/table-components/table-custom-columns/MoreInfoColumn.jsx
- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/data/api.js
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/data/utils.js
JIRA Tickets: [TNL-11393](https://2u-internal.atlassian.net/browse/TNL-11393), [CR-6428](https://2u-internal.atlassian.net/browse/CR-6428?atlOrigin=eyJpIjoiMGFhYjI2Y2NhYWUxNGU1MDlhMDIyMDBhYTM3ZjlmODgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
This PR fixes the wrong menu bug introduced in #795. This PR updates the status messages to align with the legacy messages and always show the status in the Status column no matter what it is. Finally this PR fixes the order of loading for the Videos page. Previously, the page would show loading cards while the videos and their usage locations were being fetched. This resulted in users thinking that the page was taking forever to load even though the api responded fairly quickly.  Now the page will remove the loading skeleton after all the videos have been …
> fix: update video page load order

- README.rst
- src/taxonomy/TaxonomyListPage.jsx
The README states the wrong waffle flag. Although this is inconsistent with the others, this is the actual waffle flag that edx-platform currently checks.
Ref: 
https://github.com/openedx/edx-platform/blob/4b7ef2697e84bae269983dfce63f1af60bb247df/cms/djangoapps/contentstore/toggles.py#L550
> docs: fix incorrect waffle flag stated.

- src/content-tags-drawer/data/api.js
- src/content-tags-drawer/data/api.test.js
https://github.com/openedx/frontend-app-course-authoring/pull/787 introduced a bug in the URL used to update content tags, resulting in 404 errors from the backend.
This PR fixes that bug and the related tests.
Setup:
1. Create test taxonomies, tags, orgs, and courses with https://github.com/open-craft/taxonomy-sample-data/
1. Run this PR's branch for course authoring.
Testing Tag Drawer:
1. Login to Studio as a non-superuser with course authoring permissions.
1. Visit the Sample Taxonomy Course course-v1:SampleTaxonomyOrg1+STC1+2023_1
1. Navigate to a Unit
1. Click "Manage Tags", either from the sidebar or the unit's menu
1. Add a bunch of tags at various hierarchy levels, and ensure they add as expected.
1. Delete some tags and ensure they delete as expected.
Internal-ref: …
> fix: fixed typo in updateContentTaxonomyTags URL [FC-0036]

- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsCollapsible.test.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
- src/content-tags-drawer/data/api.js
- src/content-tags-drawer/data/api.test.js
- src/content-tags-drawer/data/apiHooks.jsx
- src/content-tags-drawer/data/apiHooks.test.jsx
- src/content-tags-drawer/messages.js
This PR makes minor improvements in the search taxonomy UI.
- It expands taxonomies that match the search and highlight the search term.
- Add "No tag found with search term '....'" message.
- Part of https://github.com/openedx/modular-learning/issues/176
Open the tagging drawer and check the search responses to different queries
___
Private-ref: [FAL-3615](https://tasks.opencraft.com/browse/FAL-3615)
> feat: add search highlight/expand  and "no tags" message [FC-0036]

- src/files-and-videos/videos-page/data/api.js
- src/files-and-videos/videos-page/data/api.test.js
- src/files-and-videos/videos-page/data/thunks.js
This PR fixes the page crashing by updating the videos model at one time rather then for each video.
Testing
1. Open a course with at least 50 videos
2. Wait for card skeletons to disappear
3. Try clicking around on the page
- Select videos
- open the info modal
- search for videos
The page should have expected response times
5. Check that the Active column for the videos is correct
> fix: model update for usage locations

- src/content-tags-drawer/data/api.js
- src/content-tags-drawer/data/api.test.js
The #799 PR inadvertently reverted the code change from #815. This PR adds the code from #815 again.
1. Create test taxonomies, tags, orgs, and courses with https://github.com/open-craft/taxonomy-sample-data/
1. Run this PR's branch for course authoring.
1. Login to Studio as a non-superuser with course authoring permissions.
1. Visit the Sample Taxonomy Course course-v1:SampleTaxonomyOrg1+STC1+2023_1
1. Navigate to a Unit
1. Click "Manage Tags", either from the sidebar or the unit's menu
1. Add a bunch of tags at various hierarchy levels, and ensure they add as expected.
1. Delete some tags and ensure they delete as expected.
> fix: revert code due to wrong merge conflict resolution

- src/taxonomy/TaxonomyListPage.jsx
- src/taxonomy/data/types.mjs
- src/taxonomy/import-tags/__mocks__/taxonomyImportMock.js
- src/taxonomy/import-tags/data/api.js
- src/taxonomy/import-tags/data/api.test.jsx
- src/taxonomy/import-tags/data/utils.js
- src/taxonomy/import-tags/messages.js
- src/taxonomy/taxonomy-detail/TaxonomyDetailSideCard.jsx
- src/taxonomy/taxonomy-detail/messages.js
- Adds a new propmt on the import new taxonomy workflow to enter the `export_id`.
- Adds the `export_id` on the Taxonomy page details.
**Supporting information**
- Github issue: https://github.com/openedx/modular-learning/issues/183
- Internal Ticket: [FAL-3620](https://tasks.opencraft.com/browse/FAL-3620)
- openedx-learning related PR: https://github.com/openedx/openedx-learning/pull/145
- edx-platform related PR: https://github.com/openedx/edx-platform/pull/34143
**Screenshots**
**Testing instructions**
- First, follow the testing instructions in https://github.com/openedx/edx-platform/pull/34143
- Go to the [taxonomy list page](http://localhost:2001/taxonomies).
- Import a new taxonomy. 
- Enter an empty `export_id`. Verify the alert.
- Enter an invalid `export_id`. …
> feat: Add export ID on Taxonomy details and import new Taxonomy

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/grading-settings/GradingSettings.jsx
- src/grading-settings/GradingSettings.test.jsx
- src/grading-settings/assignment-section/assignments/AssignmentItem.jsx
- src/grading-settings/assignment-section/assignments/AssignmentTypeName.jsx
- src/grading-settings/assignment-section/index.jsx
- src/grading-settings/credit-section/CreditSection.test.jsx
- src/grading-settings/credit-section/index.jsx
- src/grading-settings/deadline-section/DeadlineSection.test.jsx
- src/grading-settings/deadline-section/index.jsx
- src/grading-settings/grading-scale/GradingScale.jsx
- src/grading-settings/grading-scale/GradingScale.test.jsx
- src/header/Header.jsx
- src/header/utils.js
- src/header/utils.test.js
This PR adds updates the header to check access for the group_configuration and grading sections. It also adds permissions checks for the outline and grading components and creates a view only option for grading.
This is a PR to a [feature branch](https://github.com/openedx/frontend-app-course-authoring/tree/CourseRoles).
> Add permissions checks for group_configuration, grading, outline

- src/taxonomy/tag-list/TagListTable.jsx
- src/taxonomy/tag-list/TagListTable.test.jsx
- src/taxonomy/tag-list/data/types.mjs
Implements https://github.com/openedx/modular-learning/issues/191
Depends on https://github.com/openedx/openedx-learning/pull/156
This updates the UI to display the total number of descendant tags for each tag, not just the direct number of children.
| Before | After |
|-|-|
|  ![before](https://github.com/openedx/frontend-app-course-authoring/assets/945577/494ee1f0-b95c-4ce1-9457-a51d200a8702) |  ![after](https://github.com/openedx/frontend-app-course-authoring/assets/945577/66abc1cc-43cd-4558-af3e-ad759b40d61b) |
Private ref: [FAL-3655](https://tasks.opencraft.com/browse/FAL-3655)
> Display full descendant count on taxonomy tag list page  [FC-0036]

- src/header/messages.js
- src/header/utils.js
- src/header/utils.test.js
This PR adds an item in the `Tools` menu to allow a call of the function that exports the course tags to a CSV file.
* Closes:
* https://github.com/openedx/modular-learning/issues/172
* Depends on:
* https://github.com/openedx/edx-platform/pull/34091
1. Use https://github.com/open-craft/taxonomy-sample-data/ to create some taxonomies.
1. Go to the course page in Studio and add some tags to the units in the course using the `Manage Tags` option:
1. Go to the course authoring MFE (i.e http://apps.local.edly.io:2001/course-authoring/course/course-v1:edX+DemoX+Demo_Course using tutor)
1. Click on the `Export Tags` menu from an existing taxonomy card
1. Check if a CSV file is downloaded with the Course structure and the tags applied to its blocks.
---
Private-ref:
- …
> feat: add export course tags menu

- CODEOWNERS
- catalog-info.yaml
This is related to Maintainership expectations.
CODEOWNERS file will notify teaching-and-learning team members of PR submissions, but there are currently no additional branch protections related to this ownership.
catalog-info.yaml populates Backstage info for the Open edX community. It helps identify that tnl is the owner of this component. This is in relation to Maintainership OEP-55.
> chore: add missing maintainership files

- src/taxonomy/index.scss
- src/taxonomy/tag-list/TagListTable.jsx
- src/taxonomy/tag-list/TagListTable.scss
- src/taxonomy/tag-list/TagListTable.test.jsx
- src/taxonomy/tag-list/data/api.js
- src/taxonomy/tag-list/data/types.mjs
This PR fixes the issues listed in https://github.com/openedx/modular-learning/issues/186
- Run the [taxonomy-sample-data](https://github.com/open-craft/taxonomy-sample-data) script.
- Go to [taxonomy list](http://localhost:2001/taxonomies/) and click on a taxonomy to see the taxonomy details page.
**1. The table header has been removed (so "Showing 7 of 7" no longer appears).**
- Verify that the header has been removed
**2. The table displays up to 100 parent tags at a time. Pagination is only required if there are more than 100 parent tags.**
- Check `Flat Taxonomy` and verify that the table shows 100 parent tags and there is pagination footer.
- Check `TwoLevelTaxonomy` and verify that there is not pagination footer.
**The "expand all" link and the up/down arrows have been moved to the …
> [FC-0036] Refined taxonomy details page

- src/course-unit/add-component/AddComponent.test.jsx
**Settings**
```yaml
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS:
MFE_CONFIG:
ENABLE_UNIT_PAGE: true
```
This pull request adds functionality to display modal windows for the Add component block.
The primary features were implemented:
- Added modals for: Open Response, Advanced components and Text buttons.
**Issue:** https://github.com/openedx/platform-roadmap/issues/321
- Current changes to the module switching widget are in preparation for the final changes to replace the LMS endpoints.
- In the upcoming pull request, the LMS endpoints of the MFE Learning will be substituted with distinct and independent …
> feat: [FC-0044] Course unit page - Modal windows for course unit page components

- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
**This is a backport from master** https://github.com/openedx/frontend-app-course-authoring/pull/710
The "+ New Library" button is absent on the Course Home Page if the Library Authoring MFE is not installed/configured. 
These changes allow usage of the URL to the legacy libraries page.
Before:
After:
> fix: show the "+ New Library" button

- src/header/utils.js
This is a backport of the master branch fix: https://github.com/openedx/frontend-app-course-authoring/pull/687
Remove the duplicated `course-v1` prefix from the URL.
> fix: correct the group configuration link in the header dropdown

- src/utils.js
The Content dropdown items have incorrect URLs for the
internal routing when MFEs are deployed using the common
domain and the PUBLIC_PATH.
1. Open any MFE page for the studio, e.g. Files and Uploads
2. Use the "Content" dropdown in the header to navigate to the "Pages and Resources" page ![image](https://github.com/openedx/frontend-app-course-authoring/assets/47273130/7b6e3676-44e1-4cdb-9b29-c308f1373de8)
3. Observe the result
Incorrect routing - the URL is threaded as a relative one.
Pages and Resources page is opened correctly
- the issue can't be reproduced on the devstack because it doesn't use PUBLIC_PATH for MFEs 
- related issue: https://github.com/openedx/frontend-app-course-authoring/issues/865
- related backport PR for Quince: …
> fix: Incorrect redirect link to Pages & Resources from pages within Course Authoring MFE

- src/index.jsx
The `<Route>` conditional check was against an undefined env variable.
> fix: accessibility page config reference

- package-lock.json
- src/schedule-and-details/ScheduleAndDetails.test.jsx
- src/schedule-and-details/__mocks__/courseSettings.js
- src/schedule-and-details/details-section/DetailsSection.test.jsx
- src/schedule-and-details/details-section/index.jsx
- src/schedule-and-details/index.jsx
- src/schedule-and-details/introducing-section/IntroducingSection.test.jsx
- src/schedule-and-details/introducing-section/index.jsx
- src/schedule-and-details/license-section/LicenseSection.test.jsx
- src/schedule-and-details/license-section/index.jsx
- src/schedule-and-details/license-section/license-selector/LicenseSelector.test.jsx
- src/schedule-and-details/license-section/license-selector/index.jsx
- src/schedule-and-details/requirements-section/RequirementsSection.test.jsx
- src/schedule-and-details/requirements-section/entrance-exam/EntranceExam.test.jsx
- src/schedule-and-details/requirements-section/entrance-exam/index.jsx
- src/schedule-and-details/requirements-section/grade-requirements/GradeRequirements.test.jsx
- src/schedule-and-details/requirements-section/grade-requirements/index.jsx
- src/schedule-and-details/requirements-section/index.jsx
- src/schedule-and-details/schedule-section/certificate-display-row/CertificateDisplayRow.jsx
- src/schedule-and-details/schedule-section/index.jsx
- src/studio-home/data/api.test.js
This PR is to a [feature branch](https://github.com/openedx/frontend-app-course-authoring/tree/CourseRoles) that was created for Campus/Residential Learning Group's (Product Working Group sub-group) [Roles & Permissions Improvement Project](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3763437589/Roles+Permissions+RBAC+Improvements). It has a [platform roadmap issue](https://github.com/openedx/platform-roadmap/issues/246) covering the topic as well.
The main purpose of this PR is to update the code to check that a user has the right permission to access specific parts of the UI. 
The data about if the user has the permission will already be being sent to the CMS and available in the LMS. 
The code should add checks at the correct locations for the permission.
What's covered:
- …
> [ROLES-47] Permissions definitions for Schedule & Details

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/course-xblock/messages.js
- src/course-unit/header-title/HeaderTitle.jsx
**Settings**
```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: ruzniaievdm/feat/unit-children
everyone: true
- name: new_core_editors.use_new_problem_editor
everyone: true
- name: new_core_editors.use_new_video_editor
everyone: true
- name: new_core_editors.use_new_text_editor
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS:
MFE_CONFIG:
ENABLE_UNIT_PAGE: true
ENABLE_NEW_EDITOR_PAGES: true
```
This merge request introduces a new feature that enhances page rendering by incorporating dynamic components. The key components include:
**Component Header:**
- Title: Displays the title of the xblock.
- Edit Button: Allows users to edit the xblock.
- Dropdown Menu: …
> feat: [FC-0044] Unit page - display xblock components

- plugins/course-apps/teams/GroupEditor.jsx
- plugins/course-apps/teams/GroupEditor.test.jsx
- plugins/course-apps/teams/messages.js
- plugins/course-apps/teams/utils.js
- plugins/course-apps/teams/utils.test.js
- src/data/constants.js
- src/index.jsx
**Settings**
```yaml
TUTOR_GROVE_LMS_ENV_FEATURES: |
ENABLE_TEAMS: True
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS: |
MFE_CONFIG["ENABLE_OPEN_MANAGED_TEAM_TYPE"] = True
```
This PR adds support for the new open managed group type. Ref: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3885760525/Open+Managed+Group+Type
Depends on: https://github.com/openedx/edx-platform/pull/33672
> feat: add open managed group type

- package-lock.json
- package.json
- src/content-tags-drawer/ContentTagsCollapsible.d.ts
- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsCollapsible.scss
- src/content-tags-drawer/ContentTagsCollapsible.test.jsx
- src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.scss
- src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
- src/content-tags-drawer/TagBubble.jsx
- src/content-tags-drawer/messages.js
- src/index.scss
This PR add the new "Add Tags" widget. Which separates out staging tags when checking them and committing (saving) them. 
- Closes https://github.com/openedx/modular-learning/issues/188
1. Run you local dev stack.
1. If you don't already have sample taxonomy/tags data, follow the instructions in this repo to generate sample data: https://github.com/open-craft/taxonomy-sample-data
1. Navigate to a sample course and open the tags drawer by clicking on "Manage Tags"
1. Expand some taxonomies and click on the "Add a Tag" select input
1. Confirm the following:
1. When checking tags in the dropdown, it keeps track of which tags are being newly added (staged). If you presse cancel, no changes are made. If press "Add Tags", the new tags are saved
1. Newly added tags appear as …
> [FC-0036] feat: New "Add Tags" widget

- src/files-and-videos/videos-page/data/thunks.js
New videos should be prepended to the list of videos, as it is default filtered by date added.
> fix: add new videos to the front of the videos list

- src/course-outline/page-alerts/messages.js
Reverts openedx/frontend-app-course-authoring#847
Checks did not recently run on this PR so lint errors were not caught. Reverting the PR so the necessary changes can be made.
> Revert "feat: show alerts related files included via paste unit"

- src/content-tags-drawer/ContentTagsCollapsible.d.ts
- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsCollapsible.test.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.scss
- src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
- src/content-tags-drawer/messages.js
This PR adds the ability to navigate the new "Add Tags" widget using the keyboard, making it fully accessible through the keyboard.
- Closes https://github.com/openedx/modular-learning/issues/189
1. Run you local dev stack on this branch
1. If you don't already have sample taxonomy/tags data, follow the instructions in this repo to generate sample data: https://github.com/open-craft/taxonomy-sample-data
1. Navigate to a sample course and open the tags drawer by clicking on "Manage Tags"
1. Expand a taxonomy, and navigate to the "Add a Tag" select input using the keyboard by "tabbing" to it
1. Confirm the following:
1. Once you've navigated to the "Add a Tag" select input the menu should open
1. Tab again and that should take you to the first element in the menu
1. Once …
> [FC-0036] feat: Make tags widget keyboard accessible

- src/files-and-videos/videos-page/data/api.js
This change sends 'Content-Length' in video uploads. AWS bucket is sometimes returning `IncompleteBody` errors, which indicates it needs this portion of the header. When this error occurs, video upload fails.
https://2u-internal.atlassian.net/browse/TNL-11532
> feat: send content-length in video

- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.scss
- src/content-tags-drawer/index.scss
This PR changes the `min-width` of the content tags drawer to better fit content in the screen
Before | After
:-:|:-:
Before | After
:-:|:-:
- Open the Course Outline
- Click on a Unit to edit it
- Click on the `Manage Tags` button in the Side bar of the unit
- Check the results
___
Private ref: [FAL-3687](https://tasks.opencraft.com/browse/FAL-3687)
> fix: content tags drawer width [FC-0036]

- package-lock.json
- package.json
Upgrade fixes default settings improperly saving in problem editor. See openedx/frontend-lib-content-components #[466](https://github.com/openedx/frontend-lib-content-components/pull/466)
for more details
> feat: upgrade frontend-lib-content-components

- src/course-unit/CourseUnit.jsx
- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXBlock.test.jsx
**Settings**
```yaml
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS: |
MFE_CONFIG["ENABLE_UNIT_PAGE"] = True
MFE_CONFIG["ENABLE_NEW_EDITOR_PAGES"] = True
```
This pull request adds to the unit page the ability to edit (for types: `html`, `problem`, `video` only) the settings and content of XBlocks by redirecting creator to full-screen editor pages.
Issue: https://github.com/openedx/platform-roadmap/issues/321
https://www.figma.com/file/YeKFwSpyLaJFDs3f3p3TSa/Studio-1%3A1-mock-ups?node-id=599%3A23595
1. Run master devstack.
2. Start platform make dev.up.lms+cms+frontend-app-course-authoring and make checkout on …
> feat: [FC-0044] Unit page - make xblock edit functional

- src/studio-home/tabs-section/TabsSection.test.jsx
- src/studio-home/tabs-section/index.jsx
- src/studio-home/tabs-section/messages.js
This PR adds a "Taxonomies" tab to the course authoring home page, and redirects to the taxonomies page when clicked.
1. Run this branch in your local dev stack
2. Make sure you have the `new_studio_mfe.use_new_home_page` flag is enabled
3. Navigate to the course authoring home page: http://apps.local.edly.io:2001/course-authoring/home
4. Confirm that the taxonomies tab appears, as in the screenshot
5. Confirm that clicking on it navigates to the taxonomies list page
---
Private-ref: [FAL-3699](https://tasks.opencraft.com/browse/FAL-3699)
> feat: Add taxonomies tab in home page

- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/AddComponent.test.jsx
- src/course-unit/add-component/add-component-btn/AddComponentIcon.jsx
- src/course-unit/add-component/add-component-modals/ComponentModalView.jsx
- src/course-unit/add-component/messages.js
- src/course-unit/constants.js
- src/course-unit/course-xblock/CourseXBlock.jsx
- src/course-unit/course-xblock/CourseXBlock.test.jsx
**Settings**
```yaml
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS: |
MFE_CONFIG["ENABLE_UNIT_PAGE"] = True
MFE_CONFIG["ENABLE_NEW_EDITOR_PAGES"] = True
```
This pull request adds the display of support labels for xblocks in the advanced xblocks selector modal to the unit page.
Tags in the modal window as "Fully supported", "Provisionally supported" or "Not supported".
Issue: https://github.com/openedx/platform-roadmap/issues/321
The initial 1 commit in this PR is temporary. Once the https://github.com/openedx/frontend-app-course-authoring/pull/912 is merged, the second commit of this PR will become the main …
> feat: [FC-0044] Unit page - display component support label

- src/studio-home/tabs-section/TabsSection.test.jsx
- src/studio-home/tabs-section/index.jsx
This PR is a followup on https://github.com/openedx/frontend-app-course-authoring/pull/923 putting the "Taxonomies" tab behind the `taxonomiesEnabled` flag.
Related PR:
- https://github.com/openedx/frontend-app-course-authoring/pull/923
1. Run this branch in your local dev stack
1. Make sure you have the `new_studio_mfe.use_new_home_page` flag is enabled
1. Make sure you have the `new_studio_mfe.use_tagging_taxonomy_list_page` **disabled** initially
1. Navigate to the course authoring home page: http://apps.local.edly.io:2001/course-authoring/home
1. Confirm that the taxonomies tab does not appear
1. Now **enabled** the `new_studio_mfe.use_tagging_taxonomy_list_page` flag
1. Confirm that the "Taxonomies" tab now appears on the home page
1. Confirm that clicking on it navigates to the …
> feat: Put Taxonomies tab behind flag

- src/content-tags-drawer/messages.js
This PR fixed the case for the `Manage Tags` button and the `Unit tags` header in the unit view.
- Open the course authoring MFE and check if the string are show correctly.
___
Private ref: [FAL-3679](https://tasks.opencraft.com/browse/FAL-3679)
> fix: message case for `Manage tags` and `Unit tags` strings [FC-0053]

- src/taxonomy/taxonomy-menu/TaxonomyMenu.jsx
- src/taxonomy/taxonomy-menu/TaxonomyMenu.test.jsx
One of the test files wasn't running:
```
PASS src/taxonomy/taxonomy-menu/TaxonomyMenu.test.jsx
● Console
console.log
● Test suite failed to run
Returning a Promise from "describe" is not supported. Tests must be defined synchronously.
Returning a value from "describe" will fail the test in a future version of Jest.
```
It's unfortunate that this doesn't raise an error in the current version of Jest, because this is a serious issue that is easy to overlook in the test logs.
While I was at it, I also made a few typing improvements and changed one use of `getByTestId` to the (preferred) `getByRole`
Internal ref: FAL-3702
> Fix the TaxonomyMenu test, which wasn't getting run at all

- src/custom-pages/CustomPages.jsx
If you have organized routing on your server using the `<app.domain.com>/<name-mfe>/...` method, then an error will occur for redirection for this link (this part is lost `<name-mfe>`):
You will not be able to reproduce this error on a local instance:
**The solution involves more flexible routing**
> fix: incorrect redirection link to Pages&Resources from Custom Pages to Quince

- src/custom-pages/CustomPages.jsx
If you have organized routing on your server using the `<app.domain.com>/<name-mfe>/...` method, then an error will occur for redirection for this link (this part is lost `<name-mfe>`):
You will not be able to reproduce this error on a local instance:
**The solution involves more flexible routing**
> fix: incorrect redirection link to Pages&Resources from Custom Pages

- .github/workflows/validate.yml
Codecov uploads are not working right now. Thus, no PR can be merged.
I'm trying to make it so the pipeline doesn't fail if the codecov upload fails.
Relates to https://github.com/openedx/axim-engineering/issues/1109
and to https://github.com/openedx/frontend-app-course-authoring/pull/846
> chore: change github workflow file to not fail pipeline for codecov

- src/files-and-videos/generic/DeleteConfirmationModal.jsx
This PR fixes a undefined bug when deleting files with new Delete Confirmation Modal #938 (See PR for full details)
1. Navigate to the Files page
2. Select a file to delete
3. Should open delete confirmation with the file name is the title
4. Click "Delete"
5. Should successfully delete and close delete modal
> fix: referencing activeStatus for undefined

- src/utils.js
This PR fixes an issue with how we're using `react-datepicker`. Currently, the package has a bug where the date/time input only accepts local time. This PR is a workaround so our date/time is displayed and saved as UTC as expected.
Link to `react-datepicker`'s issue: https://github.com/Hacker0x01/react-datepicker/issues/1787
Test the following with date/time in daylight savings and not in daylight savings.
1. Navigate to the course outline page.
2. Configure a subsection.
3. Change the time on a due date.
4. The time on the input should be the time you selected.
5. Save.
6. The due date shown should be the time you selected.
7. Navigate to the course details page.
8. Repeat the testing steps above for the course end date field.
https://2u-internal.atlassian.net/browse/TNL-11542
> fix: react datepicker workaround for local time

- src/files-and-videos/index.scss
- src/files-and-videos/videos-page/info-sidebar/TranscriptTab.test.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/LanguageSelect.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/LanguageSelect.scss
- src/files-and-videos/videos-page/info-sidebar/transcript-item/Transcript.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/TranscriptMenu.jsx
- src/files-and-videos/videos-page/info-sidebar/transcript-item/TranscriptMenu.scss
This PR changes the `<Dropdown>`s for the transcript tab in the info modal to `<Menu>`s. This resolves an inconsistent bug when the dropdowns appear off screen because their absolute position is off screen unless the user zooms out to correct the position. The functionality and style has remained the same
JIRA Ticket: [TNL-11559](https://2u-internal.atlassian.net/browse/TNL-11559)
1. Navigate to the videos page
2. Add a video (it is okay if the video fails to upload)
3. Click "•••" menu
4. Click "Info"
5. Click Transcript
6. Add a new transcript
7. Select language
8. Language dropdown should appear right below the button
9. Upload a file
10. Click "•••" menu
11. Menu dropdown should appear right below the button
> fix: change dropdowns to menus to fix off-screen render

- package-lock.json
- package.json
- src/files-and-videos/generic/table-components/FilterStatus.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/studio-home/tabs-section/courses-tab/courses-filters/__snapshots__/index.test.jsx.snap
- src/taxonomy/manage-orgs/ManageOrgsModal.jsx
- src/taxonomy/manage-orgs/ManageOrgsModal.test.jsx
- src/taxonomy/manage-orgs/messages.js
This bumps Paragon to v22.2.1, which includes:
* Fix display of menu items with checkboxes (https://github.com/openedx/paragon/issues/3019)
* Some TypeScript typings for `<Icon>`, `<Chip>`, etc. (https://github.com/openedx/paragon/issues/3016)
* ⚠️ Breaking changes to `<Chip>`, `<SearchField>`, `<Pagination>`, `<Form.Autosuggest>` (https://github.com/openedx/paragon/pull/2995)
I have tried to update everything to resolve the breaking changes. But some things (like the video uploads page) I do not know how to test (they aren't working on my devstack).
Private ref: came from work on FAL-3696
> Bump Paragon to v22.2.1, fix some bugs that turned up

- .github/workflows/validate.yml
Update codecove to the latest version and start using the per repo
tokens which will soon be required to get more reliable coverage builds.
This change also has a corresponding addition of a codecov repo upload
token to the repository secrets for this repo.
> build: Update codecov and start using repo tokens.

- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsCollapsible.scss
- src/content-tags-drawer/ContentTagsCollapsible.test.jsx
- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/course-outline/card-header/CardHeader.test.jsx
This PR makes styling updates to the tags drawer and fixes the issue.
Related PR: https://github.com/openedx/frontend-app-course-authoring/pull/939
Internal ticket: [FAL-3645](https://tasks.opencraft.com/browse/FAL-3645)
1. Start your local devstack with this PR
1. Make sure you have some sample taxonomy/tags data setup: https://github.com/open-craft/taxonomy-sample-data
1. Go into a course and click on "Manage tags" option for any unit/block
1. Confirm the following:  
1. There is no "x" in the top right of the drawer
1. Styling of headings has changed to match [figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=11845-19907&mode=design)
1. Dropdown arrows moved to the left of taxonomy name
1. Styling has changed for the count of tags per …
> [FC-0036] Refined tag drawer UI style

- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author",
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
Please provide detailed …
> [FC-0036] feat: Sort taxonomies

- src/pages-and-resources/discussions/DiscussionsSettings.jsx
[INF-1366](https://2u-internal.atlassian.net/browse/INF-1366)
User was unable to scroll down the provider and discussion settings pages in Studio. 
The issue was due to **isOverflowVisible** className. I passed this prop for paragon component **FullscreenModal** and fixed scroll issue.
**Screenshots**
**Before**
**After**
> fix: fixed scroll issue of provider and settings

- src/files-and-videos/generic/FileInput.jsx
- src/files-and-videos/generic/messages.js
This PR fixes the file count in the add toast for the Files and Videos pages. This bug was introduced in PR #885 by not using the spread operator in an array to allow the length of `selectedRows` to be valid and an integer. This change impacts Course Authors.
JIRA Ticket: [TNL-11534](https://2u-internal.atlassian.net/browse/TNL-11534)
> When adding videos on the videos upload page, a toast appears on the bottom when you have selected your upload file. Regardless of the number of videos you’re uploading, it displays `Adding 0 video(s)`
>
> This has no impact on the actual uploading.
>
> Technical note: `<ApiStatusToast>` for the adding action in FileTable.jsx must be passed the correct value for `selectedRowCount`
1. Navigate to the Files page
2. Add one file
3. Toast in left corner should …
> fix: adding files count in toast

- src/files-and-videos/videos-page/VideosPage.jsx
Swithcing from undefined to "" tells the browser to put in a modal which requires users to confirm thier navigation away. this will prevent continued annoyances from upload failures: https://2u-internal.atlassian.net/browse/TNL-11587
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author",
- Provide links to the description of corresponding configuration changes. Remember to correctly …
> feat: add browser dialog to prevent navigation

- src/utils.js
A recent PR (https://github.com/openedx/frontend-app-course-authoring/pull/944) introduces an error for users in positive time zones offsets (eg. Tokyo GMT+9 or Pakistan GMT+5). An invalid date error is encountered when navigating to the Course Updates page. This PR fixes the issue.
Test the following with your local machine set to various time zones. Test with date/time values for daylight savings and not daylight savings.
1. Navigate to the course outline page.
2. Configure a subsection.
3. Change the time on a due date.
4. The time on the input should be the time you selected.
5. Save.
6. The due date shown should be the time you selected.
7. Navigate to the course publish page.
8. Edit an update.
9. Changing the date should work as expected. …
> fix: errors for positive time zones

- src/course-outline/section-card/SectionCard.jsx
- src/course-outline/section-card/SectionCard.test.jsx
- src/course-outline/subsection-card/SubsectionCard.jsx
- src/course-outline/subsection-card/SubsectionCard.test.jsx
- src/course-outline/unit-card/UnitCard.jsx
- src/course-outline/utils.jsx
- src/search-modal/SearchKeywordsField.jsx
- src/search-modal/SearchModal.scss
- src/search-modal/SearchUI.jsx
This PR adds a few styling and UX refinements to the search modal.
- https://github.com/openedx/modular-learning/issues/211
**Note:**
The following points in the related github issue could not be reproduced on master:
> 3. For each result, the course/library name should only appear in the breadcrumbs when “all courses” is selected. (Currently, it shows for the results in “this course” too.)
> 4. If I enter a search term that yields no results, I am unable to open the “type” filter. Change it to behave like the "Tags" filter and display a message like "No types in current results" in that case.
See [comment](https://github.com/openedx/modular-learning/issues/211#issuecomment-2071662503) on PR for more information.
1. Run you local devstack on this branch
1. Make sure you …
> feat: search modal refinements

- src/content-tags-drawer/data/apiHooks.jsx
Updates the code of Tag Drawer to send two messages to parent (if the drawer is a iframe) when the tags are updated:
- One message with updated content tags.
- One message with the content tags count.
- This PR is based on https://github.com/openedx/frontend-app-course-authoring/pull/800
- Github Issue: https://github.com/openedx/modular-learning/issues/216
- Internal ticket: https://tasks.opencraft.com/browse/FAL-3734
- Follow the testing instructions of https://github.com/openedx/edx-platform/pull/34682
> [FC-0036] feat: Send messages after update tags

- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.scss
* Padding to top and left tagging drawer
* Changes in headings in the tagging drawer
- Closes https://github.com/openedx/modular-learning/issues/212
- Internal ticket: [FAL-3719](https://tasks.opencraft.com/browse/FAL-3719)
- Make sure you have some sample taxonomy/tags data setup: https://github.com/open-craft/taxonomy-sample-data
- Go to studio > one course  and open the mange tags of any section/unit.
- Check [this changes](https://github.com/openedx/modular-learning/issues/212#issue-2257267784):
- > Please increase the padding around the top and sides of the tagging drawer (it can be increased by 50-100%).
- > The H2 should be kept as  `<h2>` but should look like an H3
- > The “Manage tags” heading should match the size of the H4 (18px)
- > The Taxonomies headings should should be H3 …
> [FC-0036] refactor: Further refinements to tag drawer

- src/course-outline/card-header/CardHeader.jsx
- src/course-outline/card-header/CardHeader.test.jsx
If proctoring link is not an absolute url, update it to use studio as base url.
`Private-ref`: [BB-8832](https://tasks.opencraft.com/browse/BB-8832)
> refactor: handle relative proctoring link

- src/taxonomy/TaxonomyListPage.jsx
- src/taxonomy/import-tags/utils.js
- src/taxonomy/messages.js
Adds `In progress` message when import a taxonomy
- Closes https://github.com/openedx/modular-learning/issues/205
- Internal ticket: [FAL-3707](https://tasks.opencraft.com/browse/FAL-3707).
- Make sure you have some sample taxonomy/tags data setup: https://github.com/open-craft/taxonomy-sample-data
- Make sure you have taxonomies list page enabled: new_studio_mfe.use_tagging_taxonomy_list_page
- Navigate to the taxonomies list page.
- Click on `Import` button.
- Follow the import workflow.
- Verify the message after finish the workflow.
> feat: Add In progress message on import taxonomy

- src/content-tags-drawer/ContentTagsCollapsible.jsx
- src/content-tags-drawer/ContentTagsCollapsible.test.jsx
- src/content-tags-drawer/messages.js
In the tag drawer in "read" mode, when a taxonomy is expanded that doesn't have any content tags applied, this change shows the text "No tags added yet." and a button to "Add tags", which enables "edit" mode.
* Github issue: https://github.com/openedx/modular-learning/issues/218
* Internal ticket: [FAL-3738](https://tasks.opencraft.com/browse/FAL-3738)
https://github.com/openedx/frontend-app-course-authoring/assets/7556571/05bd08b2-8084-4d1f-a63e-b708f8b08340
* Run with latest master on edx-platform, and this branch of frontend-app-course-authoring.
* Add sample taxonomies & tags with https://github.com/open-craft/taxonomy-sample-data 
* Edit a course in the course authoring MFE.
* Click "Manage tags" to reveal the tag drawer.
* Expand a taxonomy that doesn't have any object tags added …
> [FC-0036] feat: show "No tags added yet. [Add tags]" 

- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/content-tags-drawer/ContentTagsDrawerHelper.jsx
- src/content-tags-drawer/ContentTagsDrawerSheet.jsx
- src/content-tags-drawer/common/context.js
- src/content-tags-drawer/index.js
- src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.jsx
- src/course-outline/card-header/CardHeader.jsx
- src/course-outline/status-bar/StatusBar.jsx
https://www.loom.com/share/c87289b025b34b9ab2381a749dd9db4f?sid=fffede42-3e4d-4cf9-9dae-c0a72a7c2397
- Block close on click ouside an on press Escape to avoid lose user data.
- Wrap with ContentTagsDrawerSheet to build drawer on MFE
- Github issue: https://github.com/openedx/modular-learning/issues/209
- This PR doesn't include:
> The footer of the drawer animates to draw the user's attention to the actions (see [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=13585-6449&mode=design&t=hgTeNriivLM74TtO-4)). Perhaps like [Blink 2 at this link](https://webcode.tools/css-generator/keyframe-animation)
- Internal ticket: [FAL-3711](https://tasks.opencraft.com/browse/FAL-3711)
- Depends on: …
> [FC-0036] feat: Change behaviour of Tag Drawer on click outside

- src/search-modal/FilterByBlockType.jsx
- src/search-modal/SearchModal.scss
- src/search-modal/__mocks__/search-result.json
This fixes a visual bug and sorts the blocktypes in the search filters.
Based on https://github.com/openedx/modular-learning/issues/211
> 6. the number is not visible next to longer filter names (see “Open Response Assessmen...” below.
Dropdown expands to show fullname + count: 
> 7. Please order the options in the type filter by hierarchy:
Section
Subsection
Unit
and then the components in whichever order (perhaps alphabetical)
Dropdown blocktypes are sorted, section -> subsection -> unit -> [the rest alphabetically]:
Related Ticket:
- Closes https://github.com/openedx/modular-learning/issues/211
1. Run this branch in your local tutor
2. Make sure you have sample taxonomy/tags setup
3. Make sure you have https://github.com/open-craft/tutor-contrib-meilisearch/ enabled
4. Click on the …
> feat: search filters refinement

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/constants.js
- src/course-outline/data/selectors.js
- src/course-outline/data/slice.js
- src/course-outline/data/thunk.js
- src/course-outline/header-navigations/HeaderNavigations.jsx
- src/course-outline/header-navigations/HeaderNavigations.test.jsx
- src/course-outline/hooks.jsx
- src/course-outline/messages.js
- src/course-outline/page-alerts/PageAlerts.jsx
- src/course-outline/page-alerts/PageAlerts.test.jsx
- src/course-outline/page-alerts/messages.js
Saves API errors in redux state and displays them as alerts.
`Private-ref`: [BB-8831](https://tasks.opencraft.com/browse/BB-8831)
* Try blocking course outline index (`http://studio.local.edly.io:8001/api/contentstore/v1/course_index/course-v1:OpenedX+DemoX+DemoCourse` in tutor) fetch api using network tab in developer console.
* Refresh and you should see an alert: `Network error`.
* You can also update this [response](https://github.com/openedx/edx-platform/blob/45cd459ddec2ca73d16fc00dfcd2feaccb16efa6/cms/djangoapps/contentstore/rest_api/v1/views/course_index.py#L100-L100) in edx-platform and return a error status code with some message, it will be displayed in the alert. `return Response("some error", status=500)`
> feat: better api error handling

- src/group-configurations/messages.js
**Settings**
```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: ts-develop
- name: contentstore.new_studio_mfe.use_new_group_configurations_page
everyone: true
```
Referring to the decision to return the counters in accordance with the legacy implementation.
1. Run master devstack.
2. Start platform `make dev.up.lms+cms + frontend-app-course-authoring` and make checkout on this branch.
3. Enable the new Group Configurations page by adding a waffle flag `contentstore.new_studio_mfe.use_new_group_configurations_page` in the CMS admin panel.
4. Go to the Group Configurations page.
> fix: [FC-0044] Group configurations - Add a counter for usage groups

- src/certificates/data/selectors.js
- src/certificates/data/slice.js
- src/certificates/data/thunks.js
- src/certificates/layout/MainLayout.jsx
- src/certificates/layout/hooks/useLayout.jsx
- src/course-unit/CourseUnit.jsx
- src/course-unit/data/selectors.js
- src/course-unit/data/slice.js
- src/course-unit/data/thunk.js
- src/course-unit/hooks.jsx
- src/generic/saving-error-alert/SavingErrorAlert.jsx
- src/generic/saving-error-alert/index.js
- src/generic/saving-error-alert/messages.js
- src/generic/saving-error-alert/utils.js
- src/group-configurations/data/selectors.js
- src/group-configurations/data/slice.js
- src/group-configurations/data/thunk.js
- src/group-configurations/hooks.jsx
- src/group-configurations/index.jsx
- src/textbooks/Textbooks.jsx
- src/textbooks/data/selectors.js
- src/textbooks/data/slice.js
- src/textbooks/data/thunk.js
- src/textbooks/data/thunk.test.js
- src/textbooks/hooks.jsx
```yaml
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS:
MFE_CONFIG:
ENABLE_UNIT_PAGE: true
```
If we get errors when using the `POST`, `PUT`, `PATCH`, `DELETE` methods we have to show `ErrorNotification`.
Error handing implemented on the following page:
- Course Unit
- Certificate Page
- Group Configurations
- Textbooks
- Run master devstack.
- Start platform `make dev.up.lms+cms+frontend-app-course-authoring` and make checkout on this branch.
- Enable the page for which error handling logic has been added.
- Go to the page.
https://github.com/openedx/frontend-app-course-authoring/assets/93188219/848f3b41-ed92- …
> feat: [FC-0044] Added errors handling 4xx, 5xx

- src/studio-home/card-item/CardItem.test.jsx
- src/studio-home/card-item/index.jsx
- src/studio-home/card-item/utils.js
```yaml
- name: new_studio_mfe.use_new_home_page
everyone: true
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS:
MFE_CONFIG:
ENABLE_UNIT_PAGE: true
```
Correction of the course rerun link on the Course home page.
1. Go to the Studio home page
2. Follow the link Re-run course
[Issue](https://github.com/openedx/frontend-app-course-authoring/issues/977)
> fix: fixed course rerun route

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/pages/PageGrid.jsx
Allow `PageGrid` to take plugin slot id. Because we reused the component, the `additional_plugin_slot` show up twice. 
TICKET: https://2u-internal.atlassian.net/browse/AU-2022
> fix: allow page grid to take plugin slot id instead

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/data/api.js
- src/course-outline/data/thunk.js
- src/course-outline/highlights-modal/HighlightsModal.jsx
- src/course-outline/publish-modal/PublishModal.jsx
- src/generic/configure-modal/BasicTab.jsx
- src/generic/configure-modal/ConfigureModal.jsx
- src/generic/configure-modal/ConfigureModal.test.jsx
- src/generic/configure-modal/UnitTab.jsx
- src/generic/configure-modal/messages.js
* Adds enable/disable discussion setting checkbox in unit configuration modal.
* Hides release and due date fields in section/subsection configuration modals for self paced courses.
`Private-ref`: [BB-8847](https://tasks.opencraft.com/browse/BB-8847)
* Setup tutor devstack
* Enable course authoring mfe by setting `contentstore.new_studio_mfe.use_new_course_outline_page` waffle flag.
* Open any self paced course in studio.
* Click on three dots for any subsection and click on `Configure` menu option.
* Verify that `Release` and `Due` dates section are not visible.
* Check that the same fields in any instructor paced course, they should be visible.
* Check configure modal for any Unit, an option to enable discussion should be visible.
> feat: discussion setting and release & due date setting 

- package-lock.json
- package.json
`@edx/react-unit-test-utils@2.1.0` is having a breaking change dependency.
https://github.com/openedx/react-unit-test-utils/pull/22
> chore: lock @edx/react-unit-test-utils

- src/export-page/data/thunks.js
- src/export-page/data/thunks.test.js
**Original fix MR:** https://github.com/openedx/frontend-app-course-authoring/pull/785
**Description:** The timestamp of the new export page was always showing the current time, not the export time.
**How to test:**
- go to export page for a very small course (so export won't take long for you to test)
- create an export. Check timestamp
- wait 1 minute, refresh page
- export should not show current time but previous timestamp
- create new export
- now timestamp should show new time
> [Backport] fix: export page timestamp

- src/CourseAuthoringPage.jsx
- src/course-updates/CourseUpdates.jsx
- src/course-updates/CourseUpdates.test.jsx
- src/course-updates/data/selectors.js
- src/course-updates/data/slice.js
- src/course-updates/data/thunk.js
- src/course-updates/hooks.jsx
- src/course-updates/messages.js
- src/index.scss
The JIRA ticket noted below was the original issue of this PR, but was resolved with work surrounding the data/time converter. However, the logging of the error showed a need for better error messaging and callout when no updates are saved to a course. This change impacts Authors.
Before:
After:
JIRA Ticket: [TNL-11572](https://2u-internal.atlassian.net/browse/TNL-11572)
> Reported that authors are unable to edit/change a link in their welcome page. Screenshot of the error message attached below.
1. Open a course and navigate to the Course Updates page
2. Confirm that page loads content as expected
3. If the course has updates, delete all.
4. Empty updates should show first time message with add button
5. Add first update
6. For each button click (adding, editing, deleting) force the api …
> feat: improve error messaging and empty updates

- package-lock.json
- package.json
This PR upgrades @edx/frontend-lib-content-components to 2.1.9. This upgrade includes the following changes:
- [#477](https://github.com/openedx/frontend-lib-content-components/pull/477)
- [#438](https://github.com/openedx/frontend-lib-content-components/pull/438)
> feat: bump frontend-lib-content-components 2.1.9

- src/advanced-settings/setting-card/SettingCard.jsx
- https://github.com/openedx/frontend-app-course-authoring/pull/984
This Pull Request contains small fixes of the info icon shrinking with a long field name on the Advanced settings page.
| <img width="1231" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/7261dbe9-8ffb-4417-8179-b276b4f31d8d"> | <img width="1229" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/9b3458e8-8ead-4d50-b197-df08922a1e42"> |
|---|---|
| <img width="1724" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/f838e8dd-dc54-415d-a462-b366dfd2e2f6"> | <img width="1722" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/4a500632-80ea-4419-ae9d-07f39f0720d8"> | …
> [Backport] fix: info icon shrinking on advanced settings page

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/data/api.js
- src/course-outline/messages.js
- src/header/utils.js
- Show `In progress` toast when exporting course tags
- Github issue: https://github.com/openedx/modular-learning/issues/215
- Internal ticket: [FAL-3733](https://tasks.opencraft.com/browse/FAL-3733)
The `Export Tags` button is on the [StudioHeader](https://github.com/openedx/frontend-app-course-authoring/blob/bc63bfc7f585e3751e356eb213390ee916a742f6/src/header/Header.jsx#L47) [(frontend-component-header)](https://github.com/openedx/frontend-component-header). This component only receives as parameters the [text of the button and the link](https://github.com/openedx/frontend-app-course-authoring/pull/995/files#diff-e660e1566707a54f0764f507112244f0c929f18e3198814a49424507fac6198bL72) to where that button should redirect. 
There is no way to send an `onClick` function or know when the user …
> feat: Show toast when exporting course tags

- src/files-and-videos/files-page/data/thunks.js
This PR resolves the issue with the locked filter not working on the Files page. The lock status was not given the correct string value for the filter matching as a result all files were marked as unlocked for the purpose of filtering, but the actual locked value was properly saved to the backend. Now the lock status properly updates to match the expected filtering values. This change impact Authors.
Issue [#1029](https://github.com/openedx/frontend-app-course-authoring/issues/1029)
1. Navigate to the File page
2. Click Sort and Filter
3. Click "Locked"
4. Click "Apply"
5. Confirm that the expect files appear
6. Click "Clear filters"
7. Click ••• on one of the files
8. Click "Lock"
9. Click Sort and Filter
10. Click "Locked"
11. Click "Apply"
12. Confirm that the newly locked file is …
> fix: wrong lock status update message

- src/course-updates/hooks.jsx
This is a backport of the fix to Redwood branch.
Original PR to master - https://github.com/openedx/frontend-app-course-authoring/pull/1043
> [Backport] fix: update date using utc timezone instead of local (#1043)

- src/files-and-videos/files-page/data/thunks.js
This is a backport of the fix to Redwood branch.
Original PR to master - https://github.com/openedx/frontend-app-course-authoring/pull/1053
BTR issue for Redwood release - https://github.com/openedx/wg-build-test-release/issues/359
> [backport] fix: wrong lock status update message

- package-lock.json
- package.json
This PR upgrades @edx/frontend-lib-content-components to 2.1.10. This upgrade includes the following changes:
* [479](https://github.com/openedx/frontend-lib-content-components/pull/479)
> fix: upgrade frontend -lib-content-componets package

- src/grading-settings/deadline-section/DeadlineSection.test.jsx
- src/grading-settings/deadline-section/index.jsx
This PR resolves the bug that prevented users from entering a minutes only grace period. This change impacts Course Authors.
Issue #1063
1. Open a course's grading page
2. Update the grace period to a value less than one hour
3. Should continue to display minutes value
6. Update the grace period to one hour
7. Should continue to display one hour
8. Update the grace period to greater than one hour
9. Should continue to display value greater than one hour
> fix: allow grace period minutes only

- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.scss
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/content-tags-drawer/ContentTagsDrawerHelper.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
- src/content-tags-drawer/messages.js
- src/content-tags-drawer/utils.js
- feat: Hide language taxonomy when is empty
- feat: New message on search result when taxonomy is empty
- feat: Empty taxonomies message added in drawer
- Closes https://github.com/openedx/modular-learning/issues/219
- Internal ticket: [FAL-3741](https://tasks.opencraft.com/browse/FAL-3741)
- Enable `content_tagging.auto` waffle flag.
- Make sure you have Taxonomy/Tags data setup locally and verify that the command runs well: https://github.com/open-craft/taxonomy-sample-data/
- Create a new course.
- Go to the course -> Manage tags drawer. Verify that you can see the `Languages` taxonomy
- Disable `content_tagging.auto` waffle flag.
- Create a new course.
- Go to the course -> Manage tags drawer. Verify that you can't see the `Languages` taxonomy.
- Go to [taxonomy …
> [FC-0042] Fix: Bug: Unusable "Languages" taxonomy appears in tagging drawer

- src/search-modal/SearchResult.jsx
- src/search-modal/SearchUI.test.jsx
- src/search-modal/__mocks__/search-result.json
- src/studio-home/factories/mockApiResponses.jsx
This PR fixes redirection to the library component in the unit when selecting the search result. It also fixes an issue with navigating to the library mfe when selecting a library component.
1. Run this branch on your local tutor
2. Make sure you have meilisearch configured and running in your local tutor
3. Make sure you have a Content Library with some blocks created under it, eg: text or dropdown blocks
4. Make sure you have a course that contains a library block in a Unit that includes a Content Library block from the previous step. You probably need to use the old studio UI to select the Content Library to be in the library component block in the Unit if you don't already have one set (since you cannot edit library components in the new mfe UI yet)
5. Use the search modal in the mfe …
> fix: Search result redirect to unit lib component

- src/advanced-settings/setting-card/SettingCard.jsx
- https://github.com/openedx/frontend-app-course-authoring/pull/984
This Pull Request contains small fixes of the info icon shrinking with a long field name on the Advanced settings page.
| <img width="1231" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/7261dbe9-8ffb-4417-8179-b276b4f31d8d"> | <img width="1229" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/9b3458e8-8ead-4d50-b197-df08922a1e42"> |
|---|---|
| <img width="1724" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/f838e8dd-dc54-415d-a462-b366dfd2e2f6"> | <img width="1722" alt="image" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/4a500632-80ea-4419-ae9d-07f39f0720d8"> | …
> fix: info icon shrinking on advanced settings page

- src/search-modal/SearchResult.jsx
- src/search-modal/SearchUI.test.jsx
- src/search-modal/__mocks__/search-result.json
- src/studio-home/factories/mockApiResponses.jsx
This PR backports the fix from https://github.com/openedx/frontend-app-course-authoring/pull/1027
Follow testing instructions in https://github.com/openedx/frontend-app-course-authoring/pull/1027
---
Private-ref: [FAL-3724](https://tasks.opencraft.com/browse/FAL-3724)
> fix: Search result redirect to unit lib component (#1027)

- src/content-tags-drawer/ContentTagsDrawer.jsx
- src/content-tags-drawer/ContentTagsDrawer.scss
- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/content-tags-drawer/ContentTagsDrawerHelper.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.jsx
- src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
- src/content-tags-drawer/messages.js
- src/content-tags-drawer/utils.js
Cherry pick of https://github.com/openedx/frontend-app-course-authoring/pull/1031 in Redwood
> [Cherry-pick] Fix: Bug: Unusable "Languages" taxonomy appears in tagging drawer

- package-lock.json
- package.json
This PR upgrades @edx/frontend-lib-content-components to 2.1.10. This upgrade includes the following changes:
* [483](https://github.com/openedx/frontend-lib-content-components/pull/483)
> fix: bump frontend-lib-content-components package

- package-lock.json
- package.json
This PR upgrades @edx/frontend-lib-content-components to 2.1.10. This upgrade includes the following changes:
https://github.com/openedx/frontend-lib-content-components/pull/483
Backport of https://github.com/openedx/frontend-app-course-authoring/pull/1071
Solves https://github.com/openedx/wg-build-test-release/issues/371
> fix: bump frontend-lib-content-components package (#1071)

- src/course-unit/add-component/add-component-modals/ComponentModalView.jsx
- src/studio-home/card-item/index.jsx
- src/studio-home/tabs-section/utils.js
We get an error when loading courses if `displayName` is `null`. This is unlikely to happen but this PR will treat `null` `displayName`s as `''`.
https://2u-internal.atlassian.net/browse/TNL-11654
1. Import a course with no name and organization edX.
2. Without this PR, on the course authoring home page, when searching for courses, there will be an error.
3. With this PR, the courses should display without error.
> fix: handle null displayname

- src/accessibility-page/messages.js
- src/content-tags-drawer/messages.js
- src/course-outline/card-header/messages.js
- src/course-outline/page-alerts/messages.js
- src/course-outline/status-bar/messages.js
- src/course-outline/subsection-card/messages.js
- src/course-team/course-team-member/messages.js
- src/files-and-videos/files-page/messages.js
- src/files-and-videos/generic/messages.js
- src/files-and-videos/generic/table-components/table-custom-columns/ActiveColumn.jsx
- src/generic/ConnectionErrorAlert.jsx
- src/generic/configure-modal/messages.js
- src/import-page/import-stepper/messages.js
This PR fixes warnings about "duplicate message IDs", which seem to have been made by copy-paste errors.
It's important that message IDs are unique -- they're used to identify translated messages.
A side-effect of this change is to introduce new messages into Transifex that need to be translated. Until they are translated, course authors may see some untranslated text.
Private-ref: [FAL-3750](https://tasks.opencraft.com/browse/FAL-3750)
Manual testing shouldn't be needed -- CI passing with no "duplicate message" warnings in the logs is enough.
> fix: warnings about Duplicate message id

- package-lock.json
- package.json
Reverts openedx/frontend-app-course-authoring#1106
The reason is that the pipeline to deploy to stage broke. This commit is probably the reason.
The revert is temporary until the pipeline problem is solved.
> Revert "feat: flcc to 2.2.0"

- Makefile
- package.json
- plugins/course-apps/proctoring/Settings.jsx
- plugins/course-apps/proctoring/Settings.test.jsx
- src/data/services/ExamsApiService.js
Passes on the organization to the LTI providers endpoint for use to filter.
Updated the CI tests to be silent (hides console output). The change reduced CI test generated logs from `35MB` to `298KB`.
> feat: Include org filter when requesting LTI providers

- package-lock.json
- package.json
- src/content-tags-drawer/ContentTagsCollapsible.d.ts
- src/search-modal/BlockTypeLabel.tsx
- src/search-modal/ClearFiltersButton.tsx
- src/search-modal/EmptyStates.tsx
- src/search-modal/FilterByBlockType.tsx
- src/search-modal/FilterByTags.tsx
- src/search-modal/Highlight.tsx
- src/search-modal/SearchFilterWidget.tsx
- src/search-modal/SearchKeywordsField.tsx
- src/search-modal/SearchModal.test.tsx
- src/search-modal/SearchModal.tsx
- src/search-modal/SearchResult.tsx
- src/search-modal/SearchResults.tsx
- src/search-modal/SearchUI.test.tsx
- src/search-modal/SearchUI.tsx
- src/search-modal/Stats.tsx
- src/search-modal/data/api.ts
- src/search-modal/data/apiHooks.ts
- src/search-modal/manager/SearchManager.ts
- src/search-modal/messages.ts
This PR:
- Converts all the search-related code from JS to TS
- Turns on linting for `.ts` and `.tsx` files
- Removes an old search dependency that was accidentally left in
n/a
Make sure the search modal is still working.
> chore: convert all 'search-modal' code to TypeScript

- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/data/thunks.test.js
- src/files-and-videos/videos-page/upload-modal/UploadModal.jsx
This PR fixes when the upload progress bar appears in the upload modal. The current behaviors displays  list of videos and their progress bar after the video has been uploaded to edxval. This may be confusing to the user as they would expect their video(s) to be listed right away. This PR fixes this so that video list and progress bars are displayed as soon as the dialog opens.This change impacts the Course Author.
1. Open the videos page
2. Click "+ Add videos"
3. Select a video
4. Confirm that the video is listed without delay
5.  Click "+ Add videos"
6. Select multiple videos
7. Confirm that the videos are listed without delay
> fix: progress bar display for uploads

- src/search-modal/SearchUI.test.tsx
- src/search-modal/SearchUI.tsx
This PR limits the scope of the search in the modal to only course blocks.
- Using `master` go to the search modal and make sure you have any library XBlock indexed.
- Check out this branch, go to the search modal again, and the libraries blocks should be filtered out.
> fix: only show course blocks in the search modal

- src/grading-settings/grading-scale/react-ranger.js
We include a file (`react-ranger.js`) that is already sort of transpiled, minified, etc. It references a source map that doesn't exist, resulting in this warning seen during `npm run build`:
```
WARNING in ./src/grading-settings/grading-scale/react-ranger.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'frontend-app-course-authoring/src/grading-settings/grading-scale/react-ranger.mjs.map' file: Error: ENOENT: no such file or directory, open 'frontend-app-course-authoring/src/grading-settings/grading-scale/react-ranger.mjs.map'
@ ./src/grading-settings/grading-scale/GradingScale.jsx 11:0-43 152:6-15
@ ./src/grading-settings/GradingSettings.jsx 21:0-56 160:46-58
@ ./src/grading-settings/index.js 2:0-63 2:0-63
@ …
```
> fix: source map warning seen during build

- package-lock.json
- package.json
- src/course-updates/update-form/UpdateForm.test.jsx
- src/generic/WysiwygEditor.jsx
**Settings**
```yaml
- name: contentstore.new_studio_mfe.use_new_updates_page
everyone: true
```
This is a backport to include the resolution of `frontend-lib-content-components` [#476](https://github.com/openedx/frontend-lib-content-components/issues/476)
This upgrade includes the following version updates:
- 2.5.1
- 2.5.0
- 2.4.4
- 2.4.3
- 2.4.2
- 2.4.1
- 2.40
- 2.3.2
- 2.3.1
- 2.3.0
- 2.2.0
See `frontend-lib-content-components` [tagged releases](https://github.com/openedx/frontend-lib-content-components/tags) for more information on individual tags.
> fix: bump frontend-lib-content-components to  2.5.1

- package-lock.json
- package.json
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/create-library/CreateLibrary.test.tsx
Updates `frontend-build` package to add ts* files to coverage report
Check the [Indirect Changes](https://app.codecov.io/gh/openedx/frontend-app-course-authoring/commit/78b5ae3fa70c8e027ffec410b99b5292f7f5797e/indirect-changes?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=openedx) from the coverage report of this branch to check the ts files added.
> fix: add ts* files to cov report

- src/library-authoring/create-library/CreateLibrary.test.tsx
- src/library-authoring/create-library/CreateLibrary.tsx
- src/library-authoring/create-library/messages.ts
This PR adds the missing "Cancel" button from the "Create Library" form.
1. Run this branch in your local env
2. Click on the "New library" button on the top right to open the "create a new library" form
3. Confirm that the "Cancel" button is there
4. Confirm that clicking on the cancel button takes you to the `/libraries` page
---
Private-ref: [FAL-3779](https://tasks.opencraft.com/browse/FAL-3779)
> feat: Add cancel create library button

- src/library-authoring/EmptyStates.tsx
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/LibraryHome.tsx
- src/library-authoring/LibraryRecentlyModified.tsx
- src/library-authoring/components/LibraryComponents.test.tsx
- src/library-authoring/components/LibraryComponents.tsx
- src/library-authoring/components/LibrarySection.tsx
- src/library-authoring/messages.ts
- src/search-manager/ClearFiltersButton.tsx
- src/search-manager/SearchManager.ts
- src/search-manager/SearchSortWidget.tsx
- src/search-manager/data/api.ts
- src/search-manager/data/apiHooks.ts
- src/search-manager/index.ts
- src/search-manager/messages.ts
Adds a widget to the library component search manager which sorts the search results based on the selected option.
Plus the Recently Modified components section from https://github.com/open-craft/frontend-app-course-authoring/pull/52.
Part of https://github.com/openedx/frontend-app-course-authoring/issues/1038
Blocked by: 
* https://github.com/openedx/edx-platform/pull/35103
* https://github.com/openedx/frontend-app-course-authoring/pull/1141
Private-ref: [FAL-3758](https://tasks.opencraft.com/browse/FAL-3758)
Run the latest `master` branch in Studio/CMS
0. Reindex studio to update the index settings: `tutor dev run cms ./manage.py cms reindex_studio --experimental`
1. Create a new library
2. Add components to the library.
3. From the shell, publish the library:
```
from …
```
>  feat: adds sort widget to search manager and library component page [FC-0059]

- package-lock.json
- package.json
This PR fixes the package.json to match the version in package-lock.json. When the  versions do not match it sometimes does not pick up the most recent upgrades for the package. This was found on the edX production environment when locally the static asset link replacement was working locally, but was rewriting the links with a buggy function from a previous `frontend-lib-content-components` version. This change impacts "Developers" and "Authors"
> fix: package.json out of sync with package-lock.json and upgrade

- src/library-authoring/LibraryAuthoringPage.test.tsx
Fixes flaky test after merging https://github.com/openedx/frontend-app-course-authoring/pull/1147
cf https://github.com/openedx/frontend-app-course-authoring/actions/runs/10166343467/job/28116281335
Private-ref: [FAL-3758](https://tasks.opencraft.com/browse/FAL-3758)
Testing change only; no manual testing required.
> test: fix flaky library-authoring test [FC-0059]

- package-lock.json
- package.json
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.jsx
- src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.test.jsx
This PR replaces ai-translations component with a plugin slot from the @openedx/frontend-plugin-framework
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author",
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
Be …
> feat: replace ai-translations component with a plugin slot

- package-lock.json
Reverts openedx/frontend-app-course-authoring#1184
This upgrade contains a bug that prevents images from rendering properly in the text and simple problem editor.
> Revert "fix(deps): update dependency @edx/frontend-lib-content-components to v2.6.4"

- src/files-and-videos/videos-page/data/thunks.js
- src/files-and-videos/videos-page/messages.js
- src/files-and-videos/videos-page/upload-modal/UploadProgressList.jsx
- src/files-and-videos/videos-page/upload-modal/UploadStatusIcon.jsx
This change removes the progress bar from the video upload modal and replaces it with text and a spinner. The progress bar was unable to be updated based on the progress of the AWS api connection and would always remain empty even when competed. To prevent user confusion a spinner and text changes are now used to indicate upload progress.
Before
After
JIRA Ticket: [TNL-11671 🔒 ](https://2u-internal.atlassian.net/browse/TNL-11671)
1. Navigate to the videos page
2. Click "Add Videos"
3. Select multiple videos
4. Check that the videos go through the following stages
i. Queued
ii. Uploading
iii. Failed or Check icon
> feat: replace progress bar with loading spinner

- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/messages.ts
- src/search-manager/data/api.ts
This PR adds the feature to copy library components to the clipboard to be later pasted into a course or another library (in progress https://github.com/openedx/frontend-app-course-authoring/issues/1176)
**Note:** Drag and Drop blocks will be supported in a follow up task
Closes https://github.com/openedx/frontend-app-course-authoring/issues/1104
Depends on:
- https://github.com/openedx/edx-platform/pull/35211
- Create a new library v2
- Add components to this library (Text, Problems or Video; Drag and Drop is NOT supported right now)
- Select the "Copy to clipboard" option in the card menu
- A toast must show "Component copied to clipboard"
- Go to a course of your choice
- Open a Unit
- Paste the block and check the results
- You can check the error toast trying to copy a Drag and Drop …
> [FC-0059] feat: add copy to clipboard feature to library authoring

- src/generic/clipboard/hooks/useCopyToClipboard.js
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/LibraryComponents.test.tsx
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
This PR adds the ability to paste blocks from the clipboard into a v2 Library. It adds a new button "Paste From Clipboard" that appears the user's clipboard contains a block that can be pasted into the library. In the case where the clipboard contains a unit (which cannot be pasted in a library), then the "Paste From Clipboard" button does not appear.
Related Ticket:
- https://github.com/openedx/frontend-app-course-authoring/issues/1176
- Depends on https://github.com/openedx/edx-platform/pull/35199/
1. Run you devstack on the branch in https://github.com/openedx/edx-platform/pull/35199/
1. Run the frontend on this branch
1. Make sure you have a v2 library created, create one if not, and add a bunch of components to it
1. Navigate to the v2 library, and click on the 3-dot menu of a …
> feat: Library Home - Paste Content [FC-0059]

- src/search-manager/FilterByBlockType.tsx
- src/search-manager/FilterByTags.tsx
Change the dropdown checkbox click area to match the whole highlighted line.
This change came from a UI/UX review [comment](https://github.com/openedx/frontend-app-course-authoring/issues/1048#issuecomment-2278331597).
- Open the new library v2 Home
- Check the `Tags` and `Types` filter checkbox click area
---
Private ref: [FAL-3763](https://tasks.opencraft.com/browse/FAL-3763)
> fix: dropdown checkbox click area [FC-0059]

- src/library-authoring/data/apiHooks.ts
- src/library-authoring/library-info/LibraryInfo.test.tsx
- src/library-authoring/library-info/LibraryPublishStatus.tsx
**Related PRs**:
* https://github.com/openedx/edx-platform/pull/35243
* https://github.com/openedx/openedx-learning/pull/207
Issue: #1200
**Test instructions:**
* Setup latest tutor nightly locally.
* Install https://github.com/open-craft/tutor-contrib-meilisearch and enable the plugin
* Checkout above PRs from edx-platform and openedx-learning.
* Mount both the directories in tutor using `tutor mounts add <path>`.
* Start tutor using `tutor dev launch -I`
* Go to studio -> Libraries and create a new library.
* Create some components and click on publish button in the sidebar.
* Verify that everything is saved.
* Add some more components and click on `Discard changes` button in sidebar.
* Verify that newly created components are not visible.
**Original PR and comments:** …
> fix: discard button  [FC-0062]

- src/generic/processing-notification/index.jsx
- src/generic/toast-context/index.test.tsx
- src/generic/toast-context/index.tsx
Change the `Toast` component used in our `toast-context` to match the existing element in course authoring.
This change came from a UI/UX review [comment](https://github.com/openedx/frontend-app-course-authoring/issues/1104#issuecomment-2286722658).
- Create a new library v2
- Add components to this library (Text, Problems or Video; Drag and Drop is NOT supported right now)
- Select the "Copy to clipboard" option in the card menu
- A toast must show "Component copied to clipboard"
---
Private ref: [FAL-3769](https://tasks.opencraft.com/browse/FAL-3769)
**Settings**
```yaml
TUTOR_GROVE_MFE_LMS_COMMON_SETTINGS: |
MFE_CONFIG["LIBRARY_MODE"] = "mixed"
PLUGINS:
- mfe
- grove
- meilisearch
- s3
```
**Tutor requirements**
```
git+https://github.com/overhangio/tutor.git@nightly …
```
> refactor: change toast component [FC-0059]

- .github/workflows/validate.yml
As a first step in the upgrade to Node 20, add it to the CI matrix as a non-blocking test.
See [the tracking issue](https://github.com/openedx/frontend-app-course-authoring/issues/873) for further information.
> test: Add Node 20 to CI matrix

- src/library-authoring/LibraryAuthoringPage.scss
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/index.scss
- src/library-authoring/library-info/LibraryInfoHeader.tsx
- src/library-authoring/library-sidebar/LibrarySidebar.tsx
UI fixes from [comments](https://github.com/openedx/frontend-app-course-authoring/issues/1041#issuecomment-2293982697) from AC Testing of Library Info Sidebar:
- Github issue: https://github.com/openedx/frontend-app-course-authoring/issues/1041
- Internal ticket: [FAL-3812](https://tasks.opencraft.com/browse/FAL-3812)
- Open a library in the course authoring MFE
- Check that the Library Info Sidebar is open by default
- Check that you can close the Library Info Sidebar by clicking the `Library Info` button next to the `New` button.
- Verify all the changes [commented in AC testing](https://github.com/openedx/frontend-app-course-authoring/issues/1041#issuecomment-2293982697)
**Settings**
```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/open-craft/edx-platform.git
EDX_PLATFORM_VERSION: …
```
> Library info sidebar UI fixes

- src/search-manager/FilterByBlockType.tsx
Small fix to add `key` param to the `FilterItem` component and remove console warning.
> fix: FilterItem key warning

- src/schedule-and-details/requirements-section/RequirementsSection.scss
- made fixed height for the prerequisite course dropdown list. 
Note: same height is set for the course language dropdown list.
1. add waffle flag `contentstore.new_studio_mfe.use_new_grading_page` (in /admin/waffle/flag);
2. go to `studio -> Settings -> Schedule & details`;
3. scroll page till the end and click on Prerequisite course drop-down
Drop-down list goes beyond footer
Drop-down list has the same height as Course language
**Course language example**
> feat: fixed height for prerequisite course dropdown list

- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
Currently the `New Library` button is shown to studio users even if they don't have the required access to create a library. This creates a confusing user experince for the user, since if such an user tries to create a library, they get a error down the UI flow.
This PR fixes this behavior for V1 libraries inline with the the legacy Studio UI
1. Setup this PR branch in a local or sandbox environment.
2. Login to studio through a user account without any staff access
3. Ensure New Library button is missing there.
Private Ref: [BB-9077](https://tasks.opencraft.com/browse/BB-9077)
> feat: remove new library button if user does not have create access for v1 libraries

- package-lock.json
- package.json
This fixes some problems with the dependencies and removes unused dependencies.
See inline comments for explanations of each change.
n/a
1. Run `npm ci --omit=dev && npm run build` to ensure that this MFE can be built without `devDependencies`
2. Verify that tests are passing.
Private ref: [FAL-3819](https://tasks.opencraft.com/browse/FAL-3819)
> Clean up dependencies [FC-0062]

- src/frontend-platform.d.ts
- src/library-authoring/add-content/messages.ts
- src/library-authoring/component-info/messages.ts
- src/library-authoring/components/messages.ts
- src/library-authoring/library-info/LibraryInfo.tsx
- src/library-authoring/library-info/LibraryPublishStatus.tsx
- src/library-authoring/messages.ts
- src/search-manager/messages.ts
- src/search-modal/messages.ts
- src/studio-home/card-item/index.jsx
- src/studio-home/tabs-section/libraries-v2-tab/libraries-v2-filters/libraries-v2-order-filter-menu/messages.ts
Adds TypeScript types for `frontend-platform/i18n`, to help with development, especially related to the editors.
Just make sure the code builds and tests pass as normal. No user-visible changes.
Private ref: [FAL-3819](https://tasks.opencraft.com/browse/FAL-3819)
> feat: Add type stubs for frontend-platform/i18n [FC-0062]

- src/data/constants.js
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/create-or-rerun-course/hooks.jsx
- src/generic/create-or-rerun-course/messages.js
There's no validation for combined length of organization, course number and course run:
For legacy:
---
Fix:
> fix: no validation for combined length of org, number, run

- src/data/constants.js
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.jsx
- src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
- src/generic/create-or-rerun-course/hooks.jsx
- src/generic/create-or-rerun-course/messages.js
**This is a [backport](https://github.com/openedx/frontend-app-course-authoring/pull/1262) from the master.**
There's no validation for combined length of organization, course number and course run:
For legacy:
---
Fix:
> fix: no validation for combined length of org, course number and course run for Redwood

- src/generic/create-or-rerun-course/hooks.jsx
This concerns fixing a bug from [**this issue**](https://github.com/openedx/frontend-app-course-authoring/issues/1199)
> fix: create course button inactive after using org drop-down

- src/CourseAuthoringPage.jsx
- src/header/Header.tsx
- src/header/hooks.js
- src/header/hooks.test.js
Hides the "Advanced Settings" item from the "Settings" drop-down if the studio home endpoint's response contains `can_access_advanced_settings: false`.
Re-use the testing steps from https://github.com/openedx/edx-platform/pull/35426. As a test user, go to Studio and make sure you don't see the "Advanced Settings" drop-down menu item anywhere.
> Hide "Advanced Settings" settings item [BB-9081]

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx
This PR aims to solve the issue https://github.com/openedx/frontend-app-course-authoring/issues/1016 by showing the thumbnail from the `videoSettingsModal` only when the `Video ID` is one given by edX according to [this method](https://github.com/openedx/frontend-lib-content-components/blob/0c53d8c4919c263368c397eb9e32253f0a692a01/src/editors/data/services/cms/api.js#L275)
**Additionally**, this PR fixes a bug when trying to delete a `Fallback videos` URL:
Go to the course authoring, and access a unit of a course. Now create a video and follow this:
1. If in `Video ID` you insert a UUIDv4 like `235d2e0e-864d-4b00-906a-77555c72fbb6`, then the `Thumbnail` feature will be shown
2. If you write any other thing in `Video ID`, the thumbnail will be hidden (it is not an edX video)
3. Now, if you …
> refactor: remove thumbnail for non-edX videos & allow removing fallback URLs

- README.rst
For https://github.com/openedx/frontend-app-course-authoring/issues/1250
> docs: update README based on rename

- src/editors/data/redux/app/selectors.js
- src/editors/data/redux/app/selectors.test.js
This change impacts course authors. Editors for course block depend on `unitUrl` to navigate the user back to the unit page. When trying to save a course block and the `unitUrl` is not defined, the user can fall into a infinite loop of trying to save and the page just reloading the editor. The issue does not occur in library blocks because their return URLs are constructed from the `learningContextId` or use a parent function to exit.
1. Open a course block
2. Confirm that the block loads
3. Click "Save"
4. Should be navigated back to the unit page
5. Open a V1 library block
6. Confirm that the block loads
7. Click "Save"
8. Should be navigated back to the V1 library page
9. Open a V2 library block
10. Confirm that the block loads
11. Click "Save"
12. Should be navigated back to the V2 …
> fix: isInitialized selector depends on unitUrl for course blocks

- src/files-and-videos/files-page/FileValidationModal.jsx
This bug was discussed [here](https://github.com/orgs/openedx/projects/28/views/16?pane=issue&itemId=62425234), [here](https://github.com/orgs/openedx/projects/28/views/16?pane=issue&itemId=63933528) and fixed in [this PR](https://github.com/openedx/paragon/pull/2939). However, the fix was not applied to all modal windows in course authoring. In this PR, we have added the fix to the 'Overwrite Files' modal window
Before fix
https://github.com/user-attachments/assets/c138600b-4e17-4acd-b242-9c2865340404
After fix
https://github.com/user-attachments/assets/07599f21-b0a1-4a09-8671-9c8120316717
> fix: Fix content overflow in the Overwrite Files modal window

- src/files-and-videos/files-page/messages.js
Minor fix for a missing translation in the Lock File tooltip. This text was taken from the master branch.
Before
After
> fix: Add missed translation for Lock File tooltip

- src/index.scss
- src/library-authoring/LibraryAuthoringPage.scss
- src/library-authoring/LibraryCollections.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/components/ComponentCard.scss
- src/library-authoring/components/LibraryComponents.tsx
- src/library-authoring/index.scss
This PR fixes the library authoring sidebar width and change the card grid to have auto-columns instead for breakpoints.
Part of:
- https://github.com/openedx/frontend-app-course-authoring/issues/1221
- Checkout this branch
- Open the library authoring page for a library with some components
- Resize the screen and check the responsiveness for the 'Components` and the 'Collections' tabs.
___
Private ref: [FAL-3820](https://tasks.opencraft.com/browse/FAL-3820)
> fix: responsiveness on library authoring sidebar [FC-0062]

- src/studio-home/StudioHome.jsx
- src/studio-home/StudioHome.test.jsx
Based on #1216 
Currently the New Library button is shown to studio users even if they don't have the required access to create a library. This creates a confusing user experince for the user, since if such an user tries to create a library, they get a error down the UI flow.
This PR fixes this behavior for V1 libraries inline with the the legacy Studio UI
Refer #1216
Private Ref: [BB-9077](https://tasks.opencraft.com/browse/BB-9077)
> feat: remove new library button if user does not have create access for v1 libraries (#1216)

- src/library-authoring/components/CollectionCard.test.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/messages.ts
- src/search-manager/data/api.ts
Adds children count to collection cards.
`Private-ref`: [FAL-3837](https://tasks.opencraft.com/browse/FAL-3837)
**Two options:**
* Setup https://github.com/openedx/frontend-app-authoring/pull/1281 and follow its test instructions to add collection and its components.
* Check collections tab for children count
**OR**
* Follow test instructions from https://github.com/open-craft/edx-platform/pull/684 to add components to collection programmatically.
* Check collections tab for children count
> feat: show children count in collection card

- src/pages-and-resources/app-settings-modal/AppSettingsModalBase.jsx
This is backport from master branch - https://github.com/openedx/frontend-app-authoring/pull/1301
This fix is similar to the adjacent fix - https://github.com/openedx/frontend-app-authoring/pull/1291, but now applied to modals on the Pages and Resources page
Before
https://github.com/user-attachments/assets/159f0c1a-d130-4ed4-beb2-f1bf88a9b5d1
https://github.com/user-attachments/assets/39ad2755-d41b-400b-91d4-d2e5d62dffaf
After
https://github.com/user-attachments/assets/bfdff6eb-7f6f-4a52-bfcf-50752d1ac55f
> fix: Fix content overflow in the Pages & Resources modal windows

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
This sets the browser tab title to the title of the current library.
| Before | After |
|--|--|
| ![Before](https://github.com/user-attachments/assets/27bc8526-06a6-4e75-b77f-dd3640dbd863) | ![After](https://github.com/user-attachments/assets/721b2dc6-4ad6-42fa-bb8c-c53de261f2ed) |
This is a drive-by fix while working on [Private ref: [FAL-3827](https://tasks.opencraft.com/browse/FAL-3827)].
Check out a few different libraries in the MFE. Check the title in the browser.
> Display library title in browser tab [FC-0062]

- plugins/course-apps/proctoring/Settings.jsx
- plugins/course-apps/proctoring/Settings.test.jsx
- plugins/course-apps/proctoring/messages.js
When using LTI exams course staff permissions are required to alter exam settings on a course. In some cases a user may have access to this page but no ability to alter these settings. We'd like to add a more specific error message to authorization errors so to root cause can be quickly identified by the user or support team.
[COSMO-477](https://2u-internal.atlassian.net/browse/COSMO-477) [2u-internal]
> feat: improve error message for proctored exam settings

- src/editors/EditorContainer.scss
- src/index.scss
**TL;DR -**
This pull request contains mobile phone adaptation fixes for Problem Editor page.
Added general rearrangement of pages, indentations, and fixed element deformation during adaptation.
**Related PRs:**
- frontend-lib-content-components main https://github.com/openedx/frontend-lib-content-components/pull/422
- frontend-app-course-authoring quince https://github.com/openedx/frontend-app-course-authoring/pull/921
- frontend-app-course-authoring master https://github.com/openedx/frontend-app-course-authoring/pull/922
**What changed?**
|  Before |  After |
|---|---|
|  <img width="431" alt="12" src="https://github.com/openedx/frontend-app-course-authoring/assets/17108583/52e7b744-0093-4d7e-9a3b-4f2926ce4583">  |  <img width="429" alt="11" …
> fix: layout responsive for edit page

- src/library-authoring/component-info/ComponentDetails.test.tsx
- src/library-authoring/component-info/ComponentDetails.tsx
- src/library-authoring/component-info/ComponentDeveloperInfo.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-info/ComponentManagement.test.tsx
- src/library-authoring/component-info/ComponentManagement.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/generic/history-widget/HistoryWidget.scss
- src/library-authoring/generic/history-widget/index.tsx
- src/library-authoring/generic/history-widget/messages.ts
- src/library-authoring/generic/index.scss
This PR adds the `Details` tab in the Component Sidebar.
Part of:
- https://github.com/openedx/frontend-app-authoring/issues/1195
Depends on:
- https://github.com/openedx/edx-platform/pull/35508
- Checkout this branch and https://github.com/openedx/edx-platform/pull/35508
- Create a new library and add a component to it
- Click on the component and check the draft status on the `Details` tab
- Update the component name
- Check the updated modified date in the Component History
___
Private ref: [FAL-3803](https://tasks.opencraft.com/browse/FAL-3803)
> feat: add component Details sidebar [FC-0062]

- src/library-authoring/component-info/ComponentManagement.test.tsx
- src/library-authoring/generic/status-widget/messages.ts
These times on the libraries metadata view are reported in local time (as they should be!), but were mis-labelled as UTC. This PR just removes the word "UTC".
Private ref: [FAL-3810](https://tasks.opencraft.com/browse/FAL-3810)
> fix: library metadata times are actually displayed in local time

- src/content-tags-drawer/ContentTagsDrawer.test.jsx
- src/content-tags-drawer/ContentTagsDrawer.tsx
- src/content-tags-drawer/data/api.mocks.ts
- src/content-tags-drawer/data/apiHooks.jsx
- src/library-authoring/component-info/ComponentManagement.test.tsx
- src/library-authoring/component-info/ComponentManagement.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/apiHooks.ts
This:
- Adds the `drawer` (default) and `component` variants for `ContentTagsDrawer`.
- Adds `ContentTagsDawer` in the info sidebar of library components.
- Which edX user roles will this change impact? "Course Author"
Github Issue: https://github.com/openedx/frontend-app-authoring/issues/1286
Internal ticket: [FAL-3847](https://tasks.opencraft.com/browse/FAL-3847)
- Run this script to add taxonomies and tags: https://github.com/open-craft/taxonomy-sample-data
- Go to studio and create a new library if you don't have one created.
- Go to the library home of your library.
- Create a new component on your library
- Click on the component card to open the component info. Go to `Manage` tab.
- Verify that the `ContentTagsDrawer` is rendered. Click on `Manage tags` and add some tags. Save.
- …
> feat: Add tags to info sidebar of library component [FC-0062]

- src/library-authoring/component-info/ComponentPreview.tsx
Fix the bug where the XBlock component overflowed the preview modal.
1. Open the preview modal with an XBlock with long content
2. Reduce the viewport height to force modal to shrink
3. Check the results
___
Private-ref: [FAL-3850](https://tasks.opencraft.com/browse/FAL-3859)
> fix: component preview modal overflow  [FC-0062]

- .github/workflows/validate.yml
We're seeing PRs like https://github.com/openedx/frontend-app-authoring/pull/1331 fail because of temporary CodeCov errors. To fix this, it's necessary to run the entire workflow all over again. This PR makes the same improvement we recently made to frontend-app-learning in https://github.com/openedx/frontend-app-learning/pull/1476 so that codecov uploading is a separate step that can be re-tried without needing to run the tests all over again. This makes it faster to resolve the issue, and makes it more clear what step failed.
Same as https://github.com/openedx/frontend-app-learning/pull/1476
You can only test this by checking that the CI build ran correctly.
> fix: upload codecov report as a separate workflow step

- src/generic/block-type-utils/constants.ts
- src/generic/block-type-utils/index.tsx
Lets the default Card.Header background color be grey, not white.
Bug reported on Slack: [comment](https://openedx.slack.com/archives/C06JG6RFE4V/p1726850094053179)
Private-ref: [FAL-3859](https://tasks.opencraft.com/browse/FAL-3859)
Previously:
With this change:
1. Locate / create a course in the Authoring MFE, and add a Survey or Poll or other Advanced component to that course.
2. Use the ... menu for the block to "copy to clipboard"
3. Locate / create a library in the Authoring MFE, and click the "New" button to open the "add component" sidebar.
4. Click "Paste from Clipboard" to paste the Advanced component into the library.
5. Note that the header background color is grey, as shown in screenshot.
> "Other" (e.g Surveys) components should use grey (background: #646464) in the card title bar, not white [FC-0062]

- src/library-authoring/EmptyStates.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/LibraryHome.tsx
- src/library-authoring/LibraryLayout.tsx
- src/library-authoring/LibraryRecentlyModified.tsx
- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/collections/LibraryCollectionComponents.tsx
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/collections/LibraryCollections.tsx
- src/library-authoring/common/context.tsx
- src/library-authoring/components/CollectionCard.test.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/LibraryComponents.test.tsx
- src/library-authoring/components/LibraryComponents.tsx
- src/library-authoring/create-collection/CreateCollectionModal.tsx
- src/library-authoring/library-sidebar/LibrarySidebar.tsx
- src/testUtils.tsx
This PR simplifies some of the library code by moving `libraryId` into the `LibraryContext`. So components can be simplified like this:
... and no longer have to pass `libraryId` using "prop drilling".
This PR is purely a code refactor to pave the way for some changes I need to make to `LibraryContext` in a following PR. There are no changes to functionality. It removes 82 lines of code 😎.
This is part of my work toward https://github.com/openedx/frontend-app-authoring/issues/1321
Private ref: [FAL-3861](https://tasks.opencraft.com/browse/FAL-3861)
> Improve LibraryContext, convert tests to testUtils [FC-0062]

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryRecentlyModified.tsx
- src/library-authoring/add-content/AddContentWorkflow.test.tsx
- src/library-authoring/collections/CollectionDetails.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/components/BaseComponentCard.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/LibraryComponents.test.tsx
- src/library-authoring/components/LibraryComponents.tsx
- src/library-authoring/components/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
- src/search-manager/BlockTypeLabel.test.tsx
- src/search-manager/BlockTypeLabel.tsx
- src/search-manager/FilterByBlockType.tsx
- src/search-manager/messages.ts
Our code was misusing the content libraries [allowed block types](https://github.com/openedx/edx-platform/blob/9ff0dac55cb30c21f7973d503c40f2755671f2de/openedx/core/djangoapps/content_libraries/api.py#L1043) REST API -- we were using it to get translated display names of the various block types, not to find out which block types are allowed in a given library.
This change removes references to this REST API and replaces them with the search manager `BlockTypeLabel`, and lets these translated display names be sourced from Transifex.
Affects Content Authors with Libraries v2 enabled in this MFE.
Private-ref: [FAL-3859](https://tasks.opencraft.com/browse/FAL-3859)
1. Create a v2 library
2. Add a Collection to your library.
Check that the Collection card is labelled correctly.
3. Test adding …
> Use block type label instead of Library block_types REST API [FC-0062]

- src/library-authoring/collections/CollectionDetails.test.tsx
- src/library-authoring/collections/CollectionDetails.tsx
- src/search-manager/data/api.mock.ts
This PR changes the components slots in the Collection Details sidebar to always show Problem, Text and Video component count.
- https://github.com/openedx/frontend-app-authoring/issues/1089#issuecomment-2387142825
- Add components to a Collection
- The Collection Stats should always show Problem, Text and Video slots, and group everything else on the Other slot
___
Private-ref: [FAL-3883](https://tasks.opencraft.com/browse/FAL-3883)
> fix: change collection stats component slots [FC-0062]

- src/generic/CodeEditor.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.tsx
- src/library-authoring/component-info/ComponentDetails.test.tsx
- src/library-authoring/component-info/ComponentDetails.tsx
- src/library-authoring/component-info/ComponentPreview.test.tsx
- src/library-authoring/component-info/ComponentPreview.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
This PR adds a new "Advanced details" section to the "Details" tab of library components in the Authoring MFE. This replaces the previous "developer info" panel that was only visible in development builds. This one is visible to everyone, but hidden behind a collapsible widget.
| Collapsed (default) | Expanded |
|---|---|
| ![Screenshot](https://github.com/user-attachments/assets/eb526a8f-1327-4a9f-8b67-97dd6da93028) <br><br><br><br><br><br><br><br><br><br><br><br> | ![Screenshot](https://github.com/user-attachments/assets/5156110e-a6e5-4d44-90f7-975ff1fa308a) |
It includes the **OLX editor**, with a warning that you need to be very careful using it:
If you make a mistake in the OLX and it's invalid, you'll get an **error message** like this:
I also added a **list of assets**, though it …
> Content Libraries: Advanced Component Info & OLX Editor [FC-0062]

- src/course-outline/page-alerts/PageAlerts.jsx
- src/course-outline/page-alerts/PageAlerts.test.jsx
The alert used to inform about the usage of an upgraded version of discussion forum still shows on refresh after being dismissed.  The goal of this PR is correct that and save the dismissal per course.
- Clone this repository and run `npm insall`
- Ensure your are running Tutor redwood locally (>= 18)
- Mount the clone repository to Tutor using `tutor mounts add  your/path/to/frontend-app-course-authoring`
- Run `tutor dev launch`
- To simplify testing and show the Alert, comment out the following or set the condition to be always false.
```
if (providerType !== 'openedx') {
return null;
}
```
- Dismiss the Alert then refresh. The alert will show again
- Checkout this PR's branch then run `npm install`
- Now after dismissal and refresh, the alert shouldn't show.
BB-9079
> feat: save discussion alert dismissal

- .env
- .env.development
- .env.test
- README.rst
- package.json
When I became maintainer of the Learning MFE, [I updated its README to explain how to easily run it in dev mode on your host, along with Tutor](https://github.com/openedx/frontend-app-learning/pull/1472).
This PR makes the same improvements to the README of the Authoring MFE.
> docs: update the README with an easy way to run the MFE with Tutor (on your host)

- src/assets/scss/_form.scss
This is a minor issue where the calendar icon appears over the opened datepicker modal window.
Before
After
> fix: Calendar icon over datepicker modal

- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- src/library-authoring/component-info/ComponentPreview.test.tsx
This is a subset of https://github.com/openedx/frontend-app-authoring/pull/1349 that doesn't have all the Files & Uploads changes, but just has:
- **refactor: switch Content Library XBlock preview to Studio**
- **fix: disable static asset mangling for v2 Content Libraries**
> Minimal Library Asset Support

- src/index.jsx
- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- src/library-authoring/LibraryBlock/index.ts
- src/library-authoring/component-comparison/CompareChangesWidget.test.tsx
- src/library-authoring/component-comparison/CompareChangesWidget.tsx
- src/library-authoring/component-comparison/messages.ts
- src/library-authoring/index.tsx
- src/library-authoring/legacy-integration/PreviewChangesEmbed.test.tsx
- src/library-authoring/legacy-integration/PreviewChangesEmbed.tsx
- src/library-authoring/library-info/LibraryInfoHeader.test.tsx
This implements in an iframe a very simple view for comparing an old version of a library component with the latest published version. Currently, it's only used by a modal in the legacy UI but soon it will also be used on the Unit page in this MFE.
The part in red is implemented in this MFE PR, and the surrounding modal and buttons are part of the legacy UI (for simpler implementation and better UX consistency)
Part of https://github.com/openedx/frontend-app-authoring/issues/1341
Test along with the platform PR - see instructions in https://github.com/openedx/edx-platform/pull/35669
Private ref: [FAL-3879](https://tasks.opencraft.com/browse/FAL-3879)
> View for comparing published version of library block to previous [FC-0062]

- src/editors/sharedComponents/TypeaheadDropdown/index.jsx
Related to #1199
In TypeaheadDropdown component we set a normalized value instead of original one.
As a result - a lowercased value is saved into DB.
Test instruction:
- go to Home page
- click create new course
- type organization with upper case
- use TAB to move to the next field
- fill a Course number
- fill the Course run
- create course
AR:
- the Org is create in Lower case
ER:
- the org is create in original Upper case
> fix: set original value for TypeaheadDropdown component

- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
The picker component will not call any api on selection.
For: https://github.com/openedx/edx-platform/pull/35670
Please provide detailed step-by-step instructions for testing this change.
> refactor: picker component to only post message with block info [FC-0062]

- package-lock.json
- package.json
Updating to the recently published fix release for Redwood:
- https://www.npmjs.com/package/@edx/frontend-lib-content-components/v/2.5.3
> chore(deps): update @edx/frontend-lib-content-components to v2.5.3

- src/library-authoring/common/context.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/component-picker/ComponentPicker.tsx
- src/library-authoring/component-picker/SelectLibrary.test.tsx
- src/library-authoring/component-picker/SelectLibrary.tsx
- src/library-authoring/components/ComponentCard.tsx
Removes the need to `parentLocator` to component picker and removes next button as well. Now when a user selects a library, they are taken to the next page to select components as no other action is required in library selection page.
* For https://github.com/openedx/edx-platform/pull/35670
Please see https://github.com/openedx/edx-platform/pull/35670
> refactor: remove parentLocator and next button from component picker [FC-0062]

- src/library-authoring/component-info/ComponentAdvancedInfo.tsx
Currently when you open a component in the sidebar, the OLX and static assets are loaded from the backend API, even if you never click on the "Details" tab nor expand the "Advanced Details" collapsible.
This PR is a simple fix so that the OLX and static asset data are only loaded when needed - if the user actually expands and views the "Advanced details" section.
Check your CMS request logs or browser's Network log when viewing a component in the sidebar, before and after this change.
Note there are some other inefficient requests, but we can tackle that another time.
Private ref: [FAL-3905](https://tasks.opencraft.com/browse/FAL-3905)
> perf: don't load advanced info details before they're needed [FC-0062]

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/collections/CollectionDetails.test.tsx
- src/library-authoring/collections/CollectionDetails.tsx
- src/library-authoring/collections/CollectionInfo.tsx
- src/library-authoring/collections/CollectionInfoHeader.test.tsx
- src/library-authoring/collections/CollectionInfoHeader.tsx
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/common/context.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.tsx
- src/library-authoring/component-info/ComponentDetails.test.tsx
- src/library-authoring/component-info/ComponentDetails.tsx
- src/library-authoring/component-info/ComponentInfo.test.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-info/ComponentInfoHeader.test.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/component-info/ComponentManagement.test.tsx
- src/library-authoring/component-info/ComponentManagement.tsx
- src/library-authoring/component-info/ComponentPreview.test.tsx
- src/library-authoring/component-info/ComponentPreview.tsx
- src/library-authoring/component-info/ManageCollections.tsx
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/ComponentDeleter.tsx
- src/library-authoring/library-sidebar/LibrarySidebar.tsx
Clicking on `Add to collection` menu item will display sidebar with `Manage` tab open and `Tags` section collapsed for better visibility of collections section. Also, refactors library context to replace three separate state variables with single object type
* Implements https://github.com/openedx/frontend-app-authoring/issues/1394
* `Private-ref`: [FAL-3848](https://tasks.opencraft.com/browse/FAL-3848)
* Click on `Add to Collection` menu item in components card as well as in the sidebar, it should open up sidebar with Manage tab active and tags section collapsed.gg
> feat: add to collection menu item functionality [FC-0062]

- .env
- .env.development
- .env.test
- CODEOWNERS
- README.rst
- catalog-info.yaml
- package-lock.json
- package.json
- plugins/course-apps/calculator/package.json
- plugins/course-apps/edxnotes/package.json
- plugins/course-apps/learning_assistant/package.json
- plugins/course-apps/live/package.json
- plugins/course-apps/ora_settings/package.json
- plugins/course-apps/proctoring/package.json
- plugins/course-apps/progress/package.json
- plugins/course-apps/teams/package.json
- plugins/course-apps/wiki/package.json
- plugins/course-apps/xpert_unit_summary/package.json
After I updated `tutor-mfe`, I wasn't able to run this with `npm run dev` because it had `PUBLIC_PATH=/course-authoring/` specified. Then I realized there were still a whole lot more things that need to be updated.
This PR changes the name of the npm package. I'm not sure if that will cause any issues? It's working fine on my devstack though.
> fix: this repo has been renamed to frontend-app-authoring

- README.rst
- src/library-authoring/component-info/ComponentInfo.test.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/components/ComponentEditorModal.tsx
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
Implements and enables the publish button functionality in the libraries v2 component sidebar. 
* Implements: https://github.com/openedx/frontend-app-authoring/issues/1353
* Private-Ref: https://tasks.opencraft.com/browse/FAL-3897
* Checkout this PR and the following edx-platform PR https://github.com/openedx/edx-platform/pull/35677
* Configure waffle flags to enable libraries v2: 
```bash 
$ tutor dev run lms ./manage.py lms shell -c "from waffle.models import Flag; Flag.objects.update_or_create(name='contentstore.new_studio_mfe.disable_legacy_libraries', defaults={'everyone': False}); Flag.objects.update_or_create(name='contentstore.new_studio_mfe.disable_new_libraries', defaults={'everyone': False})"
```
* Create a new library and two components inside it.
* Click on one component and …
> feat: publish single library component

- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/LibraryRecentlyModified.tsx
- src/library-authoring/__mocks__/collection-search.json
- src/library-authoring/__mocks__/library-search.json
- src/library-authoring/__mocks__/libraryComponentsMock.ts
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/common/context.tsx
- src/library-authoring/component-info/ComponentInfoHeader.test.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/component-info/ComponentPreview.tsx
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/component-picker/ComponentPicker.tsx
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
- src/search-manager/data/api.ts
Updated the Content Picker to show published components.
- Which edX user roles will this change impact?  "Course Author"
- Create or use a library.
- Create new components and publish the library
- Follow instructions from PR: https://github.com/openedx/frontend-app-authoring/pull/1356 to add library components to a course.
- Select the library and verify that only you can see the published components.
- Create new components. Don't publish the library
- Select the library on the content picker and verify that only you can see the published components (Don't see the new components).
- Publish the library.
- Select the library on the content picker and verify that only you can see the published components.
- Update the title and descriptions of components. Don't publish the library.
- On …
> feat: Show published components on content picker

- src/index.jsx
- src/library-authoring/common/context.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/component-picker/ComponentPicker.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/messages.ts
This PR refactors the `ComponentPicker` and adds the multiple-select feature to be used in https://github.com/openedx/edx-platform/pull/35679 and https://github.com/openedx/frontend-app-authoring/issues/1173.
- Part of:
- https://github.com/openedx/frontend-app-authoring/issues/1173
- This can be tested changing [this](https://github.com/open-craft/frontend-app-course-authoring/blob/037ffcf10bae3f1407310b2c161512d18ea091b1/src/library-authoring/component-picker/ComponentPicker.tsx#L44) following line from `'single'` to `'multiple'` and opening http://apps.local.edly.io:2001/course-authoring/component-picker
___
Private ref: [FAL-3901}](https://tasks.opencraft.com/browse/FAL-3901)
> feat: add onComponentSelected callback function and componentPickerMode types [FC-0062]

- src/editors/EditorContainer.test.jsx
- src/editors/EditorContainer.tsx
- src/editors/__snapshots__/EditorContainer.test.jsx.snap
- src/editors/messages.ts
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/components/LibraryComponents.tsx
- src/search-manager/SearchKeywordsField.tsx
- src/search-manager/SearchManager.ts
- src/search-manager/messages.ts
Adds support for displaying single xblock in a library when passed a query param: usageKey. This is required for directing users to a specific block from course.
https://github.com/user-attachments/assets/7950c17f-3454-45ce-b4e7-79bad929df72
* For https://github.com/openedx/frontend-app-authoring/issues/1340
* https://github.com/openedx/edx-platform/pull/35700
* `Private-ref`: [FAL-3877](https://tasks.opencraft.com/browse/FAL-3877)
* Checkout https://github.com/openedx/edx-platform/pull/35700
* Use new `Library Content` option to add an xblock from libraries
* Click on edit button of the new block in course.
* Verify the alert at the top of the modal.
* Click on the button to open the block in library.
> feat: direct link to single block in library [FC-0062]

- src/generic/delete-modal/DeleteModal.jsx
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/library-info/LibraryInfo.test.tsx
- src/library-authoring/library-info/LibraryPublishStatus.tsx
- src/library-authoring/library-info/messages.ts
Issue: https://github.com/openedx/frontend-app-authoring/issues/1405
https://github.com/user-attachments/assets/5c3313de-3f0a-4f34-b07b-8d4cbff4506c
* add a component in any library
* Click on `Discard changes` button in sidebar and verify the confirmation modal.
> feat: show confirmation dialog before discarding library changes [FC-0062]

- src/editors/containers/TextEditor/index.jsx
- src/editors/containers/TextEditor/index.test.jsx
- src/editors/data/redux/app/reducer.js
- src/editors/data/redux/app/reducer.test.js
- src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/editors/sharedComponents/TinyMceWidget/index.jsx
This PR allows to preview images on the text editor for Libraries.
Closes #1358
Depends on https://github.com/openedx/edx-platform/pull/35681
Please provide detailed step-by-step instructions for testing this change.
> fix: allow to preview images

- src/course-outline/CourseOutline.jsx
- src/header/hooks.js
Fixes the "Export Tags" course menu item so that it works no matter where in the course it's used.
Affects "Course Authors" with tagging enabled.
https://github.com/user-attachments/assets/8e7bae38-ca68-4b72-937a-ede5bb662a10
See: https://github.com/openedx/frontend-app-authoring/issues/1380
Private-ref: [FAL-3873](https://tasks.opencraft.com/browse/FAL-3873)
1. Visit a course page other than the Course Outline in the Authoring MFE (e.g. Advanced Settings, Course Team, Export Course)
2. Click menu item Tools > Export Tags
Should redirect you to the Course Outline page and download the tags export csv.
3. From the Course Outline page, click menu item Tools > Export Tags
Will reload the Course Outline page and download the tags export csv.
> fix: use absolute URL for Export Tags menu item

- src/course-outline/CourseOutline.jsx
- src/header/hooks.js
Use absolute URL for Export Tags menu item so that the menu item works no matter where in the course it's used. Fix this issue: https://github.com/openedx/frontend-app-authoring/issues/1380
Backported for sumac (cherry picked from commit 774728a9c0739fe006d0951252196b5dab6bea58)
See https://github.com/openedx/frontend-app-authoring/pull/1432 for full details and testing instructions.
> [sumac] fix: use absolute URL for Export Tags menu item

- src/library-authoring/component-picker/SelectLibrary.test.tsx
- src/library-authoring/component-picker/SelectLibrary.tsx
- src/library-authoring/component-picker/messages.ts
This PR fixes the empty state text for adding library content if the user can't access any library.
Related to:
- https://github.com/openedx/frontend-app-authoring/issues/1425
- You would need a user with no access to any libraries
- Access http://apps.local.edly.io:2001/course-authoring/component-picker and check if the message is correct
**Note**: If you still see some libraries, make sure that these libraries don't allow public read
___
Private ref: [FAL-3917](https://tasks.opencraft.com/browse/FAL-3917)
> fix: empty state for library selection on component picker [FC-0062]

- src/library-authoring/component-picker/SelectLibrary.test.tsx
- src/library-authoring/component-picker/SelectLibrary.tsx
- src/library-authoring/component-picker/messages.ts
Cherry-pick of https://github.com/openedx/frontend-app-authoring/pull/1440
This PR fixes the empty state text for adding library content if the user can't access any library.
Related to:
- https://github.com/openedx/frontend-app-authoring/issues/1425
- You would need a user with no access to any libraries
- Access http://apps.local.edly.io:2001/course-authoring/component-picker and check if the message is correct
**Note**: If you still see some libraries, make sure that these libraries don't allow public read
___
Private ref: [FAL-3917](https://tasks.opencraft.com/browse/FAL-3917)
> [sumac] fix: empty state for library selection on component picker [FC-0062]

- src/library-authoring/LibraryAuthoringPage.scss
- src/library-authoring/component-info/ComponentPreview.tsx
Fix this issue: https://github.com/openedx/frontend-app-authoring/issues/1390
Backported for sumac (cherry picked from commit https://github.com/openedx/frontend-app-authoring/commit/cff1177ae93db0f63377ef387fca232b24e47c0b)
See https://github.com/openedx/frontend-app-authoring/pull/1438 for full details and testing instructions.
> [sumac] fix: Library Preview Expand button covers dropdown

- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
Link component to collection if pasted in a collection page.
* Fixes: #1435 
* `Private-ref`: [FAL-3922](https://tasks.opencraft.com/browse/FAL-3922)
* Copy any supported xblock from a course or library and paste into a collection in another library.
> fix: add component to collection on paste [FC-0062]

- src/library-authoring/data/apiHooks.ts
This PR fixes the following bug:
> After publishing a library then editing a component, the "Publish" button in Library Info doesn't become enabled until you refresh
Related to:
- https://github.com/openedx/frontend-app-authoring/issues/1455
- Open the library home for a library
- Open the library sidebar and publish the library
- Make sure the "Publish" button is disabled
- Click on a component and open the component's sidebar
- Edit the name of the component
- Open the library sidebar again and check if the "Publish" button is ENABLED
- Publish the library again to reset the status, and make sure the "Publish" button is disabled
- Click on the three-dot menu on a component card and click on edit to open the component editor modal
- Change the component content
- Open the library sidebar …
> fix: enable publish button on library after component edit [FC-0062]

- src/library-authoring/data/apiHooks.ts
Backport of https://github.com/openedx/frontend-app-authoring/pull/1446
This PR fixes the following bug:
> After publishing a library then editing a component, the "Publish" button in Library Info doesn't become enabled until you refresh
Related to:
- https://github.com/openedx/frontend-app-authoring/issues/1455
- Open the library home for a library
- Open the library sidebar and publish the library
- Make sure the "Publish" button is disabled
- Click on a component and open the component's sidebar
- Edit the name of the component
- Open the library sidebar again and check if the "Publish" button is ENABLED
- Publish the library again to reset the status, and make sure the "Publish" button is disabled
- Click on the three-dot menu on a component card and click on edit to open the …
> fix: enable publish button on library after component edit [sumac] [FC-0062]

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.test.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
Fixes: https://github.com/openedx/frontend-app-authoring/issues/1453
* `Private-ref`: [FAL-3873](https://tasks.opencraft.com/browse/FAL-3873)
* https://github.com/openedx/frontend-app-authoring/issues/1453
* Check transcripts in video editor preview in both course and libraries.
* The transcripts part in preview should only be visible for courses.
> chore: hide transcripts in video preview for library

- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
Show a detailed error when 400 Bad Request received while adding a component to a library, either a new or pasted component. The most likely error from the backend here is "library can only have {max} components", and since this error is translated already, we can just report it through.
Content Authors using Libraries v2 are affected by this change.
Error shown on paste:
Error shown on create:
Relates to: https://github.com/openedx/frontend-app-authoring/issues/1456
Private-ref: [FAL-3873](https://tasks.opencraft.com/browse/FAL-3873)
1. Manually decrease `settings.MAX_BLOCKS_PER_CONTENT_LIBRARY` in the backend to a suitable limit for testing.
2. Try to add more than `settings.MAX_BLOCKS_PER_CONTENT_LIBRARY` blocks to a content library
3. Confirm that the updated toast error is legible …
> fix: show a more detailed error on Bad Request

- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
Link component to collection if pasted in a collection page. Fixes: https://github.com/openedx/frontend-app-authoring/issues/1435
(cherry picked from commit 549dbaa0fa5df9451b649cf148adbd8f9137c30f)
Backport of https://github.com/openedx/frontend-app-authoring/pull/1450
> [sumac] fix: add component to collection on paste [FC-0062] (#1450)

- src/library-authoring/component-picker/SelectLibrary.tsx
This PR adds padding between the search bar and the library list.
Also, the render method was refactored to be a bit simpler.
- Part of:
- https://github.com/openedx/frontend-app-authoring/issues/1337#issuecomment-2425279039
-  Open http://apps.local.edly.io:2001/course-authoring/component-picker
- Check the spacing between the search bar and the library list
___
Private ref: [FAL-3931](https://tasks.opencraft.com/browse/FAL-3931)
> fix: add spacing to searchbar and simplify render conditions [FC-0062]

- src/library-authoring/component-picker/SelectLibrary.tsx
Backport of https://github.com/openedx/frontend-app-authoring/pull/1461
This PR adds padding between the search bar and the library list.
Also, the render method was refactored to be a bit simpler.
- Part of:
- https://github.com/openedx/frontend-app-authoring/issues/1337#issuecomment-2425279039
-  Open http://apps.local.edly.io:2001/course-authoring/component-picker
- Check the spacing between the search bar and the library list
___
Private ref: [FAL-3931](https://tasks.opencraft.com/browse/FAL-3931)
> [sumac] fix: add spacing to searchbar and simplify render conditions [FC-0062]

- src/hooks.test.ts
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/add-content/AddContentWorkflow.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
Fixing tests for library-authoring.
After the latest changes in the repository we have some tests related to the library functionality failing. This PR provides fixes for these tests.
> fix: [FC-0070] fixing broken tests

- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/component-picker/ComponentPicker.tsx
- src/library-authoring/component-picker/messages.ts
Displays a info banner if only published content is visible in component picker.
* Fix for https://github.com/openedx/frontend-app-authoring/issues/1485
* Use `Library Content` option from legacy course unit page and verify the banner.
* Use `Existing Library Content` button from collection sidebar to verify that the banner is not displayed when all components are available in picker.
> feat: show info banner in component picker [FC-0062]

- src/library-authoring/component-picker/ComponentPicker.test.tsx
- src/library-authoring/component-picker/ComponentPicker.tsx
- src/library-authoring/component-picker/messages.ts
Displays a infor banner if only published content is visible in component picker.
(cherry picked from commit efd2b3d27d108b8442012aa6ab10c35594f38569)
Backport of #1498
`Private-ref`: [FAL-3944](https://tasks.opencraft.com/browse/FAL-3944)
> [sumac] feat: show info banner in component picker (#1498)

- src/hooks.test.ts
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/AddContentWorkflow.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/common/context.tsx
- src/library-authoring/components/ComponentEditorModal.tsx
- src/testUtils.tsx
Fix for: https://github.com/openedx/frontend-app-authoring/issues/1489
`Private-ref`: [FAL-3922](https://tasks.opencraft.com/browse/FAL-3922)
> fix: remove unnecessary toast notification on adding component

- src/course-outline/card-header/CardHeader.scss
This PR fixes a styling issue seen when the title of a subsection is really long and gets truncated.
OpenCraft Internal Jira ticket: [BB-9078](https://tasks.opencraft.com/browse/BB-9078)
Before styling fix:
After styling fix:
> [BB-9078] Adjust styling when title is truncated

- src/header/messages.js
This link is defined in frontend-component-header, so the message shouldn't be here. Anyway, we are [deleting the link from frontend-component-header too](https://github.com/openedx/frontend-component-header/pull/553), as [the app is being removed from edx-platform](https://github.com/openedx/edx-platform/pull/35852).
> refactor: remove pointless maintenance link message

- src/library-authoring/add-content/AddContentContainer.test.tsx
This PR fixes the testing after the merge of https://github.com/openedx/frontend-app-authoring/pull/1458
> test: fix contentContainer test

- src/editors/containers/EditorContainer/index.tsx
- src/editors/sharedComponents/TinyMceWidget/hooks.js
Fixes https://github.com/openedx/frontend-app-authoring/issues/1426
The following bugs were found with the TinyMCE aux modal (used in emoticons, formulas and embed iframe):
- The TinyMCE aux modal and the Editor modal close when clicking on any content in the aux modal.
- When the user opens the `Edit Source Code` modal, this adds `data-focus-on-hidden` to the TinyMce aux modal, making it unusable (not clickable).
- Since they are two separate modals, the focus remains on the editor modal, making it impossible to use scrolling or inputs from the modal aux.
**Solution:** Move the aux modal inside the editor modal.
One discarded solution: Block the modal editor from closing when interacting with the modal aux. The modal editor still retained focus.
- Which edX user roles will this change …
> fix: TinyMce aux modal issues in text editors [FC-0062]

- src/library-authoring/components/CollectionCard.test.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/search-manager/data/api.ts
When using the library component picker, show the correct number on component count (published components) in collection cards.
- Which edX user roles will this change impact?  "Course Author"
Github issue: https://github.com/openedx/modular-learning/issues/234
Internal ticket: [FAL-3921](https://tasks.opencraft.com/browse/FAL-3921)
Depends on: https://github.com/openedx/edx-platform/pull/35734
- Use this branch of edx-paltform: https://github.com/openedx/edx-platform/pull/35734
- Go library home page of a library
- Create or use a collection
- Create components in the collection
- Publish the library
- Create new components, but not publish the library
- Go to a unit in a course and add a "Library content", using the legacy UI
- Select your library and search your collection
- Check that …
> fix: Show published count component in library content picker [FC-0062]

- src/editors/sharedComponents/TinyMceWidget/hooks.js
Move the aux modal inside the editor modal
(cherry picked from commit https://github.com/openedx/frontend-app-authoring/commit/0365e3809b20251c5f99bd954c5d9c5a8490b725)
Backport of https://github.com/openedx/frontend-app-authoring/pull/1500
Internal ticket: [FAL-3928](https://tasks.opencraft.com/browse/FAL-3928)
> [sumac] fix: TinyMce aux modal issues in text editors [FC-0062] (#1500)

- src/library-authoring/components/CollectionCard.test.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/search-manager/data/api.ts
When using the library component picker, show the correct number on component count (published components) in collection cards.
(cherry picked from commit https://github.com/openedx/frontend-app-authoring/commit/624f5addcfe596279929a62dca457c3e8feb7e7f)
Backport of https://github.com/openedx/frontend-app-authoring/pull/1481
> [sumac] fix: Show published count component in library content picker (#1481)

- src/library-authoring/add-content/AddContentContainer.test.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/common/context.tsx
- src/library-authoring/components/ComponentEditorModal.tsx
- src/testUtils.tsx
(cherry picked from commit 033acc45f19a695f1d98fd318caafa466bfb728b)
Backport of #1490
> [sumac] fix: remove unnecessary toast notification on adding component (#1490)

- src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
- src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/editors/sharedComponents/TinyMceWidget/index.jsx
- src/editors/sharedComponents/TinyMceWidget/index.test.jsx
- src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
- src/generic/WysiwygEditor.jsx
This PR introduces a new prop in the `TinyMceWidget` to enable the `imageuploadModal`, previously the function was linked to `isLibrary` prop but now that libraries is being activated and a change in the logic of that validation was introduced,  other parts of the website such as Schedule and Details and Updates can not render TinyMceWidget. 
This PR introduces a new prop  `enableImageUpload`   to make it semantically correct and manage the behavior of displaying the upload image option. 
[Discussion](https://github.com/openedx/frontend-app-authoring/pull/1516#issuecomment-2487818248)
- Once in your instance, you can go to Schedule and Details in a course and the web page should be render without errors.
- The TinyMCE component should not display the images upload option.
> fix: map image upload feature with enableImageUpload prop in TinyMceWidget

- src/course-outline/CourseOutline.test.jsx
- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.scss
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/constants.js
- src/course-unit/data/api.js
- src/course-unit/data/apiHooks.ts
- src/course-unit/preview-changes/index.scss
- src/course-unit/preview-changes/index.test.tsx
- src/course-unit/preview-changes/index.tsx
- src/course-unit/preview-changes/messages.ts
- src/generic/delete-modal/DeleteModal.jsx
- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- src/library-authoring/component-info/ComponentAdvancedAssets.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/library-info/LibraryPublishStatus.tsx
Implements: https://github.com/openedx/frontend-app-authoring/issues/1464
Depends on: 
* https://github.com/openedx/frontend-app-authoring/pull/1422
* https://github.com/openedx/edx-platform/pull/35861
* https://github.com/openedx/frontend-app-authoring/issues/1464
* https://github.com/openedx/edx-platform/pull/35861
* `Private-ref`: [FAL-3943](https://tasks.opencraft.com/browse/FAL-3943)
* Checkout https://github.com/openedx/edx-platform/pull/35861
* Enable new course unit mfe page using waffle: `contentstore.new_studio_mfe.use_new_unit_page`
* Copy any text, video or problem block from v2 library and paste into any course unit.
* Update the block in library and publish the library.
* Go back to course unit when the block was pasted and use the `update` button in the component header.
* …
> feat: preview library block changes in course unit [FC-0062]

- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/AddComponent.test.jsx
- src/course-unit/add-component/messages.js
- src/course-unit/constants.js
Fix for https://github.com/openedx/frontend-app-authoring/issues/1502
* Depends on 
* https://github.com/openedx/edx-platform/pull/35888
* https://github.com/openedx/frontend-app-authoring/issues/1502
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-3959
* Checkout https://github.com/openedx/edx-platform/pull/35888
* Create a problem bank.
* Click on Add components button in the block.
* The picker modal should open up in the mfe and not inside the iframe.
* Verify that it works as expected.
> feat: show problem bank component picker on window msg [FC-0062]

- package-lock.json
- package.json
...by bumping frontend-component-header 5.7.0 -> 5.8.0
Our reasoning is that the two functions of the Studio Maintenance dashboard (Announcements and Maintenance Banner) have been broken for a while.
It's actually version 5.7.2 that removes the link [1] but since 5.8.0 has no breaking changes, it seemed prudent to jump straight to latest.
[1] https://github.com/openedx/frontend-component-header/releases/v5.7.2
Related PR: https://github.com/openedx/edx-platform/pull/35852
> feat!: remove Maintenance header link

- src/editors/hooks.test.jsx
- src/editors/hooks.ts
Backport of https://github.com/openedx/frontend-app-authoring/pull/1531
This PR fixes the flicker bug described here: https://github.com/openedx/frontend-app-authoring/pull/1528#issuecomment-2494602511
https://github.com/user-attachments/assets/ac51fac2-831c-4c17-be89-3e40814f2454
The `data` object is being mutated with the same value, causing the components to re-render. 
**Note**: There is a racing condition involved, so the flicker doesn't happen consistently.
1. Try to add a new component using the sidebar and check if the flicker stopped happening.
> fix: editor flicker after creating xblock

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/collections/CollectionInfo.tsx
- src/library-authoring/common/context.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
This PR makes the selected tab on the sidebar persist while selecting Components or Collections.
- Related to https://github.com/openedx/frontend-app-authoring/issues/1538
- Open the library authoring page, click on Components/Collections, and check the results
- Note that if you click on a Collection (the default "Manage" tab is shown) and switch to a Component, the "Preview" tab will be shown (it will not persist). This is intended.
___
Private ref: [FAL-3980](https://tasks.opencraft.com/browse/FAL-3980)
> feat: preserve library sidebar tab while switching items

- src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
- src/library-authoring/component-info/ComponentAdvancedInfo.tsx
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
Fix https://github.com/openedx/frontend-app-authoring/issues/1354#issuecomment-2491748690
- Which edX user roles will this change impact?  "Course Author".
GitHub Issue: https://github.com/openedx/frontend-app-authoring/issues/1354#issuecomment-2491748690
Depends on: https://github.com/openedx/edx-platform/pull/35932
Internal ticket: [FAL-3976](https://tasks.opencraft.com/browse/FAL-3976)
- Create or use an existing library.
- Create a new text component, edit the content, and publish the library.
- Edit the content of your new component, but not publish the library.
- Go to Details → Advanced details → OLX Source, and verify that you can see the draft OLX.
- Go to a unit in a course.
- Add a library component, select your library.
- In the Library Component Picker go to `Details → …
> fix: Show published OLX in Library Content Picker [FC-0062]

- src/studio-home/StudioHome.tsx
- src/studio-home/__mocks__/studioHomeMock.js
- src/studio-home/factories/mockApiResponses.jsx
This PR fixes the `+ Add Library` button display according to the new permissions.
- Depends on https://github.com/openedx/edx-platform/pull/35953
- Part of https://github.com/openedx/edx-platform/issues/35943
- Open the course authoring mfe with a Global Staff
- Check if the `+ Add Library` button at the `Courses` and `Libraries [beta]` tabs show the new library form in the mfe (v2 libraries)
- Check if the `+ Add Library` button at the `Legacy Libraries` tab opens a new tab redirecting to the library page on Legacy Studio
- Open the course authoring mfe with a user without permissions
- Check if the `+ Add Library` button at the `Courses` and `Libraries [beta]` tabs is not show
- Check if the `+ Add Library` button at the `Legacy Libraries` tab opens a new tab redirecting to the library …
> fix: content libraries permission [FC-0062]

- src/studio-home/card-item/index.tsx
This PR fixes the link from the cards on the legacy libraries list page.
1. Open the legacy libraries list
2. Click on one library and check if you got redirected
> fix: legacy library link

- src/generic/processing-notification/ProcessingNotification.test.jsx
- src/generic/processing-notification/index.jsx
- src/generic/toast-context/index.test.tsx
- src/generic/toast-context/index.tsx
- src/library-authoring/library-team/LibraryTeam.test.tsx
- src/library-authoring/library-team/LibraryTeam.tsx
- src/library-authoring/library-team/messages.ts
- Updates the message error when the user doesn't exist when adding a new team member to a library.
- Which edX user roles will this change impact? "Course Author"
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1342#issuecomment-2491666441
- Internal ticket: [FAL-3978](https://tasks.opencraft.com/browse/FAL-3978)
- Select a library from the list of v2 Libraries, and open the Library Info sidebar. You need to use a user with Admin access.
- Click on `Manage Access`, and add a user that doesn't exist.
- Verify the new error message.
> fix: Update error messages when adding user to library [FC-0062]

- src/library-authoring/LibraryAuthoringPage.tsx
- src/search-manager/SearchManager.ts
When clearing filters the library authoring page redirects to the first tab that was navigated to. Here's a video for lack of a better explanation:
https://www.loom.com/share/355e907bb767476a8d50c434233bcd23?sid=5349e45e-fe07-4c1d-9d75-f2126cf3fee2
This PR does two things:
- Makes the Active Tab Key independent from the URL, except for the initial load, where the active tab is set from the url.
- Avoids unnecessarily changing SearchParams: Due to a limitation of the useSearchParams react hook, which uses a memoized value for the URL that becomes stale after selecting a tab, it unexpectedly changes the URL value. Unfortunately there's no way to completely avoid this, so if there's a usageKey url param, the hook setter function will be called and the URL will revert to the stale memoized …
> fix: avoid changing url when removing filters

- src/studio-home/tabs-section/courses-tab/courses-filters/index.jsx
This PR makes the Studio Home search bar work as expected. When active/archived filters were on or there was selected any order filter, the search skipped these values and just returned the courses list without the respective filters. Additionally, when a search keyword was applied and a filter was selected, the keyword stayed stuck and the search list returned was not the appropriate
- [courses-filters/index.jsx](https://github.com/openedx/frontend-app-authoring/pull/1497/files#diff-f970504b9f0fcd613b8df290917964121b7b09712cae9760ff41c4646833470e): It was added the filter states to the `useCallback` dependencies so if any of this filters changes, they are applied properly and retrieved the proper data
GitHub Issue: https://github.com/openedx/frontend-app-authoring/issues/1477
Make sure …
> fix: fetch proper courses when keyword searching with applied filters

- src/generic/delete-modal/DeleteModal.jsx
- src/library-authoring/components/ComponentDeleter.test.tsx
- src/library-authoring/components/ComponentDeleter.tsx
- src/library-authoring/components/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.test.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
Implements: https://github.com/openedx/frontend-app-authoring/issues/1418
Allows library authors to undo component deletion by display a toast message with undo button for some duration after deletion.
* Issue: https://github.com/openedx/frontend-app-authoring/issues/1418
* Depends on https://github.com/openedx/edx-platform/pull/35993
* `Private-ref`: [FAL-3986](https://tasks.opencraft.com/browse/FAL-3986)
* Checkout https://github.com/openedx/edx-platform/pull/35993 in edx-platform
* Start tutor devstack.
* Go to any v2 library and add a component, and optionally add this component to any collection.
* Now delete the component and use the `Undo` button in the toast to undo the action.
* Verify that the component is back in library as well as the collection if it was added to any.
> feat: undo component delete [FC-0076]

- src/hooks.ts
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/collections/messages.ts
- src/search-manager/FilterByBlockType.tsx
This PR changes the Library (and Collection) subheader, according to https://github.com/openedx/frontend-app-authoring/issues/1486
- Related to https://github.com/openedx/frontend-app-authoring/issues/1486
- Open a Library and check the header
- Do the same with a Collection
- Open a library with components and collections
- From the Components tab, select a Block Type
- Change to the Collections tab and check if the selection is shown on the dropdown
___
Private ref: [FAL-3981](https://tasks.opencraft.com/browse/FAL-3981)
> refactor: improve library sub header

- src/library-authoring/LibraryAuthoringPage.tsx
- src/search-manager/FilterByBlockType.tsx
This PR adds the `disabled` prop for `FilterByBlockType` component and uses it on the Library Collection tab.
- Related to https://github.com/openedx/frontend-app-authoring/issues/1486
- Open a Library
- Select some block type on the `FilterByBlockType` component
- Navigate to the Collection tab and check if the collections are shown
- Return to the "All Content" tab and check if the previous filter persists
___
Private ref: [FAL-3981](https://tasks.opencraft.com/browse/FAL-3981)
> fix: disable filter by block on collections tab [FC-0076]

- src/course-outline/constants.js
- src/course-outline/data/slice.js
- src/course-outline/data/thunk.js
- src/course-outline/page-alerts/PageAlerts.jsx
- src/course-outline/page-alerts/PageAlerts.test.jsx
- src/course-outline/page-alerts/messages.js
- src/course-outline/utils/getErrorDetails.js
- src/course-outline/utils/getErrorDetails.test.js
Updated to have human readable forbidden error (403), this change came into picture from the discussion
on [issue 361](https://github.com/openedx/platform-roadmap/issues/361#issuecomment-2449310586)
New Alert
Discussion on [issue 361](https://github.com/openedx/platform-roadmap/issues/361#issuecomment-2469510868)
1. Start tutor in the dev mode, `tutor dev launch`
2. Make sure frontend-app-authoring is mounted by `tutor mounts add < path to frontend-app-authoring>`
3. if you have mounted it for the first time you might have to rebuild the openedx-dev image by `tutor images build openedx-dev`
4. We need to stop the containers and start them by `tutor dev stop` followed by `tutor dev start -d`
5. We need to change branch from master to the branch of this PR.
6. …
> feat: Adding human readable 403 error access restricted

- src/library-authoring/create-library/CreateLibrary.test.tsx
- src/library-authoring/create-library/CreateLibrary.tsx
- src/studio-home/__mocks__/studioHomeMock.js
Allows Content Authors to auto-create an organization when creating a library, if auto-creating orgs is allowed by the platform.
https://github.com/user-attachments/assets/67e291b9-408b-470c-b194-698869d35552
Part of: https://github.com/openedx/frontend-app-authoring/issues/1577
Depends on: https://github.com/openedx/edx-platform/pull/36094 <-- this PR must be merged first.
0. Install branch from https://github.com/openedx/edx-platform/pull/36094
With cms `settings.ORGANIZATIONS_AUTOCREATE = True` (default):
1. Visit http://apps.local.openedx.io:2001/authoring/library/create
3. Fill in the form using an organization that does not exist in the available list, e.g. `NewOrg`
4. Click "Create"
Should redirect to the new library's page and auto-create the organization.
With cms …
> fix: allow user provided value if can auto-create orgs [FC-0076]

- src/editors/AdvancedEditor.test.tsx
- src/editors/AdvancedEditor.tsx
- src/editors/Editor.tsx
- src/editors/EditorPage.test.tsx
- src/editors/messages.ts
- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- src/library-authoring/components/ComponentEditorModal.tsx
Creates the `AdvancedEditor` to support editors like Drag and Drop, openresponse, poll, survey, and other advanced editors.
Follow this [discovery](https://docs.google.com/document/d/1d1h8KL5L6RPhEWC05RTfFkLXgrm3UZOBdO5_eZ1U8N8/edit?tab=t.0#heading=h.q3611h1pn2pg) for next steps.
- `AdvancedEditor` created to call `studio_view` of the block
- Update `LibraryBlock`  to support any view (and use `studio_view` in `AdvancedEditor`)
- Intercept `xblock-event` message to close the Advanced editor on cancel or save
- Which edX user roles will this change impact? "Course Author", "Developer".
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1201
- Depends on: https://github.com/openedx/edx-platform/pull/36029
- Use this branch of …
> feat: Add AdvancedEditors with an iframe [FC-0076]

- src/library-authoring/collections/CollectionDetails.tsx
- src/library-authoring/component-info/ComponentDetails.test.tsx
- src/library-authoring/component-info/ComponentManagement.test.tsx
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/generic/history-widget/index.tsx
- src/library-authoring/generic/history-widget/messages.ts
This PR adds the "Last Published" date to the `HistoryWidget`.
- https://github.com/openedx/frontend-app-authoring/issues/1354#issuecomment-2526179107
- Open the library component sidebar
- Open the "Details" tab
- Check the new "Last Published" entity 
___
Private ref: [FAL-4015](https://tasks.opencraft.com/browse/FAL-4015)
> feat: add last published date to HistoryWidget [FC-0076]

- src/grading-settings/grading-scale/GradingScale.scss
- src/grading-settings/grading-scale/components/GradingScaleSegment.tsx
This PR fixes the visibility of the "Remove" button for grade segments. Previously, the button would appear on hover above the segment. But the styling of the button blocked it from being visible. Now, the button appears on hover under the grade range. This change impacts Course Authors.
1. Open a course
2. Navigate to the grading page
3. Add a new grade
4. Hover over new grade
5. Confirm that "Remove" is visible
6. Click "Remove"
7. Confirm that the segment is removed
> fix: hidden remove button

- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.test.jsx
Hides some XBlock settings fields when editing library blocks. These hidden settings fields are relevant to course blocks, but not library blocks.
This change impacts Library Authors, and Course Authors who use Library Blocks and/or Problem Banks.
Part of: https://github.com/openedx/frontend-app-authoring/issues/1317
Relates to: https://github.com/openedx/edx-platform/pull/36158
Private-ref: [FAL-3996](https://tasks.opencraft.com/browse/FAL-3996)
1. Create a problem block in a Content Library.
2. Edit the problem and fill in the question, answer, etc fields.
Note that all the problem settings besides "Hints" have been removed from the library UI.
3. Publish the updated problem block.
4. Copy the problem block to the Studio clipboard.
5. Paste it into a Course Unit.
6. Edit the pasted …
> feat: hide some settings fields when editing a library problem [FC-0076]

- src/editors/sharedComponents/TinyMceWidget/utils.js
This PR resolve issue in text components where the save button became unresponsive after making changes. The problem was caused by a mismatch in the regular expressions used to match specific patterns. One pattern, @asset+block/, ended with a /, while the other, @asset+block@, ended with an @. 
https://2u-internal.atlassian.net/browse/TNL-11741?atlOrigin=eyJpIjoiOWFjZDgwYzhjOWI3NGQ3NDk1MjIyMDgyNmRhNjQ0OTYiLCJwIjoiaiJ9
1. Open a course.
2. Add a new Text component.
3. Select the text in popup.
4. Edit the component in the frontend-app-authoring interface.
5. Use the Insert/Edit Link button to add the link `/asset-v1:olaX+abc99+101+type@asset+block@2.2.3.pdf`.
7. Save the component.
8. Verify that the URL is added without any errors.
> Fix regex mismatch in text block

- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
- src/header/Header.tsx
Fixes https://github.com/openedx/frontend-app-authoring/issues/1637 so that clicking editor toolbars doesn't try to close the modal.
Partially fixes https://github.com/openedx/frontend-app-authoring/issues/1636
Before:
After:
This "Insert" toolbar is shown in the "Expandable" text fields like Answer, Feedback, and Hint (all in the Problem editor), when you click on an empty line (or when the whole input is empty). Most people seemed fine with removing/shortening it, but I was asked on Slack to keep the "image" and "table" insertion tools. Which are also the ones in the [official plugin docs](https://www.tiny.cloud/docs/tinymce/latest/quickbars/) for this floating toolbar plugin.
Open a Problem component, both in a library and in a course. Set answers, feedback, and hints. Check that the …
> Fix problem input [FC-0076]

- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- Updates the height of the Advanced Editor.
- Which edX user roles will this change impact? "Course Author"
- Related to https://github.com/openedx/edx-platform/pull/36221
- Internal ticket: [FAL-4040](https://tasks.opencraft.com/browse/FAL-4040)
- Go to a course. Go to Advanced settings
- Add the following in Advanced module list:
```
[
"done",
"google-calendar",
"google-document",
"pdf",
]
```
- Install the [PDF plugging](https://github.com/open-craft/xblock-pdf.git@v1.1.0#egg=xblock-pdf) 
- Create and copy a completion block 
- Go to the library home of a library. Paste the block.
- Open the Editor. Verify the style, and verify that the text does not overlap with the close button.
- Also verify that the editor has a good size.
- Also verify that the Save and Cancel buttons are on the …
> fix: Height in Advanced Editor [FC-0076]

- src/optimizer-page/messages.js
Update display string for Course Optimizer Scanning Step
> refactor: Update message for Scan completion in Course Optimizer page

- src/constants.js
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/constants.js
- src/course-unit/data/thunk.js
- src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
- src/course-unit/xblock-container-iframe/hooks/types.ts
- src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
- src/course-unit/xblock-container-iframe/index.tsx
- src/course-unit/xblock-container-iframe/messages.ts
- src/course-unit/xblock-container-iframe/utils.ts
- src/generic/modal-iframe/ModalIframe.test.tsx
- src/generic/modal-iframe/index.scss
- src/generic/modal-iframe/index.tsx
- src/generic/saving-error-alert/SavingErrorAlert.jsx
- src/generic/styles.scss
🚨 **Dependencies:**
- 🔗 [edx-plarform PR](https://github.com/openedx/edx-platform/pull/35777)
This PR  includes adding new message types, updating message handlers, and implementing a new modal iframe for legacy XBlock editing.
The next PR will be adding post messages for the tagging functionality.
https://github.com/user-attachments/assets/94061120-d85b-4930-9689-d6138a1951d4
**Settings**
```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: Peter_Kulko/advanced_blocks_edit_and_move_modals
TUTOR_GROVE_NEW_MFES:
authoring:
port: 18000
repository: https://github.com/raccoongang/frontend-app-course-authoring.git
version: Peter_Kulko/edit-modal-for-advanced-xblocks …
```
> feat: [FC-0070] handled edit modals from advanced xblocks

- src/editors/AdvancedEditor.test.tsx
- src/editors/AdvancedEditor.tsx
- src/editors/containers/EditorContainer/components/CancelConfirmModal.tsx
- src/editors/containers/EditorContainer/index.tsx
- Extracts the cancel confirmation modal as a new component.
- Adds the cancel confirmation modal to the Advanced editors in libraries.
- Which edX user roles will this change impact? Common user roles are "Course Author"
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1669
- Internal ticket: [FAL-4091](https://tasks.opencraft.com/browse/FAL-4091)
- Go to the library home of a library.
- Create a new Drag an drop block.
- Open the editor.
- Click on cancel or outside of the modal. Verify that the cancel confirmation modals appear.
- Follow the testing instructions of https://github.com/openedx/frontend-app-authoring/pull/1649#issue-2831593180 to enable more blocks to tests.
N/A
> feat: Add cancel confirmation modal to Advanced editors in libraries [FC-0076]

- src/import-page/file-section/FileSection.jsx
This PR addresses the issue where the `Dropzone` component was too large, obstructing the view of the course import status. The height of the `Dropzone` has been adjusted to 200 pixels to ensure that users can see more information about the course import status while importing a course.
- Adjusted the height of the `Dropzone` component to 200 pixels.
- **Improved Visibility**: Users can now see more information about the course import status while importing a course without scrolling.
- **Enhanced User Experience**: The reduced height of the `Dropzone` ensures that important information is not obstructed.
- Our UI/UX team member ensured that the course import status is more visible during the import process.
- [Issue #1387](https://github.com/openedx/frontend-app-authoring/issues/1387): …
> fix: Adjust course import dropzone height to make course import status visible 

- src/optimizer-page/data/constants.ts
- [TNL-11886](https://2u-internal.atlassian.net/browse/TNL-11886)
- Corrected LINK_CHECK_STATUSES.IN_PROGRESS value that is sent by backend. As aligned with backend, it should be [this](https://github.com/openedx/django-user-tasks/blob/13182d5ff3c6165f7f3e7955c58cdfdd7e2d6444/user_tasks/models.py#L43).
> [TNL-11886] Fix: Resolve Course Optimizer Scanning Bug

- package-lock.json
- package.json
We are temporarily re-introducing the Maintenance link, as the Maintenance Announcements tool is still in use, as discussed on: openedx/edx-platform#35852
There are no other significant changes in this version bump: https://github.com/openedx/frontend-component-header/compare/v5.8.0...v5.8.3
Related PRs:
* https://github.com/openedx/frontend-component-header/pull/565
* https://github.com/openedx/edx-platform/pull/36107
This will be reversed (that is: we will re-remove the Maintenance link) before Ulmo, via:
* https://github.com/openedx/edx-platform/issues/36263
> fix: Upgrade header, temporarily re-introducing Maintenance link

- src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
- src/editors/containers/ProblemEditor/data/OLXParser.js
- src/editors/containers/ProblemEditor/data/OLXParser.test.js
- src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
Fix for https://github.com/openedx/frontend-app-authoring/issues/1460
* Error while saving a text problem without entering second answer text box.
* In text input problem, if we enter feedback to second or third answer (incorrect) field, the feedback is moved to previous answer, i.e. feedbacks shift up by 1.
* To test this issue, checkout the first commit in this PR.
* Part of https://github.com/openedx/frontend-app-authoring/issues/1460
* `Private-ref`: [FAL-4087](https://tasks.opencraft.com/browse/FAL-4087)
* Follow instructions in https://github.com/openedx/frontend-app-authoring/issues/1460 and verify that editors do not default to advanced editor.
* And verify the above listed issues are also fixed
Found one more issue but did not fix it as part of this PR:
If incorrect answers are …
> fix: parsing text input problems

- src/library-authoring/component-info/ComponentPreview.tsx
This PR changes the `PreviewComponent` modal size from the default `"md"` to `"xl"`.
Related to https://github.com/openedx/frontend-app-authoring/issues/1343
Open the component preview modal using the "Expand" button on the component sidebar and check the width before and after this PR.
**Settings**
```yaml
TUTOR_GROVE_ADDITIONAL_DOMAINS:
- domain: meilisearch.{{ LMS_HOST }}
```
___
Private ref: [FAL-3991](https://tasks.opencraft.com/browse/FAL-3991)
> fix: change ComponentPreview modal size to xl [FC-0076]

- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
Backports the bugfixes from https://github.com/openedx/frontend-app-authoring/pull/1646 to Sumac.
* Backports fixes for https://github.com/openedx/frontend-app-authoring/issues/1637 + 
https://github.com/openedx/frontend-app-authoring/issues/1636
* Private-ref: [FAL-4085](https://tasks.opencraft.com/browse/FAL-4085)
* Run this branch in your sumac tutor devstack.
* Follow instructions on https://github.com/openedx/frontend-app-authoring/pull/1646 to test these changes.
See notes below.
1. [Sumac doesn't support adding images to content library blocks](https://github.com/openedx/frontend-app-authoring/blob/open-release/sumac.master/src/editors/sharedComponents/TinyMceWidget/pluginConfig.js#L9), and so the tinymce `image` button will not show in any of the editors.
Partial support for …
> [sumac] fix: bugs with ExpandableTextArea toolbars & modals in problem editor [FC-0076]

- src/CourseAuthoringRoutes.jsx
- src/content-tags-drawer/data/apiHooks.jsx
- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/constants.js
- src/course-unit/context/hooks.tsx
- src/course-unit/hooks.jsx
- src/course-unit/hooks.test.jsx
- src/course-unit/xblock-container-iframe/hooks/types.ts
- src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
- src/course-unit/xblock-container-iframe/index.tsx
🚨 **Dependencies:**
- 🔗 [edx-plarform PR](https://github.com/openedx/edx-platform/pull/35751)
Added interaction between MFE and Legacy tagging functionality for xblocks on the Course unit page.
- fixed problem with scrolling after creating a new xblock with a new editor (https://github.com/openedx/edx-platform/pull/35777#pullrequestreview-2631007078)
https://github.com/user-attachments/assets/a2db1457-24d6-4d3f-8c84-22c8f50dfecd
**Settings**
```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: Peter_Kulko/manage-tags-interoperation-between-mfe-and-Studio-xBlock-View
TUTOR_GROVE_NEW_MFES:
authoring:
port: 18000
repository: https://github.com/raccoongang/frontend-app-course-authoring.git
version: …
```
> feat: [FC-0070] Manage Tags interoperation

- src/generic/configure-modal/ConfigureModal.jsx
1. In Studio create course -> on Course outline page add Section and Subsection
2. Click on three dots button for Subsections -> click on Configure
3. Set empty **Release date**, save changes
4. Watch the CMS logs:
```
2024-11-01 14:03:24,129 ERROR 403 [django.request] [user None] [ip None] log.py:241 - Internal Server Error: /xblock/outline/block-v1:RG+dimilitydiadimiljitydiadifnkffffffffffffffffffjkkkkkhhjllkn+2024+type@chapter+block@d51c801024ba44b8ac784375f6648723
Traceback (most recent call last):
File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
^^^^^^^^^^^^^^^^^^^^^
File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = …
```
> fix: 500 error after saving empty subsection release date

- src/course-outline/hooks.jsx
When you re-run a course:
You see this notification:
If you click the "Dismiss" button, in the "Network" tab of your browser dev tools you can see this:
This `DELETE` request has no effect, because needs to be sent to Studio instead. If you re-load the page - the notification will still be there.
This PR fixes this by prefixing [notification_dismiss_url](https://github.com/openedx/edx-platform/blob/838977a8f3981be491a7fa2441724e4e6e92d895/cms/djangoapps/contentstore/utils.py#L1916-L1922) that we get from the backend with the Studio base URL. 
A dismissed notification shouldn't re-appear after page reload.
[internal reference](https://tasks.opencraft.com/browse/BB-9234)
> fix: broken re-run notification dismiss

- src/editors/sharedComponents/ImageUploadModal/ImageSettingsModal/hooks.js
- src/editors/sharedComponents/ImageUploadModal/ImageSettingsModal/hooks.test.js
When content creators include double quotation marks (") in the Alt Text field using the Visual Editor, the text is truncated at the first occurrence of a double quote.
For example, inserting: `The “Submit For Grading” button is located on the right side of the bar.`
Results in: `The` as alt text
Although the text appears correct after saving, reopening the Edit Image Settings reveals that the Alt Text was actually cut off. Upon inspecting the HTML source, the <img> tag is rendered incorrectly:
```
alt="The " submit="" for="" grading="" icon="" is="" located="" on="" the="" right="" side="" of="" bar="" 
width="595" height="90">
```
This PR resolves the above mentioned issue.
- [JIRA Link](https://2u-internal.atlassian.net/browse/TNL-11864)
- Which edX user …
> [TNL-11864] fix: Prevent Alt Text from Being Truncated Due to Double Quotation Marks

- src/course-unit/CourseUnit.jsx
- src/generic/clipboard/paste-component/index.tsx
#1700 included a bug that broke the "Paste Component" feature on the new Unit Outline (and the positioning of the "What is on the clipboard" popover).
This PR fixes it.
- Open a Unit
- Copy a Component
- Paste this component and check the results
> fix: paste button on unit outline

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/search-manager/FilterByPublished.tsx
- src/search-manager/SearchManager.ts
This is a fix for https://github.com/openedx/frontend-app-authoring/issues/1484#issuecomment-2654634014
- Which edX user roles will this change impact? Common user roles are "Course Author".
GitHub issue: https://github.com/openedx/frontend-app-authoring/issues/1484
Internal link: [FAL-4100](https://tasks.opencraft.com/browse/FAL-4100)
- Create two components and publish both (published)
- Create two components and publish both and make changes to both (published with changes)
- Create four components, avoid publishing (never published)
- Change `Sory By` to `Recently Published`. 
- Verify that the `Publish status` filter doesn't change.
- Verify that the published and published with changes components are ordered by published date. Verify that the …
> refactor: Separate Publish order sort from publish filter [FC-0076]

- src/generic/configure-modal/ConfigureModal.jsx
- src/generic/configure-modal/VisibilityTab.jsx
- src/generic/configure-modal/messages.js
This PR fixes the message displayed in the `Subsection visibility` section of the `Configure` modal within the studio Course Outline when a course is either `isSelfPaced` or not.
- https://github.com/openedx/frontend-app-authoring/issues/1020
- https://github.com/eduNEXT/consulting-issues-mapping/issues/156
- Mount this MFE using this PR's branch
- Access to a course in the Studio
- Go to `Schedule & details`, change the date to a future date, and test changing `Course Pacing` among the two options
- After changing the `Course Pacing` go to the outline, click the three dots of a subsection, click in `Configure` and then in `Visibility`
- You should watch:
``` MD
`Hide content after end date
After the course's end date has passed, learners can no longer access its content. The subsection …
```
> fix: render proper visibility message on self-paced course type

- src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
- src/editors/containers/ProblemEditor/data/SettingsParser.js
**Issue:** The "Show Answer" feature was not appearing in certain problem components because an empty string ("") was being sent to the backend instead of the default value.
**Fix:** The issue was resolved by updating the populateItem function to ensure that when an item's value is null or an empty string (""), it correctly falls back to defaultValue.
[TNL-11844](https://2u-internal.atlassian.net/browse/TNL-11844?atlOrigin=eyJpIjoiYmZmOGQ5NTQ2ZGQ4NGRiODg5NjY1ZTVlYmQwYmEwMWYiLCJwIjoiaiJ9)
- Open the course in Studio.
- Go to Advanced Settings.
- Set the Show Answer default value to "Show answer" and save.
- Open or create a problem in the course.
- Do not manually update the Show Answer field.
- Save the problem and check if the Show Answer field automatically applies the default value. …
> Use defaultValue when item is null or empty

- src/library-authoring/component-info/ComponentInfo.test.tsx
- src/library-authoring/component-info/ComponentInfo.tsx
- src/library-authoring/component-info/ComponentUsage.tsx
- src/library-authoring/components/PublishConfirmationModal.tsx
- src/library-authoring/components/messages.ts
- src/library-authoring/data/api.mocks.ts
- Add Publish confirmation modal
- Which edX user roles will this change impact? "Course Author".
- Github link: https://github.com/openedx/frontend-app-authoring/issues/1188
- Internal ticket: [FAL-4084](https://tasks.opencraft.com/browse/FAL-4084)
- Go to a library home of a library
- Create a component
- Publish. Verify the new publish state of the modal
- Make changes in the component
- Publish. Verify that the modal shows "This component is not used in any course."
- Add the component to one or two courses
- Make changes in the component
- Publish. Verify that the modal shows the courses.
N/A
> feat: Add Publish confirmation modal [FC-0076]

- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.js
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.test.js
- src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.test.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
- src/editors/data/redux/problem/reducers.test.ts
- src/editors/data/redux/problem/reducers.ts
- src/editors/sharedComponents/ExpandableTextArea/__snapshots__/index.test.jsx.snap
- src/editors/sharedComponents/ExpandableTextArea/index.jsx
- src/editors/sharedComponents/ExpandableTextArea/index.scss
- src/editors/sharedComponents/ExpandableTextArea/index.test.jsx
- src/editors/sharedComponents/TinyMceWidget/hooks.js
- src/editors/sharedComponents/TinyMceWidget/hooks.test.js
- src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
Fix images in single and multi select problems in libraries. Found following issues and fixed them:
* Images were not being rendered in any of the fields in these problems.
* Base url was not being set which is used by tinymce to load images with relative path.
* Answer fields were set to inline mode which does not initialize images or base paths as described in [docs](https://www.tiny.cloud/docs/tinymce/latest/inline-editor-options/#inline).
* If same image twice is used twice in a problem, the logic of replacing `static/image.jpg` with `/static/image.jpg` would replace the first occurrence twice resulting in `//static/image.jpg`, breaking both the links.
* On initialization of answer fields, the absolute static asset urls were being replaced by relative urls causing the editor being set …
> fix: image rendering in single and multi select problems [FC-0076]

- src/index.jsx
This backports the `staleTime` parameter to avoid excessive backend calls.
- More info here (https://github.com/openedx/frontend-app-authoring/pull/1723#issuecomment-2719156375)
- Open a Course Outline
- Check that we have one (and only one) call to http://studio.local.openedx.io:8001/api/content-staging/v1/clipboard/
- Open and close some sections (exposing the Unit card)
- Check that no additional calls to the endpoint are made
> perf: add staleTime to queryClient to avoid excessive calls [sumac]

- src/generic/alert-error/AlertError.test.tsx
- src/generic/alert-error/index.tsx
- src/generic/alert-error/messages.ts
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/create-library/CreateLibrary.test.tsx
- src/taxonomy/TaxonomyLayout.test.tsx
- src/taxonomy/TaxonomyLayout.tsx
- src/taxonomy/TaxonomyListPage.test.tsx
- src/taxonomy/common/context.ts
- src/taxonomy/import-tags/ImportTagsWizard.jsx
- src/taxonomy/import-tags/ImportTagsWizard.test.jsx
- src/taxonomy/messages.ts
- src/taxonomy/taxonomy-menu/TaxonomyMenu.test.tsx
This PR adds the error information when we have a failure while importing a Taxonomy.
- Related to: https://github.com/openedx/frontend-app-authoring/issues/1671
- Open the Taxonomy page
- Try to import a file with an invalid format (i.e. a json with empty/invalid content)
- Check the error message
___
Private ref: [FAL-4093](https://tasks.opencraft.com/browse/FAL-4093)
> fix: show error information when taxonomy import fails [FC-0076]

- src/course-libraries/CourseLibraries.test.tsx
- src/course-libraries/CourseLibraries.tsx
**Description**: Open review tab in course libraries page of any component is out of sync.
**Related to:** https://github.com/openedx/frontend-app-authoring/issues/1565#issuecomment-2731000745
`Private-ref`: [FAL-4006](https://tasks.opencraft.com/browse/FAL-4006)
**Test instructions**: Open `Libraries` page in any course and verify that the review tab is selected by default if components are out of sync
> refactor: open review tab in course libraries if out of sync [FC-0076]

- src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
- src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
- src/editors/containers/ProblemEditor/data/OLXParser.js
- src/editors/data/redux/thunkActions/problem.ts
edx-platform would pass a default_to_advanced flag in through the REST API, depending on the value of a waffle flag.
The flag did not actually cause anything to default to advanced. What it actually did was switch from getOLXParser to getBetaOLXParser. However, getBetaOLXParser was never implemented--it just logs a console warning and return getOLXParser.
We remove this unused flag and unused function. The underlying default_to_advanced API flag and the backing waffle flag will be removed from edx-platform in a separate PR.
This essentially reverts https://github.com/openedx-unsupported/frontend-lib-content-components/pull/496
> refactor: Remove unused defaultToAdvanced and getBetaParsedOLXData

- src/course-libraries/CourseLibraries.test.tsx
- src/course-libraries/OutOfSyncAlert.tsx
Clicking review button on out of sync alert should not dismiss the alert
and it should be displayed again in outline or all tab.
**Related to:** https://github.com/openedx/frontend-app-authoring/issues/1566#issuecomment-2737700011
**Private-ref:** [FAL-4007](https://tasks.opencraft.com/browse/FAL-4007)
**Test instructions:**
Verify the out of sync alert is not dismissed on clicking review, i.e., it is displayed again in outline and all tab even after clicking review button.
Only dismiss button should dismiss the alert and not display it until the out of sync count changes.
> refactor: don't dismiss out of sync alert on review [FC-0076]

- src/editors/Editor.tsx
- src/editors/VideoSelector.jsx
- src/editors/VideoSelector.test.jsx
- src/editors/hooks.test.jsx
- src/editors/hooks.ts
Data from previous editor instance was being processed by current editor instance and sometimes failed due to mismatch. For example, editing text editor or any other basic editor after opening an advanced problem like drag-n-drop crashed. Now the editor is only rendered after the initialization process is complete.
- Which edX user roles will this change impact?: "Course Author", "Developer", and "Operator".
* Related to: https://github.com/openedx/frontend-app-authoring/issues/1668
* `Private-ref`: [FAL-4090](https://tasks.opencraft.com/browse/FAL-4090)
* Follow instructions in the issue: https://github.com/openedx/frontend-app-authoring/issues/1668 and verify that the issue is fixed.
Include anything else that will help reviewers and consumers understand …
> fix: prevent editor from loading twice before initialization

- src/editors/containers/VideoEditor/components/VideoEditorModal.test.tsx
- src/editors/containers/VideoEditor/components/VideoEditorModal.tsx
The call to [dispatch(thunkActions.video.loadVideoData(selectedVideoId, selectedVideoUrl));](https://github.com/openedx/frontend-app-authoring/blob/9e65424ca6db32f515f5570c27e54d7e0b5cffc4/src/editors/containers/VideoEditor/components/VideoEditorModal.tsx#L17) relies on selectors.app.videos(state) to return the list of available videos. However, when a course contains many videos, this selector sometimes returns an empty list initially. As a result, the check for selectedVideoId fails because the video list is unavailable at dispatch time, preventing the Video ID field from being populated on the editor/video page. This causes an attempt to load video data before the list is fully available.
To ensure loadVideoData is called when the video list becomes available, this PR introduces a …
> Fix video ID not populating issue

- src/optimizer-page/CourseOptimizerPage.test.js
- src/optimizer-page/scan-results/BrokenLinkTable.tsx
Ticket: [TNL-11930](https://2u-internal.atlassian.net/browse/TNL-11930)
In this PR, fix link navigation in BrokenLinkHref and GoToBlock components
- Updated BrokenLinkHref to prevent default anchor behavior and open broken links directly in a new tab.
- Updated GoToBlock to prevent default anchor behavior and open block URLs directly in a new tab.
- Added test coverage for this fix code in `CourseOptimizerPage.test.js`, this was needed to be covered: https://github.com/openedx/frontend-app-authoring/pull/1760/checks?check_run_id=39390124321
Previous Behavior (links were very briefly going to “about: blank” url before directing to the given website):
https://github.com/user-attachments/assets/d18fb773-bb6d-4293-aa62-6925ee966476
Current Behavior after fix (It doesn't load `about: blank` …
> fix: link navigation for BrokenLink and GoToBlock

- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/data/thunks.js
##Description
**Issue:**
The video upload modal dialog does not display upload progress when a video is being uploaded.
**Before fix:**
**Fix:**
Refactored handleAddFile to update uploadingIdsRef before dispatching addVideoFile.
[TNL-11940](https://2u-internal.atlassian.net/browse/TNL-11940)
1. Navigate to the Videos page.
2. Ensure there are no existing videos.
3. Upload a new video.
4. Verify that the upload progress is now correctly displayed in the modal dialog.
> Update useRef before dispatching file upload action

- src/generic/block-type-utils/constants.ts
- src/generic/key-utils.test.ts
- src/generic/key-utils.ts
- src/generic/loading-button/LoadingButton.test.tsx
- src/generic/loading-button/index.tsx
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryLayout.tsx
- src/library-authoring/add-content/AddContentContainer.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/common/context/LibraryContext.tsx
- src/library-authoring/create-collection/messages.ts
- src/library-authoring/create-library/CreateLibrary.tsx
- src/library-authoring/create-unit/CreateUnitModal.tsx
- src/library-authoring/create-unit/index.tsx
- src/library-authoring/create-unit/messages.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.ts
This PR implements the basic workflow to create a Unit in a Library.
- Implements https://github.com/openedx/frontend-app-authoring/issues/1595
- Depends on: https://github.com/openedx/edx-platform/pull/36371
1. Make sure you are using this PR with openedx/edx-platform#36371
2. Open a library
3. Click on the "+ New" button on the Library Header
4. Select "Unit"
5. . You should see the new Unit in the component list
*Note*: The card view for the Unit has not been implemented yet, so interacting with this new Unit card will raise many errors as it is being handled as an ordinary Library Component.
___
Private ref: [FAL-4056](https://tasks.opencraft.com/browse/FAL-4056)
> feat: create unit on libraries workflow [FC-0083]

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/LibraryLayout.tsx
- src/library-authoring/__mocks__/library-search.json
- src/library-authoring/messages.ts
- src/library-authoring/routes.test.tsx
- src/library-authoring/routes.ts
This PR implements the "Units" tab on the Library Authoring.
- Implements https://github.com/openedx/frontend-app-authoring/issues/1610
- Depends on https://github.com/openedx/frontend-app-authoring/pull/1742
- Open a library with some Units
- Navigate through the unit tab
-  Check the URL change and the selection filter
- Use multiple filters and check if the result is consistent
___
Private ref:
[FAL-4055](https://tasks.opencraft.com/browse/FAL-4055)
> feat: library units tab [FC-0083]

- src/header/messages.js
Ticket: [TNL-11945](https://2u-internal.atlassian.net/browse/TNL-11945)
In this PR rename `Optimize Course` to `Course Optimizer`
**Before:**
**After:**
> [TNL-11945] chore: rename course optimizer name in dropdown

- src/optimizer-page/scan-results/ScanResults.scss
- src/optimizer-page/scan-results/ScanResults.tsx
- src/optimizer-page/scan-results/SectionCollapsible.tsx
- src/optimizer-page/scan-results/messages.js
- src/optimizer-page/utils.test.js
- src/optimizer-page/utils.ts
Ticket: [TNL-11936](https://2u-internal.atlassian.net/browse/TNL-11936)
Currently, course sections display "0 broken links" and "0 locked links," which can be misleading. Users only discover that a manual check is required after expanding the section. This PR adds manual check count to the collapsed view.
**Before:**
**After:**
> [TNL-11936] feat: add manual check count to collapsed view

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/LibraryLayout.tsx
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/common/context/LibraryContext.tsx
- src/library-authoring/common/context/SidebarContext.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/containers/ContainerInfoHeader.test.tsx
- src/library-authoring/containers/ContainerInfoHeader.tsx
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/containers/index.tsx
- src/library-authoring/containers/messages.ts
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/library-sidebar/LibrarySidebar.tsx
- src/library-authoring/routes.test.tsx
- src/library-authoring/routes.ts
This PR implements the placeholder for the Unit Sidebar.
Implements https://github.com/openedx/frontend-app-authoring/issues/1617
Depends on https://github.com/openedx/frontend-app-authoring/pull/1754
- Open a library with some units
- Click on the unit and check that the sidebar opens
- Copy the URL with the sidebar open and reload, to check if the sidebar is open correctly
- Do the same using the `Units` tab
- Also, check that you can rename the units using the sidebar
__
Private ref: [FAL-4050](https://tasks.opencraft.com/browse/FAL-4050)
> feat: library unit sidebar [FC-0083]

- src/course-unit/add-component/messages.js
With the transition to docs.openedx.org, update links to docs.edx.org to the community-supported site.
> docs: Update references to docs.edx.org

- src/editors/sharedComponents/CodeEditor/hooks.js
- src/editors/sharedComponents/CodeEditor/index.test.jsx
Ticket: [TNL-11920](https://2u-internal.atlassian.net/browse/TNL-11920)
- Ignore altText to avoid replacing &quot; with "(double quotes) in alt text value.
- Modify unit tests to cover the new code.
**Before:**
After saving the text in source code editor:
**After:**
After saving the text in source code editor(It will remain same, but it will look like in below pic and keep showing the `&quot;` in source code editor):
e code editor:
> fix: ignore altText to avoid replace &quot; with "

- plugins/course-apps/teams/Settings.jsx
This PR adds a missing property (`userPartitionId`) when updating the groups config. If this property is not sent, the backend generates a new user partition ID, breaking all previous configurations.
- https://github.com/openedx/frontend-app-authoring/issues/1719
1. Using Tutor, create a mount of this MFE with the changes in this PR's branch.
2. Create a Waffle Flag for your course in `{lms_domain}/admin/waffle_utils/waffleflagcourseoverridemodel/`
- Waffle Flag: `teams.content_groups_for_teams`
- Course id: [Your Course ID]
- Enabled: ✅ 
3. Enables Teams in the platform using the `teams.enable_teams_app` flag.
4. Enable teams for your course in **Studio > [Your Course] > Content > Pages & Resources > Teams > Teams toggle**
5. In the same modal of **Configure teams**, create a few …
> fix: add user partition id when update groups

- src/course-outline/CourseOutline.test.jsx
- src/course-outline/subsection-card/SubsectionCard.test.jsx
- src/course-outline/unit-card/UnitCard.test.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
- src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
- src/generic/clipboard/hooks/useClipboard.test.tsx
- src/generic/clipboard/hooks/useClipboard.ts
- src/generic/data/api.mock.ts
- src/generic/hooks/tests/hooks.test.tsx
- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/LibraryContent.test.tsx
- src/library-authoring/add-content/AddContent.test.tsx
- src/library-authoring/add-content/AddContentWorkflow.test.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/component-info/ComponentInfo.test.tsx
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/units/LibraryUnitPage.test.tsx
When working on clipboard enhancements for containers, I noticed bugs with almost all of the "Copy to clipboard" actions in the MFE. They would work, but report an error that they failed, because the broadcast channel was closed.
Before:
After:
Open library content and/or courses in the Authoring MFE. Try copying XBlocks or Units. 
Make sure the sync among tabs is still working.
Private ref: Part of [FAL-4067](https://tasks.opencraft.com/browse/FAL-4067)
> fix: Copy to clipboard would seemingly fail even if it worked [FC-0083]

- src/editors/AdvancedEditor.tsx
- src/library-authoring/LibraryBlock/LibraryBlock.tsx
- src/library-authoring/component-comparison/CompareChangesWidget.tsx
- src/library-authoring/component-info/ComponentPreview.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
Sets minimum height of library block previews based on its render
location and block type.
Ref: https://github.com/openedx/edx-platform/pull/36477#issuecomment-2797616975
`Private-ref`: https://tasks.opencraft.com/browse/FAL-4049
<details>
<summary>
Screenshots:
</summary>
**With large fixed size min-height, all blocks in unit page look big**
**After:**
</details>
> fix: auto adjust min height of xblock previews [FC-0083]

- src/library-authoring/add-content/AddContent.tsx
Alphabetically sorts the blocks listed under "Advanced / Other" by default display name.
This is a minor change affecting Library Authors.
Resolves: https://github.com/openedx/frontend-app-authoring/issues/1513#issuecomment-2715841482
Private-ref: [FAL-4119](https://tasks.opencraft.com/browse/FAL-4119)
1. Install some extra XBlocks to appear in the "Advanced / Other" list, e.g. [in-video-quiz](https://github.com/openedx/xblock-in-video-quiz) or [freetextresponse](https://github.com/openedx/xblock-free-text-response). The installed XBlocks must have a `display_name` property and be listed in [`settings.LIBRARY_ENABLED_BLOCKS`](https://github.com/openedx/edx-platform/blob/694bf77993bf0d209301d907be0ece89bb71282a/cms/envs/common.py#L2907).
```
tutor dev exec cms …
```
> fix: sort Advanced Blocks by default display name [FC-0076]

- src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
- src/generic/inplace-text-editor/index.tsx
- src/generic/inplace-text-editor/messages.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/collections/CollectionInfoHeader.test.tsx
- src/library-authoring/collections/CollectionInfoHeader.tsx
- src/library-authoring/collections/messages.ts
- src/library-authoring/component-info/ComponentInfoHeader.test.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/component-info/messages.ts
- src/library-authoring/containers/ContainerInfoHeader.test.tsx
- src/library-authoring/containers/ContainerInfoHeader.tsx
- src/library-authoring/containers/messages.ts
- src/library-authoring/units/LibraryUnitPage.test.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
- src/library-authoring/units/messages.ts
This PR adds a feature to allow renaming the Unit in the new Unit Page
Also, introduces a new `InplaceTextEditor` to reuse code related to this feature.
- Implements part of https://github.com/openedx/frontend-app-authoring/issues/1624
- Open a Unit Page
- Click on the Unit name on the header
- Change the Unit name and click Enter
- Check if the unit was renamed
- Try renaming a Unit, a Component, and a Collection using the Sidebar to ensure it works correctly.
___
Private ref: [FAL-4063](https://tasks.opencraft.com/browse/FAL-4063)
> feat: rename unit in LibraryUnitPage [FC-0083]

- src/library-authoring/add-content/AddContent.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.tsx
- src/library-authoring/add-content/index.ts
- src/library-authoring/add-content/messages.ts
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
This PR allows adding existing components to units
- Implements https://github.com/openedx/frontend-app-authoring/issues/1620
- Depends on https://github.com/openedx/frontend-app-authoring/pull/1784
- Go to the library home of a library.
- Create a Unit.
- Open the Unit page of the new unit.
- Click on Add content button.
- Click on "Existing Library Content"
- Select some components and click on "Add to Unit"
-  Verify that the blocks are added to the unit
Note: Before merging https://github.com/openedx/frontend-app-authoring/pull/1797 you may see another Units on the component picker
___
Private ref: [FAL-4059](https://tasks.opencraft.com/browse/FAL-4059)
> feat: add existing components to unit [FC-0083]

- src/__mocks__/clipboardSubsection.js
- src/__mocks__/index.js
- src/generic/clipboard/hooks/useClipboard.test.tsx
- src/library-authoring/add-content/AddContent.test.tsx
- src/library-authoring/add-content/AddContent.tsx
- src/library-authoring/data/api.mocks.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.test.tsx
This PR allows pasting units from a course into a content library. The child XBlocks and the unit will be pasted into the library.
Depends on https://github.com/openedx/edx-platform/pull/36516
Note that if https://github.com/openedx/frontend-app-authoring/pull/1800 is not merged, you may see fake errors when copying.
Implemented as part of https://github.com/openedx/frontend-app-authoring/issues/1647 which turned out to be too complex so I started with the reverse.
Go to a course, copy a unit, then test pasting that unit into both courses and libraries.
| Copied Unit | Pasted Unit |
|-----|-----|
| ![Screenshot](https://github.com/user-attachments/assets/168e5b44-222b-41bc-bee0-9fe59710d867) | ![Screenshot](https://github.com/user-attachments/assets/1d95d0ad-e16a-438e-b7a1-1952967a1911) | …
> feat: allow pasting units from a course into a library

- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/ComponentMenu.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/components/index.ts
- src/library-authoring/components/messages.ts
- src/library-authoring/data/api.test.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/units/LibraryUnitPage.test.tsx
- Users can remove a component from a unit
- The component is NOT deleted, and remains present in the library
- A toast shows that the component was removed, and allows the user to undo
- Overflow menu item appears in sidebar for selected components in unit
- Overflow menu item appears directly on components in full page unit view
- Which edX user roles will this change impact?  "Course Author".
- Github link: https://github.com/openedx/frontend-app-authoring/issues/1622
- Internal ticket: [FAL-4061](https://tasks.opencraft.com/browse/FAL-4061)
- Go to the library home of a unit
- Create a unit
- Open the unit
- Add some new components to the unit
- Remove a component using the menu in the component card
- Remove a component using the menu in the component sidebar.
N/A
> feat: Remove component from unit [FC-0083]

- src/files-and-videos/files-page/factories/mockApiResponses.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/videos-page/data/slice.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
Ticket: [TNL-11637](https://2u-internal.atlassian.net/browse/TNL-11637)
This PR fixes toggle behavior for video and file view.
- Before:
- The default view was card. And The videos and files both pages were sharing same variable & default view.
- Whenever user selects list view on videos/files page and redirects to another page, the toggle/view shifts again to default(card) view whenever it returns to videos/files page.
- After:
- The default view is list now. And The videos and files both pages can have different state & default view.
- Whenever user selects card view on videos/files page and redirects to another page, the toggle/view remain same whatever user had selected before when it returns to videos/files page.
https://github.com/user-attachments/assets/fd47d24f-35cb-42af-b549-7dd09 …
> fix: toggle behavior for video & file view

- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/containers/messages.ts
- src/library-authoring/data/api.ts
- src/library-authoring/data/apiHooks.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
Implements a _minimal_ version of https://github.com/openedx/frontend-app-authoring/issues/1627
Depends on https://github.com/openedx/edx-platform/pull/36543
Private ref [FAL-4069](https://tasks.opencraft.com/browse/FAL-4069)
1. Check out this PR and the required edx-platform PR.
2. Create or paste a unit that contains multiple components (xblocks).
3. Click on the new "Publish" button for that unit. (Note: there is no confirmation dialog.)
a. Verify that the toast is shown:
b. Verify that the "Draft" badges on the preview have disappeared:
c. Verify that the "Unpublished Changes" badges in the search results have disappeared:
4. Make changes to a component that's in the the unit. Verify that both it and the unit now show "Unpublished Changesj" again.
**When a unit is selected in the …
> feat: button to publish a container [FC-0083]

- src/pages-and-resources/pages/PageSettingButton.jsx
- src/pages-and-resources/pages/PageSettingButton.test.jsx
Getting TypeError: r is not a function, when clicked on custom pages or textbooks arrow buttons in pages and resources.
Replace Link with navigate.
> fix: use navigate instead of Link from react-dom

- src/library-authoring/data/apiHooks.ts
This just simplifies how API methods are imported into one `apiHooks.ts` file, reducing the overall lines of code and chance for conflicts. Since we're importing all the API methods anyways, there is nothing to gain from explicitly importing each one separately.
Private ref: drive-by while working on FAL-4145
> chore: simplify imports in library-authoring/data/apiHooks.ts

- .env
- .env.test
- src/library-authoring/add-content/AddContent.test.tsx
- Enables ORA2 blocks in libraries by default
- Which edX user roles will this change impact? "Course Author"
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1512
- Internal ticket: [FAL-3992](https://tasks.opencraft.com/browse/FAL-3992)
- Verify that the tests covers the new code.
- Go to the library home of a library.
- Verify that you can create and edit ORA2
N/A
> chore: Enable ora2 in libraries by default [FC-0076]

- src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
- src/generic/inplace-text-editor/index.tsx
- src/library-authoring/collections/CollectionInfoHeader.tsx
- src/library-authoring/component-info/ComponentInfoHeader.test.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/containers/ContainerInfoHeader.tsx
- src/library-authoring/data/apiHooks.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.test.tsx
- src/library-authoring/units/messages.ts
This PR allows renaming components inside a unit
- Implements https://github.com/openedx/frontend-app-authoring/issues/1626
- Open a Unit Page of a unit with some components
- Click on one component name and rename it
- Check if the name is updated sucessfully
- Do the same navigating using `Tab` and pressing any key to start editing the name
___
Private ref: [FAL-4065](https://tasks.opencraft.com/browse/FAL-4065)
> feat: rename component on unit page

- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/factories/mockApiResponses.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/videos-page/VideosPage.test.jsx
- src/files-and-videos/videos-page/data/slice.js
- src/files-and-videos/videos-page/factories/mockApiResponses.jsx
Ticket: [TNL-11637](https://2u-internal.atlassian.net/browse/TNL-11637)
- react redux state changes back to default whenever page refreshes.
- On course authoring mfe, whenever we redirect from one page to another, it automatically refreshes the page which react app shouldn't do.
- So, instead of managing video and file pages previously selected view in react redux, save & manage these values in localStorage. So that page refreshes doesn't bother end users.
Attaching it's previously merged related [PR](https://github.com/openedx/frontend-app-authoring/pull/1808) which was made keeping in mind to make use of react redux. But unfortunately, page is refreshing every time user redirects to another page in same MFE. Usually in react App, page switching shouldn't refresh the page.
> fix: video & file page toggles due to page refreshing in course authoring mfe

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.test.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/messages.js
- New Transcript widget state on video editors on creation workflow
- Which edX user roles will this change impact? "Course Author",
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1352#issuecomment-2807096263
- Internal ticket: [FAL-4137](https://tasks.opencraft.com/browse/FAL-4137)
- Create a new video block, on the editor verify the new state of the Transcript Widget.
- Save the video.
- Edit the video and verify the old state of the Transcript Widget
N/A
> feat: New Transcript widget state on video editors on creation workflow [FC-0076]

- package-lock.json
- package.json
- src/CourseAuthoringPage.jsx
- src/accessibility-page/AccessibilityPage.jsx
- src/course-rerun/index.jsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/collections/LibraryCollectionPage.tsx
- src/library-authoring/create-library/CreateLibrary.tsx
- src/plugin-slots/README.md
- src/plugin-slots/StudioFooterSlot/README.md
- src/studio-home/StudioHome.tsx
- src/taxonomy/TaxonomyLayout.test.tsx
- src/taxonomy/TaxonomyLayout.tsx
https://app.pr-1832-e8373e.sandboxes.opencraft.hosting/authoring/course/course-v1:demo+Course+1
> feat: import `StudioFooterSlot` from component package instead of slot package

- src/files-and-videos/videos-page/data/utils.js
Ticket: [TNL-11638](https://2u-internal.atlassian.net/browse/TNL-11638)
- fix: incorrect video durations in video info tab and  videos list view.
- Time for short videos with length less than 6 minutes was being calculated correctly. Before the value was being divided by 360 which means if any video is more than 6 minutes(360 seconds), the hours will be calculated incorrectly as shown in below before & after fix images.
So In this PR, changed `360` to `3600` to correctly calculate hour and also removed `% 60` as it will result in false calculation of hours for the video with more than `60` hours length.
Original length is also `00:07:47` minutes.
> fix: incorrect video durations

- src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.tsx
- src/content-tags-drawer/tags-sidebar-controls/index.tsx
- src/course-outline/card-header/CardHeader.jsx
- src/course-outline/card-header/CardHeader.test.jsx
- src/course-outline/unit-card/UnitCard.jsx
- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/data/thunk.js
- src/course-unit/data/utils.js
- src/course-unit/header-title/HeaderTitle.jsx
- src/course-unit/header-title/HeaderTitle.test.jsx
- src/course-unit/sidebar/PublishControls.tsx
- src/course-unit/sidebar/components/sidebar-footer/ActionButtons.tsx
- src/course-unit/sidebar/components/sidebar-footer/UnitVisibilityInfo.tsx
- src/course-unit/sidebar/components/sidebar-footer/index.tsx
- src/generic/configure-modal/ConfigureModal.jsx
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
This PR disallows edits to units in courses (including title change, children change) that are sourced from a library.
- Implements https://github.com/openedx/frontend-app-authoring/issues/1712
- Depends on https://github.com/openedx/edx-platform/pull/36558
- Open a unit that was added from a library (https://github.com/openedx/frontend-app-authoring/pull/1829)
- Checkout https://github.com/openedx/edx-platform/pull/36558
- Check that the Edit (near the title) is disabled
- Check that the "Publish" button on the sidebar is disabled
- Check that the "Manage Tags" button on the sidebar is disabled
- Check that you cannot add new blocks to the unit
- Check that you cannot change the children blocks on the unit
___
Private ref: [FAL-4112](https://tasks.opencraft.com/browse/FAL-4112)
> feat: disallow edits to units in courses that are sourced from a library

- src/course-outline/__mocks__/courseOutlineIndex.js
- src/course-outline/card-header/CardHeader.jsx
- src/course-outline/card-header/CardHeader.scss
- src/course-outline/card-header/CardHeader.test.jsx
- src/course-outline/card-header/messages.js
- src/course-outline/unit-card/UnitCard.jsx
- src/course-outline/unit-card/UnitCard.test.jsx
- src/course-unit/preview-changes/index.test.tsx
- src/course-unit/preview-changes/index.tsx
- src/library-authoring/component-comparison/CompareChangesWidget.tsx
- src/library-authoring/component-comparison/messages.ts
- Adds the sync button in unit cards in the course outline.
- Opens the compare previews.
- Functionality to sync units.
- Functionality to decline sync units.
- Which edX user roles will this change impact? "Course Author".
https://www.loom.com/share/70a14ccdb2ae487ea769be340d6ba845?sid=752e2e84-3553-4306-ad71-d21e40e4a682
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1634
- Depends on: https://github.com/open-craft/edx-platform/pull/773
- Internal ticket: [FAL-4075](https://tasks.opencraft.com/browse/FAL-4075)
- Create a unit
- Create a component and add it to the unit
- Publish the unit.
- Use this branch: https://github.com/openedx/frontend-app-authoring/pull/1829 and follow the testing instructions to add the unit to a …
> feat: Sync units in course outline [FC-0083]

- src/course-unit/header-title/HeaderTitle.jsx
- src/course-unit/header-title/HeaderTitle.test.jsx
Allows downstream course Units to update their settings.
Course Authors using Library Units are affected by this change.
* Follow-up to https://github.com/openedx/frontend-app-authoring/pull/1833/files
* Addresses [this comment](https://github.com/openedx/frontend-app-authoring/issues/1712#issuecomment-2829090892)
* Private-ref: [FAL-4112](https://tasks.opencraft.com/browse/FAL-4112)
1. Use latest edx-platform `master`, and run migrations.
2. Create a Library with a Unit in it, and Publish.
3. Create a Course, and add the Library Unit to  a Section > Subsection.
4. Browse to the Course Unit page, and edit the Settings using the cog icon. Change settings.
5. Return to the Library Unit, and update the Unit title and/or contents. Publish.
6. Return to the Course Outline, and click the "sync" …
> fix: allow units sourced from libraries to update their settings [FC-0083]

- src/course-unit/CourseUnit.jsx
- src/course-unit/CourseUnit.test.jsx
- src/course-unit/__mocks__/courseUnitIndex.js
- src/course-unit/messages.js
- Add 'This unit can only be edited from the library' banner in units that are sourced from a library
- Which edX user roles will this change impact? "Course Author".
- Create a unit and publish
- Go to the course outline of a course.
- On a subsection, click on the `Use unit from library`
- Wait to the unit page is open
- Verify the new banner.
N/A
> feat: Add 'This unit can only be edited from the library' banner in units that are sourced from a library [FC-0083]

- src/course-libraries/OutOfSyncAlert.tsx
- src/course-libraries/__mocks__/linkCourseSummary.json
Fixes a bug in the course banner that happens when `readyToSyncCount` is absent/null in the backend data.
* Closes: https://github.com/openedx/frontend-app-authoring/issues/1796
* Private-ref: [FAL-4143](https://tasks.opencraft.com/browse/FAL-4143)
I haven't figured out why this happens sometimes, so am not sure exactly how to test it manually.
But check the commits and their tests to see how:
1. [ae5e712](https://github.com/openedx/frontend-app-authoring/pull/1864/commits/ae5e71259b04eb04c7c91e01057a91d4fcdaf613) demonstrates the issue by breaking the existing test showing ["NaN library components are out of sync. Review updates to accept or ignore changes" as the banner text](https://github.com/openedx/frontend-app-authoring/actions/runs/14657161379/job/41134140206?pr=1864#step:4:222). …
> fix: NaN library components are out of sync [FC-0083]

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/messages.js
- src/course-unit/xblock-container-iframe/hooks/types.ts
- src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
- src/course-unit/xblock-container-iframe/index.tsx
- src/course-unit/xblock-container-iframe/messages.ts
- src/editors/Editor.tsx
- src/editors/EditorContext.tsx
- src/editors/EditorPage.test.tsx
- src/editors/EditorPage.tsx
- src/editors/containers/EditorContainer/index.test.tsx
- src/editors/containers/EditorContainer/index.tsx
- src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
- src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
- src/editors/containers/VideoEditor/components/VideoEditorModal.tsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
- src/editors/containers/VideoEditor/index.tsx
- src/library-authoring/components/ComponentEditorModal.tsx
Currently in libraries editing a component opens a modal without navigating into other urls, but in course units you get redirected to a new page to edit the block and then back to the unit page. 
This PRs refactors the logic so that editing components in courses opens modals instead of redirecting.. Currently it is keeping the editing urls in order to not break any other flows such as the video upload page.
Issue: https://github.com/openedx/frontend-app-authoring/issues/1644
1. make sure you are using MFE editors: `tutor dev run lms ./manage.py lms shell -c "from waffle.models import Flag; Flag.objects.update_or_create(name='contentstore.new_studio_mfe.use_new_unit_page', defaults={'everyone': True})"`
2. In any course, create components of multiple types and make sure they can be added …
> feat: display editors as modals 

- README.rst
A number of features now default to being on in edx-platform. In order to use the legacy versions of these features, legacy flags need to be set. This PR updates documentation to reflect these changes.
Follows changes made in this PR: https://github.com/openedx/edx-platform/pull/36495
> chore: update readme on legacy flags

- src/editors/sharedComponents/CodeEditor/hooks.js
**Ticket**: [TNL-11959](https://2u-internal.atlassian.net/browse/TNL-11959)
- This PR fixes the error when viewing text component in RAW HTML as `lang` was passed `undefined` and `CODEMIRROR_LANGUAGES[lang]()` was throwing this: `TypeError: Ap[i] is not a function`
> fix: Error when viewing text component in RAW HTML

- src/pages-and-resources/PagesAndResources.jsx
- src/pages-and-resources/PagesAndResources.test.jsx
- src/plugin-slots/AdditionalCourseContentPluginSlot/index.tsx
- src/plugin-slots/AdditionalCoursePluginSlot/index.tsx
A recent refactor cleaned up the Pages and Resources plugin slots but introduced an issue where the plugins were no longer being rendered
> fix: pages and resources plugins not rendered

- src/course-libraries/ReviewTabContent.tsx
Removes custom ordering code from course libraries page as it is no longer required once https://github.com/openedx/edx-platform/pull/36599 is merged.
- Which edX user roles will this change impact? None.
* Depends on: https://github.com/openedx/edx-platform/pull/36599
Verify that sorting behaviour of Review Content Updates tab in course libraries page remains unaffected.
It should sort links based on recently modified downstream components.
> refactor: remove custom order function from course libraries list

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/add-content/AddContent.test.tsx
- src/library-authoring/add-content/AddContent.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/common/context/SidebarContext.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/containers/ContainerOrganize.tsx
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/containers/messages.ts
- src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
- src/library-authoring/generic/manage-collections/ManageCollections.tsx
- src/library-authoring/generic/manage-collections/messages.ts
- src/library-authoring/generic/messages.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
This PR fixes some UX bugs related to the unit pages.
- https://github.com/openedx/frontend-app-authoring/issues/1834
- https://github.com/openedx/frontend-app-authoring/issues/1879
- https://github.com/openedx/frontend-app-authoring/issues/1881
- https://github.com/openedx/frontend-app-authoring/issues/1648#issuecomment-2810338790
- Ref: https://github.com/openedx/frontend-app-authoring/issues/1879
- Open the Unit Sidebar
- Check that it shows the "Manage Tab" instead of "Organize Tab"
- Add the same content twice on a Unit
- Check that there are no duplicate key warnings on the console while viewing the Unit Page
- Check that there are no duplicate key warnings on the console while viewing the Library Page
- Ref: https://github.com/openedx/frontend-app-authoring/issues/1648#issuecomment- …
> fix: unit pages ux bugs [FC-0083]

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/add-content/AddContent.test.tsx
- src/library-authoring/add-content/AddContent.tsx
- src/library-authoring/add-content/PickLibraryContentModal.test.tsx
- src/library-authoring/add-content/PickLibraryContentModal.tsx
- src/library-authoring/add-content/messages.ts
- src/library-authoring/common/context/SidebarContext.tsx
- src/library-authoring/components/ContainerCard.test.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/containers/ContainerOrganize.tsx
- src/library-authoring/containers/UnitInfo.tsx
- src/library-authoring/containers/messages.ts
- src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
- src/library-authoring/generic/manage-collections/ManageCollections.tsx
- src/library-authoring/generic/manage-collections/messages.ts
- src/library-authoring/generic/messages.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
- src/search-manager/data/api.ts
Backports https://github.com/openedx/frontend-app-authoring/pull/1868 + https://github.com/openedx/frontend-app-authoring/pull/1820 to Teak.
Part of: https://github.com/openedx/frontend-app-authoring/issues/1778
Blocked by: https://github.com/openedx/edx-platform/pull/36651
Private-ref: [FAL-4139](https://tasks.opencraft.com/browse/FAL-4139)
Run https://github.com/openedx/edx-platform/pull/36651 on the backend.
See https://github.com/openedx/frontend-app-authoring/pull/1868 + https://github.com/openedx/frontend-app-authoring/pull/1820 for testing instructions.
> perf: use Library search results to populate container card preview [FC-0083] [TEAK]

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/data/thunk.js
The xBlock Manage Access modal doesn't open on duplicated xBlock without page reload.
- open CMS
- open course
- open section > subsection > units
- add unit
- dublicate unit
- click on the unit menu > manage access
- access modal doesn't display
- refresh page and click on the unit menu > manage access
- access modal displays
- teak release https://github.com/openedx/frontend-app-authoring/pull/1874
**Settings**
```
TUTOR_GROVE_NEW_MFES:
authoring:
port: 18000
repository: https://github.com/raccoongang/frontend-app-course-authoring.git
version: romaniuk/fix/manage-access-modal-on-duplicated-xblock
```
> fix: manage access modal on duplicated xblock

- src/library-authoring/data/apiHooks.ts
Together with https://github.com/openedx/edx-platform/pull/36640 , this fixes https://github.com/openedx/frontend-app-authoring/issues/1871 . It depends on that PR for a complete fix, but either PR can be merged independently.
See https://github.com/openedx/frontend-app-authoring/issues/1871
Private ref: [FAL-4156](https://tasks.opencraft.com/browse/FAL-4156)
0. Check out https://github.com/openedx/edx-platform/pull/36640 and install its updated `openedx-events` version.
1. Create a unit. Publish it.
2. Add/create a component in the unit. Edit the component so it shows "unpublished changes"
3. Click on "Library Info" and "Publish all changes"
4. Verify that no units/components in the library search results still show as having unpublished changes. (Before this PR you would still see …
> fix: invalidate search results when publishing all changes in library [FC-0083]

- src/generic/DraggableList/SortableItem.jsx
- src/library-authoring/components/BaseCard.scss
- src/library-authoring/components/BaseCard.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/index.scss
This PR improves the focus and selected styles from the LibraryPage and UnitPage.
- https://github.com/openedx/frontend-app-authoring/issues/1792
- Open a Library and a Unit inside the library authoring and check that the focus and selections styles match the design here: https://github.com/openedx/frontend-app-authoring/issues/1792#issuecomment-2840190569
___
Private ref: [FAL-4144](https://tasks.opencraft.com/browse/FAL-4144)
> fix: improve focus/selected style on library authoring

- src/course-outline/CourseOutline.test.jsx
- src/course-outline/subsection-card/SubsectionCard.jsx
- src/course-outline/subsection-card/SubsectionCard.test.jsx
The whole page was being refreshed while searching content from course outline page due to fetching of waffle flag on changes in location search field.
Related to https://github.com/openedx/frontend-app-authoring/issues/1902
`Private-ref`: https://tasks.opencraft.com/browse/FAL-4161
Verify that the bug described in https://github.com/openedx/frontend-app-authoring/issues/1902 is fixed and the functionality of hiding `Use unit from library` button on disabling new libraries still works.
> fix: search modal refresh on typing

- package-lock.json
- package.json
This PR extract more translations to be translated from the exiting source code, when translated those new strings, it will improve localization.
1. Upgrades the `frontend-build` to the `v14.5.0`, with the support for additional source folders.
2. Configure the `plugins` folder to be used as source folder for i18n extraction.
Executing this command before and after this PR, and the prerequisites. You will see an increase of the extracted strings to be translated.
```bash
npm run i18n_extract && grep '"id"' temp/babel-plugin-formatjs/Default.messages.json | wc -l
```
From 1730 before to 2471 after.
Any.
1. https://github.com/openedx/frontend-build/pull/650 has already been merged. :heavy_check_mark: 
2. A frontend-build upgrade - this PR also upgrades this package :heavy_check_mark: 
Run …
> fix: include plugins in i18n extraction script

- src/course-outline/xblock-status/NeverShowAssessmentResultMessage.jsx
- src/course-outline/xblock-status/XBlockStatus.jsx
- src/course-outline/xblock-status/XBlockStatus.test.jsx
**Ticket:** [TNL-11769](https://2u-internal.atlassian.net/browse/TNL-11769)
- add never show assessment result message in subsection card
**Before:** 
**After:**
> feat: add never show assessment msg in subsection

- src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
- src/generic/inplace-text-editor/index.tsx
- src/library-authoring/collections/CollectionInfoHeader.tsx
- src/library-authoring/component-info/ComponentInfoHeader.tsx
- src/library-authoring/containers/ContainerInfoHeader.tsx
- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/data/apiHooks.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/LibraryUnitPage.test.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
This PR adds the following:
- Optimistic update for renaming Components, Collections and Containers
- Change the InplaceTextEditor to show the new text until the `onSave` promise resolves
- Change the InplaceTextEditor style to: Always show the rename button
- Related to https://github.com/openedx/frontend-app-authoring/issues/1849
Check the style and behaviour on the following:
- UnitPage > Rename unit title
- UnitPage > Rename component title
- Sidebar > Rename unit title
- Sidebar > Rename collection title
- Sidebar > Rename component title
___
> fix: change InplaceTextEditor style and add optimistic update

- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentMenu.tsx
- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/data/api.test.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
Select component that is being edited in library and show its sidebar. Also fixes issue with children component listing in library unit page.
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author"
- Related to: https://github.com/openedx/frontend-app-authoring/issues/1803
- Related to: https://github.com/openedx/frontend-app-authoring/pull/1926/files#r2088216522
- `Private-ref`: https://tasks.opencraft.com/browse/FAL-4160
Verify that change described in https://github.com/openedx/frontend-app-authoring/issues/1803 is implemented and works in all pages.
- Any special concerns or …
> feat: select component and show sidebar on edit 

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/search-manager/SearchKeywordsField.tsx
Fix flickering issue in search field.
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author"
https://github.com/user-attachments/assets/4ba0bf38-aa29-447d-863d-317cfca40e22
* Related to https://github.com/openedx/frontend-app-authoring/issues/1902#issuecomment-2887453654
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-4161
Verify that the bug described in https://github.com/openedx/frontend-app-authoring/issues/1902#issuecomment-2887453654 is not present.
> fix: search text flickering

- src/library-authoring/collections/CollectionInfo.tsx
- src/library-authoring/components/BaseCard.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/routes.ts
Opens collection or unit page only on double click.
- Which edX user roles will this change impact? Common user roles are "Course Author"
* Related to: https://github.com/openedx/frontend-app-authoring/issues/1883
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-4160
Verify that collection and unit page is only opened when we double click the respective card.
> feat: open collection or unit page on double click only

- src/library-authoring/generic/status-widget/index.tsx
- src/library-authoring/library-info/LibraryPublishStatus.tsx
- src/library-authoring/library-info/messages.ts
This PR renames the Library publish button from "Publish" to "Publish All Changes"
- Related to https://github.com/openedx/frontend-app-authoring/issues/1467
Open the library sidebar and check if the "Publish All  Changes" button.
___
> fix: rename library publish button

- src/library-authoring/LibraryAuthoringPage.tsx
Fix the bug described in https://github.com/openedx/frontend-app-authoring/issues/1859
Github issue: https://github.com/openedx/frontend-app-authoring/issues/1859
Internal ticket: [FAL-4160](https://tasks.opencraft.com/browse/FAL-4160)
- Go to the Collections tab
- Open the publish status filter and verify that the menu is in the correct position
- Go to the Home tab
- Open the publish status filter and verify that the menu is in the correct position.
N/A
> fix: Inconsistent publish status filter menu placement in Library home page

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/messages.js
Updating video fallback message to remove edX reference.
#1015
https://github.com/openedx/wg-build-test-release/issues/491
On studio dashboard enter to a course
Click to edit or create a unit
Add a new component video type
On the video modal scroll down to fallback video section and verify the text.
> fix: removing edX text reference on video fallback message

- src/header/hooks.test.js
- src/header/messages.js
In the Content dropdown on Studio, we renamed "Updates" to "Course Updates" and "Library" to "Library Updates", so is a clearer path to access.
Fixes #1755
> Rename in content dropdown updates and libraries

- src/library-authoring/LibraryAuthoringPage.test.tsx
- src/library-authoring/collections/CollectionInfo.tsx
- src/library-authoring/collections/LibraryCollectionPage.test.tsx
- src/library-authoring/components/BaseCard.tsx
- src/library-authoring/components/CollectionCard.tsx
- src/library-authoring/components/ComponentCard.test.tsx
- src/library-authoring/components/ComponentMenu.tsx
- src/library-authoring/components/ContainerCard.tsx
- src/library-authoring/containers/UnitInfo.test.tsx
- src/library-authoring/data/api.test.ts
- src/library-authoring/routes.ts
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/search-manager/SearchKeywordsField.tsx
Backport of #1949, #1999 and #2002
> [Teak] backport #1949, #1999 and #2002

- src/library-authoring/library-info/messages.ts
This PR renames the Library publish button from "Publish All Changes" to "Publish All"
- Related to https://github.com/openedx/frontend-app-authoring/issues/1467#issuecomment-2897986744
Open the library sidebar and check if the "Publish All" button.
___
> fix: rename library publish button to "Publish All"

- src/course-outline/status-bar/StatusBar.jsx
Ticket: [TNL-11993](https://2u-internal.atlassian.net/browse/TNL-11993)
When we specify in Studio (Settings > Schedule & Details) that the course needs to start on a specific date at 12:00 UTC, it is converted into 02:00 AM (Dutch time). 
It should be converted to 02:00 PM.
I did a check with multiple other start times and my findings are:
- Until 11:59 UTC the time is converted to 1:59 PM, what is correct
- Starting at 12:00 UTC until 12:59 it is converted to AM instead of PM
- From 13:00 UTC onwards it is converted to 14:00 PM, as expected.
**Solution:** 
Format was wrong where we were converting the string to UTC datetime obj. So, I have corrected the format in this PR.
**Before:**
**After:**
> fix: studio time zone conversion issue

- src/course-unit/preview-changes/index.test.tsx
- src/course-unit/preview-changes/index.tsx
When accepting/rejecting upstream changes to a course block, just reload the xblock that was changed.
This works around the scrolling issue reported below by avoiding reloading the entire unit. Also makes for a nicer editing experience.
Part of: https://github.com/openedx/frontend-app-authoring/issues/1579
Private-ref: [FAL-4160](https://tasks.opencraft.com/browse/FAL-4160)
1. Create and publish a library component.
2. Copy/paste that component into a course unit.
3. Modify the original library component and publish the changes.
4. Refresh the course unit to see the pending changes.
5. Click the "refresh" button and accept or reject the changes.
The synced block should update itself, and maintain the page scroll position.
> fix: refresh xblock inline after accepting/rejecting library sync [FC-0090]

- plugins/course-apps/xpert_unit_summary/settings-modal/SettingsModal.scss
We shouldn't be importing this from `@edx/brand`. Paragon's [`utilities-only.scss` imports `variables`](https://github.com/openedx/paragon/blob/908fe823e134d106fe502fb85b3c3cdac8006ff3/styles/scss/core/utilities-only.scss#L2). [Paragon's `_variables.scss`](https://github.com/openedx/paragon/blob/release-23.x/styles/scss/core/_variables.scss) ensures the scss variables in this file compile to read css variables. Brand packages provide css variables.
> fix: don't import scss vars from brand package

- src/course-unit/preview-changes/index.test.tsx
- src/course-unit/preview-changes/index.tsx
Backports https://github.com/openedx/frontend-app-authoring/pull/2022 to Teak.
Helps Course Authors.
Part of: https://github.com/openedx/frontend-app-authoring/issues/1579
Private-ref: [FAL-4160](https://tasks.opencraft.com/browse/FAL-4160)
See https://github.com/openedx/frontend-app-authoring/pull/2022
> [TEAK] fix: refresh xblock inline after accepting/rejecting library sync [FC-0090]

- src/course-outline/CourseOutline.test.jsx
- src/course-outline/__mocks__/courseOutlineIndex.js
- src/course-outline/data/api.js
- src/course-outline/data/selectors.js
- src/course-outline/data/slice.js
- src/course-outline/data/thunk.js
- src/course-outline/hooks.jsx
This PR integrates a new API that properly synchronizes discussion topics when creating course re-runs. It addresses an issue where discussion topic data wasn't being correctly synced to new courses, particularly affecting larger courses.
When creating re-runs of larger courses, discussion topic data was inconsistently synchronized to the new course, leading to data inconsistencies in the CSM UI.
Implemented an API call that ensures discussion topic data is properly synchronized between the original course and its re-run. This guarantees that all discussion data remains up-to-date and consistent in the CMS UI.
> feat: added process to sync discussions topic on page load

- src/course-unit/CourseUnit.jsx
Fixes a bug when viewing a Problem Bank-type "unit" without upstream link information attached.
This issue affects Course Authors.
* Part of https://github.com/openedx/frontend-app-authoring/issues/2007
* Private-ref: [FAL-4160](https://tasks.opencraft.com/browse/FAL-4160)
1. Create a library with two or more problem components.
2. Create a course + section + subsection + unit
3. Add a Problem Bank block to the unit, and add the library's problem components to the Problem Bank.
4. Click the View link in the Problem Bank, and verify that you can see the problem components without error.
> fix: upstreamInfo is not always provided

- src/course-unit/CourseUnit.jsx
Backports https://github.com/openedx/frontend-app-authoring/pull/2041 to Teak.
This issue affects Course Authors.
* Part of https://github.com/openedx/frontend-app-authoring/issues/2007
* Private-ref: [FAL-4160](https://tasks.opencraft.com/browse/FAL-4160)
See https://github.com/openedx/frontend-app-authoring/pull/2041
> [teak] fix: upstreamInfo is not always provided [FC-0090]

- src/library-authoring/components/BaseCard.scss
- src/library-authoring/units/LibraryUnitBlocks.tsx
- src/library-authoring/units/index.scss
This PR removes the library cards' resize because of the border change on selection.
Related to: https://github.com/openedx/frontend-app-authoring/issues/1792#issuecomment-2894950598
- Open a library, click on cards and check that the cards aren't resizing
- Open a unit inside a library, click on the components and check that the cards aren't resizing
> fix: selection card wiggle

- src/editors/sharedComponents/CodeEditor/hooks.js
- src/editors/sharedComponents/SourceCodeModal/__snapshots__/index.test.jsx.snap
- src/editors/sharedComponents/SourceCodeModal/index.jsx
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author",
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
Please provide detailed …
> fix: backport changes for html button in text component markdown editor

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/header-navigations/HeaderNavigations.jsx
- src/course-outline/subsection-card/SubsectionCard.jsx
It was requested that the Expand All button should expand both Sections and Subsections
- The state variable is send to the SubSection element so it shares the state controlled by the button
Fixes: https://github.com/openedx/wg-build-test-release/issues/479
- Now that the SubSections are expanded when clicking in the buttons, the test cases where adapted to handle that behavior.
- Test cases are adapted to the new behavior.
- Got to the Authoring Studio
- Go to the example course outline
- Click `Expand All`
- All Sections and Subsection should be expanded
- User should be able to expand and collapse all items individually as normal
- Click `Collapse All`
- All Sections should be collapsed as normal
- User should be able to expand and collapse all items individually as normal …
> fix: Expand all now expands subsections

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.scss
Files and Uploads three-dot menu for a file is truncated when is a short list or on the next to last file of the table due to overflow-x that is set as auto in data table container, it seems to be hidden but creates a scrollbar and expects to scroll to see the menu.
Fixes https://github.com/openedx/wg-build-test-release/issues/426
Go to content -> files -> click on the next to last file three dot menu
Before:
Short list
Long list
After:
Short list
Long list
> Fix Files and Uploads three-dot menu for a file was truncated

- src/course-checklist/ChecklistSection/messages.js
- src/course-checklist/ChecklistSection/utils/courseChecklistData.jsx
- src/course-checklist/ChecklistSection/utils/courseChecklistValidators.js
- src/course-checklist/ChecklistSection/utils/courseChecklistValidators.test.js
- src/course-checklist/ChecklistSection/utils/getValidatedValue.js
- src/course-checklist/ChecklistSection/utils/getValidatedValue.test.js
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/constants.js
- src/course-outline/utils/courseChecklistValidators.js
- src/course-outline/utils/courseChecklistValidators.test.js
- src/course-outline/utils/getChecklistForStatusBar.test.js
- src/course-outline/utils/getChecklistValues.js
Best Practices Checklist behavior was wrong for some cases, also in the issue was requested to completely remove mobile friendly video from the checklist.
Fixes:
- Video duration: if duration was null it shouldn't be marked as completed, if there were no videos shouldn't be marked as completed
- Unit depth: If course doesn't have units it shouldn't be marked as completed
- Diverse learning sequence: description mentions that 80% should contain multiple content types, so if it is exactly 80% it should be marked as completed
Fixes https://github.com/openedx/frontend-app-authoring/issues/2070
Course with …
> Fix logic of best practices checklist and remove mobile friendly check

- src/course-outline/CourseOutline.jsx
- src/course-outline/CourseOutline.test.jsx
- src/course-outline/header-navigations/HeaderNavigations.jsx
- src/course-outline/subsection-card/SubsectionCard.jsx
_Backport From https://github.com/openedx/frontend-app-authoring/pull/1998_
It was requested that the Expand All button should expand both Sections and Subsections
- The state variable is send to the SubSection element so it shares the state controlled by the button
Fixes: https://github.com/openedx/wg-build-test-release/issues/479
- Now that the SubSections are expanded when clicking in the buttons, the test cases where adapted to handle that behavior.
- Test cases are adapted to the new behavior.
- Got to the Authoring Studio
- Go to the example course outline
- Click `Expand All`
- All Sections and Subsection should be expanded
- User should be able to expand and collapse all items individually as normal
- Click `Collapse All`
- All Sections should be collapsed as normal
- User should …
> BACKPORT fix: Expand all now expands subsections

- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/files-page/FilesPage.scss
This PR is a Teak backport for #2071 , which fixes: Files and Uploads three-dot menu for a file is truncated when is a short list or on the next to last file of the table due to overflow-x that is set as auto in data table container, it seems to be hidden but creates a scrollbar and expects to scroll to see the menu.
Fixes https://github.com/openedx/wg-build-test-release/issues/426
Go to content -> files -> click on the next to last file three dot menu
Before:
Short list
Long list
After:
Short list
Long list
Master PR: #2071
> Backport fix: files & uploads menu was truncated due to overflow-x (#2071)

- src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
- src/generic/inplace-text-editor/index.tsx
- src/library-authoring/LibraryAuthoringPage.tsx
- src/library-authoring/data/apiHooks.ts
- Fix the issue of the big edit icon 
- Makes the edit button disappear while editing
- Which edX user roles will this change impact? "Course Author.
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1971
- Internal ticket: [FAL-4165](https://tasks.opencraft.com/browse/FAL-4165)
- Create one unit, one section and one subsection.
- Go to the unit page and verify that the issue has been resolved.
- Go to the section page and verify that the issue has been resolved.
- Go to the subsection page and verify that the issue has been resolved.
- I think that this PR can be backported to teak if necessary
> fix: Issue on the Inplace editor [FC-0090]

- src/course-unit/CourseUnit.jsx
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.v1.md
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
The sidebar slot in the Course Unit page wrapped only a partial set of components that are being rendered when the unit is of 'vertical' type. This leads to 2 issues:
* the sidebar slot will not be rendered when the unit
is not of `vertical` type
* the slot's position in the UI is inconsistent between
the Course Outline page and Course Unit page
In this PR, all the elements of the sidebar column are wrapped into the slot.
- *Which edX user roles will this change impact?* "Course Author" and "Developer".
- *Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).* - No UI changes. 
- *Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.* - N/A …
> refactor: CourseAuthoringUnitSidebarSlot

- src/course-unit/CourseUnit.test.jsx
- src/course-unit/add-component/AddComponent.jsx
- src/course-unit/add-component/messages.js
- src/course-unit/xblock-container-iframe/index.tsx
- src/course-unit/xblock-container-iframe/messages.ts
- https://github.com/openedx/frontend-app-authoring/issues/2106
- https://github.com/openedx/frontend-app-authoring/issues/2107
Remove an extra editing xBlock modal on the unit page.
https://github.com/user-attachments/assets/e75a9c14-24de-430b-b933-8d87d38ef687
- In Studio, add a new unit and insert a text component.
- Try to insert/edit a link, an emoji, a special character, or an iframe.
- You can see the TinyMCE modal.
> fix: remove an extra editing xblock modal on unit page

- src/library-authoring/common/context/SidebarContext.tsx
- src/library-authoring/section-subsections/LibrarySectionSubsectionPage.test.tsx
- src/library-authoring/units/LibraryUnitPage.test.tsx
Shows the sidebar Preview tab when a container child is selected, while hiding the Preview tab when sidebar shows the container itself, since it's "preview" is already in the main page body.
Adds tests to ensure this behavior is maintained.
Affects Content Library Authors.
Addresses comments from:
* https://github.com/openedx/frontend-app-authoring/issues/1613#issuecomment-2959957440
* https://github.com/openedx/frontend-app-authoring/issues/1614#issuecomment-2959953369
Private-ref: [FAL-4191](https://tasks.opencraft.com/browse/FAL-4191)
* Create one or more components
* Create a unit with one or more components
* Create a subsection with one or more units
* Create a section with one or more subsections
* Using each of the "All Content" / Components / Units / Section / Subsection _tabs_, …
> fix: show Preview tab in sidebar when container child selected [FC-0090]

- src/library-authoring/LibraryAuthoringPage.tsx
When working with the modal component selection window, there are problems with incorrect placement of the Change Library link stroke. So product suggested to remove icon and empty link.
Fixes #1894 
Go to a course -> add a new unit -> select Libraries -> select a library -> try to go back to change library
Before:
After:
https://github.com/user-attachments/assets/e4d6c80b-ffcb-45fe-8749-61e8c87d00a2
> Remove icon and empty breadcrumb from libraries component selection

- src/editors/data/redux/thunkActions/problem.test.ts
- src/editors/data/redux/thunkActions/problem.ts
- src/library-authoring/components/ComponentEditorModal.tsx
The markdown problem editor wasn't available in libraries, but probably unintentionally.
Don't merge yet - there is a minor bug with this: https://github.com/openedx/frontend-app-authoring/issues/2099
Create a new problem in a library. Switch to markdown editor.
Confirm that if the waffle flag is modified, the markdown option is no longer available.
> Backport fix: enable markdown editor in libraries

- src/library-authoring/LibraryAuthoringPage.tsx
When working with the modal component selection window, there are problems with incorrect placement of the Change Library link stroke. So product suggested to remove icon and empty link.
Fixes #1894 
Backport of #2129 
Go to a course -> add a new unit -> select Libraries -> select a library -> try to go back to change library
Before:
After:
https://github.com/user-attachments/assets/e4d6c80b-ffcb-45fe-8749-61e8c87d00a2
> Backport: Remove icon and empty breadcrumb from libraries (#2129)

- src/search-modal/SearchModal.scss
- src/search-modal/SearchResult.tsx
Fixed issue with the text-truncate property, does not correctly applied to the description in the search result item in the search modal:
https://github.com/openedx/frontend-app-authoring/issues/1900
Replaced `text-truncate` class which contains `white-space: nowrap;` rule and in this case, it breaks layout. 
Additionally fixed `btn-icon` that has shrunk due to lack of space.
Fix example:
> fix: Text truncate issue in the search modal

- src/advanced-settings/data/api.js
- src/advanced-settings/data/api.test.js
This PR fixes this [bug](https://github.com/openedx/frontend-app-authoring/issues/1243#issue-2496098982) and this [bug](https://github.com/eduNEXT/hosting-heimdall/issues/25).
* Deploy your local environment or go to your preferred remote environment (REDWOOD).
* Go to studio > settings > advanced settings.
* "Certificate html override" and "other course settings" are showing dictionary keys in `camelCase` (Review any field whose value is an object with configuration keys).
**BEFORE**
**AFTER**
> fix: advanced-settings.api always return exactly what it receives

- src/course-unit/CourseUnit.jsx
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.v1.md
- src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
Teak backport of https://github.com/openedx/frontend-app-authoring/pull/2000
See: https://github.com/openedx/frontend-app-authoring/pull/2000
> [Teak Backport] feat: course authoring unit sidebar slot v2

- src/advanced-settings/data/api.js
- src/advanced-settings/data/api.test.js
This PR fixes this [bug](https://github.com/openedx/frontend-app-authoring/issues/1243#issue-2496098982) and this [bug](https://github.com/eduNEXT/hosting-heimdall/issues/25).
\[ Maintainer edit: This is a backport of https://github.com/openedx/frontend-app-authoring/pull/1581 ]
* Deploy your local environment or go to your preferred remote environment (REDWOOD).
* Go to studio > settings > advanced settings.
* "Certificate html override" and "other course settings" are showing dictionary keys in `camelCase` (Review any field whose value is an object with configuration keys).
BEFORE
AFTER
> fix: advanced-settings api should not camel-case return value (openedx#1581)

- src/files-and-videos/files-page/FilesPage.test.jsx
- src/files-and-videos/files-page/data/slice.js
- src/files-and-videos/generic/DeleteConfirmationModal.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/table-components/TableActions.jsx
- src/files-and-videos/generic/table-components/TableActions.test.jsx
This PR clears the selected rows in the Files page when a delete or add action is executed. It also modifies the `setAssetIds` reducer to avoid asset duplication
Resolves #1541 
1. Go to Studio -> any course -> Content -> Files
2. Upload a set of four or more files
3. Then select the first two files in the list and go to Actions -> Delete
4. After you press "Delete", those files will be removed, and the next two files shouldn't become selected
|before|after|
|---------|------|
|[Screencast from 30-05-25 16:38:04.webm](https://github.com/user-attachments/assets/de65236e-2aab-4e53-8e26-bdd05636ee21)|[Screencast from 30-05-25 16:39:48.webm](https://github.com/user-attachments/assets/7c0b17c0-c2ac-43de-8b74-efbd4cefc594)|
> refactor: remove selected rows when deleting or adding elements

- src/library-authoring/__mocks__/unit-single.json
- src/library-authoring/generic/index.scss
- src/library-authoring/generic/parent-breadcrumbs/ParentBreadcrumbs.test.tsx
- src/library-authoring/generic/parent-breadcrumbs/index.scss
- src/library-authoring/generic/parent-breadcrumbs/index.tsx
- src/library-authoring/generic/parent-breadcrumbs/messages.ts
- src/library-authoring/section-subsections/LibrarySubsectionPage.tsx
- src/library-authoring/section-subsections/index.scss
- src/library-authoring/units/LibraryUnitPage.test.tsx
- src/library-authoring/units/LibraryUnitPage.tsx
This PR adds the `ParentBreadcrumbs` component to show a list of parent containers on the Unit and Subsection breadcrumbs.
- Related to https://github.com/openedx/frontend-app-authoring/issues/2194
- Open a unit not associated with any subsections
- Check that the breadcrumbs show only the library name
- Add a unit to one subsection
- Open the Unit page and check that the breadcrumbs show a direct link to this subsection
- Add the same unit to another subsection
- Open the Unit page and check that the breadcrumbs show a menu listing both subsections
- Repeat the process, checking Subsections associated with Sections
___
Private ref: [FAL-4216](https://tasks.opencraft.com/browse/FAL-4216)
> feat: add ParentBreadcrumbs component [FC-0090]

- src/generic/delete-modal/DeleteModal.tsx
- src/library-authoring/containers/ContainerRemover.tsx
- src/studio-home/tabs-section/courses-tab/courses-filters/index.test.jsx
Styles the container delete and remove modals according to the designs.
- Issue: https://github.com/openedx/frontend-app-authoring/issues/1985
- [Private-Ref](https://tasks.opencraft.com/browse/FAL-4174)
- Open the libraries v2 and create/open a Section/Subsection. 
- Create a new subsection/unit
- Try to delete it from the card menu
- Assert the confirmation warning looks like this: 
- Try to remove it
- Assert the dialog looks like this
> fix: delete and remove modals styling

- src/course-unit/hooks.jsx
- src/editors/data/redux/thunkActions/app.js
- src/editors/data/redux/thunkActions/app.test.js
Ticket: [TNL-12019](https://2u-internal.atlassian.net/browse/TNL-12019)
When we edit & save the component, publish button doesn't show up until we refresh the page manualy or open this unit by opening previous unit and coming back to this unit again. 
In this PR, we are dispatching a storage event whenever we edit the component, it'll refresh the page & show the publish button as expected.
**Before:**
**After:**
> fix: publish button doesn't show up after component edit

- src/library-authoring/add-content/AddContent.tsx
Updates the icons of the add existing content icons in section/subsection pages: https://github.com/openedx/frontend-app-authoring/issues/1968#issuecomment-3001622086
- Github issue: https://github.com/openedx/frontend-app-authoring/issues/1968#issuecomment-3001622086
- Internal ticket: [FAL-4191](https://tasks.opencraft.com/browse/FAL-4191)
- Go to the library home
- Create a Section and Subsection
- In the section page, click on `Add subsection`. In the sidebar, verify that both icons are the same.
- In the subsection page, click on `Add Unit`. In the sidebar, verify that both icons are the same.
N/A
> fix: Update add existing content icons in section/subsection pages

- src/library-authoring/LibraryAuthoringPage.scss
This PR subtly increases the sidebar width to prevent the overflow menu from wrapping to a second line when two scrollbars are present.
- Related to: https://github.com/openedx/frontend-app-authoring/issues/1822
This should be done in Chrome:
- Open a content library and select a component
- Reduce the screen width (i.e., by opening the console) to force both the library page and the sidebar to show a scrollbar
- Check that you can reproduce the bug
- Checkout this branch and check if the bug is fixed
Another approach would be to remove the duplicated sidebar by adjusting the sidebar height to match the content, but this would alter the sticky behavior, where we always see the top of the sidebar while scrolling through the content.
> fix: increase sidebar width to prevent menu overflow

- src/library-authoring/units/LibraryUnitBlocks.tsx
When selecting a component inside a unit with the keyboard, opening it in the sidebar by pressing enter was not working.
- Previous related PR: https://github.com/openedx/frontend-app-authoring/pull/2209
- Issue: https://github.com/openedx/frontend-app-authoring/issues/2196#issuecomment-3022779839
- [Private-Ref](https://tasks.opencraft.com/browse/FAL-4240)
* In the library home, create a unit.
* Open the unit page, and create multiple components
* select one component card with the keyboard. Press Enter. The sidebar should open
> fix: open component with keyboard within unit page

- src/header/hooks.jsx
- src/optimizer-page/CourseOptimizerPage.tsx
- src/optimizer-page/messages.js
This PR updates the **Course Optimizer** page in the CMS by replacing the **"BETA"** tag with **"NEW"** in the following locations:
- CMS header menu (navigation)
- Page title of the Course Optimizer
---
- Replaced `"BETA"` with `"NEW"` in the header UI component
- Ensured consistency across both UI and metadata
---
[2U internal Jira ticket](https://2u-internal.atlassian.net/browse/TNL2-150)
---
- This is a UI/label change only — no backend or logic modifications were made.
**Before:**
**After:**
---
> feat: Update Course Optimizer label from BETA to NEW

- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.js
- src/files-and-videos/generic/table-components/sort-and-filter-modal/utils.test.js
Files and Uploads search text is lost when using Sort and Filter more than once
Fix for the following issue 
https://github.com/openedx/frontend-app-authoring/issues/2052
https://github.com/user-attachments/assets/c6cf343e-b233-4ace-8a29-185dfbad6692
> Files and Uploads search text is lost when using Sort and Filter more than once

- src/accessibility-page/AccessibilityForm/AccessibilityForm.jsx
- src/advanced-settings/setting-card/SettingCard.jsx
- src/advanced-settings/setting-card/SettingCard.test.jsx
- src/course-outline/drag-helper/SortableItem.jsx
- src/export-page/export-stepper/ExportStepper.jsx
- src/export-page/export-stepper/ExportStepper.test.jsx
- src/files-and-videos/generic/FileTable.jsx
- src/files-and-videos/generic/InfoModal.jsx
- src/files-and-videos/generic/table-components/table-custom-columns/ActiveColumn.jsx
- src/files-and-videos/videos-page/VideoThumbnail.jsx
- src/generic/configure-modal/AdvancedTab.jsx
- src/generic/configure-modal/PrereqSettings.jsx
- src/grading-settings/assignment-section/assignments/AssignmentTypeName.jsx
- src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
Closes https://github.com/openedx/frontend-app-authoring/issues/2282
Replacing the usage of `injectInt` HOC with `useIntl()` hook from `@edx/frontend-platform/i18n` and all related code.
Most of the refactor of the files was made using this codemon: https://github.com/WGU-Open-edX/oex-utils/tree/main/intl-modernizer.
> Replacing of injectIntl with useIntl() part 2

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.jsx
- src/files-and-videos/files-page/FileThumbnail.jsx
- src/files-and-videos/generic/ApiStatusToast.jsx
- src/files-and-videos/generic/DeleteConfirmationModal.jsx
- src/generic/ConnectionErrorAlert.jsx
- src/generic/configure-modal/BasicTab.jsx
- src/grading-settings/deadline-section/index.jsx
- src/import-page/file-section/FileSection.jsx
- src/pages-and-resources/discussions/app-config-form/AppConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/lti/LtiConfigForm.jsx
- src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.jsx
Replace of injectIntl with useIntl() part 6
> refactor: Replace of injectIntl with useIntl() part 6

- src/accessibility-page/AccessibilityPage.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
- src/editors/containers/TextEditor/index.jsx
- src/editors/containers/TextEditor/index.test.tsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/LanguageNamesWidget.jsx
- src/export-page/export-modal-error/ExportModalError.jsx
- src/files-and-videos/files-page/FileValidationModal.jsx
- src/files-and-videos/files-page/FilesPage.jsx
- src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
- src/generic/course-stepper/index.jsx
- src/optimizer-page/CourseOptimizerPage.tsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/AnonymousPostingFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
Closes https://github.com/openedx/frontend-app-authoring/issues/2283
Replacing the usage of `injectInt` HOC with `useIntl()` hook from `@edx/frontend-platform/i18n` and all related code.
Most of the refactor of the files was made using this codemon: https://github.com/WGU-Open-edX/oex-utils/tree/main/intl-modernizer.
> Replacing of injectIntl with useIntl() part 3

- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx
- src/files-and-videos/videos-page/info-sidebar/InfoTab.jsx
- src/files-and-videos/videos-page/transcript-settings/Cielo24Form.jsx
- src/generic/configure-modal/UnitTab.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
- src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.jsx
- src/pages-and-resources/discussions/app-list/AppListNextButton.jsx
- src/schedule-and-details/introducing-section/introduction-video/index.jsx
- src/studio-home/tabs-section/libraries-tab/index.jsx
https://github.com/openedx/frontend-app-authoring/issues/2285
> refactor: Replace of injectIntl with useIntl() part 5 #2285

- src/course-unit/course-sequence/sequence-navigation/UnitButton.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.tsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.tsx
- src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/index.test.jsx
- src/editors/containers/ProblemEditor/index.test.tsx
- src/editors/containers/ProblemEditor/index.tsx
- src/editors/data/redux/index.ts
- src/editors/editorTestRender.jsx
- src/testUtils.tsx
Replace connect with useSelector() and useDispatch() 1/5 #2313
> refactor: Replace connect with useSelector() and useDispatch() 1/5

- src/CourseAuthoringRoutes.jsx
- src/course-outline/data/apiHooks.ts
- src/course-unit/SubsectionUnitRedirect.test.tsx
- src/course-unit/SubsectionUnitRedirect.tsx
- src/course-unit/__mocks__/courseSectionVertical.js
- src/course-unit/breadcrumbs/Breadcrumbs.test.tsx
- src/course-unit/breadcrumbs/Breadcrumbs.tsx
- src/course-unit/index.js
- src/course-unit/utils.ts
- navigates the breadcrumb to the first unit under the subsection instead of the outline page.
Closes #1924
- As per the above issue the to make the breadcrumbs navigate to the first unit if available, of the subsection the url of the breadcrumbs needed a change.
- To navigate to the unit page first unit id is required which is fetched via the subsection id. 
- Breadcrumbs does not have the subsection id but was using the ancestorXblocks data from the api. Hence felt it is best to included an extra field for subsection id in the api response via https://github.com/openedx/edx-platform/pull/37072  
- Now this breadcrumbs navigates to an intermediate page for subsections.
- This page does the fetching of firstunit Id, the final url creation and redirection to the first unit.
> feat: navigates subsection breadcrumb to first unit page

- src/editors/VideoSelector.test.tsx
- src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/index.test.tsx
- src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.tsx
- src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
- src/editors/containers/ProblemEditor/index.test.tsx
- src/editors/containers/ProblemEditor/index.tsx
- src/editors/data/store.ts
- src/editors/editorTestRender.tsx
- src/editors/sharedComponents/TinyMceWidget/index.test.tsx
- src/testUtils.tsx
This fixes some bugs and cleans up redundant code introduced by https://github.com/openedx/frontend-app-authoring/pull/2326 .
This is part of the broader effort to clean up our test suite and [remove `useSelector` and `useDispatch`](https://github.com/openedx/frontend-app-authoring/issues/2312).
This mostly changes test code, but it does make one fix to the problem editor, so make sure the (capa) problem editor is working normally.
> Clean up editor tests

- src/files-and-videos/videos-page/VideosPage.jsx
- src/files-and-videos/videos-page/info-sidebar/VideoInfoModalSidebar.jsx
[OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be linked here.
- Which user roles will this change impact? Common user roles are "Learner", "Course Author",
Please provide detailed …
> fix: fix unit test and refactor the code

- src/library-authoring/containers/ContainerInfo.test.tsx
- src/library-authoring/section-subsections/LibraryContainerChildren.tsx
- src/library-authoring/units/LibraryUnitBlocks.tsx
Removes interactivity from section/subsection preview in sidebar. Also fixes an issue with unit sidebar, where users could press enter after clicking on any component and it would select it.
- Which user roles will this change impact? "Course Author"
* https://github.com/openedx/frontend-app-authoring/issues/2359
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-4240
Verify that the bug described in #2359 is fixed.
check if your PR …
> fix: remove interactivity from section/subsection preview in sidebar

- src/constants.js
- src/generic/hooks/tests/hooks.test.tsx
- src/generic/hooks/useIframeBehavior.tsx
Fixes https://github.com/openedx/openedx-aspects/issues/316 by scrolling window to the xblock location instead of scrolling within the iFrame
Test with https://github.com/openedx/edx-platform/pull/37152
Need to enable Aspects in-context metrics (https://github.com/openedx/frontend-plugin-aspects)
We're trying to move away from some deprecated patterns in this codebase. …
> fix: scroll entire window instead of iframe

- src/files-and-videos/generic/EditFileErrors.jsx
[OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be linked here.
- Which user roles will this change impact? Common user roles are "Learner", "Course Author",
Please provide detailed …
> refactor: Replace of injectIntl with useIntl() part 6 - remaining files

- src/course-checklist/CourseChecklist.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/index.jsx
- src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/index.test.tsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/index.jsx
- src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.jsx
- src/editors/sharedComponents/CodeEditor/index.jsx
- src/export-page/export-footer/ExportFooter.jsx
- src/files-and-videos/generic/FileMenu.jsx
- src/files-and-videos/generic/UsageMetricsMessage.jsx
- src/generic/SaveFormConnectionErrorAlert.jsx
- src/generic/configure-modal/VisibilityTab.jsx
- src/pages-and-resources/discussions/app-list/AppCard.jsx
- src/schedule-and-details/introducing-section/index.jsx
- src/studio-home/tabs-section/courses-tab/contact-administrator/index.jsx
Replace of injectIntl with useIntl() part 8 #2288 #2357
> refactor: Replace of injectIntl with useIntl() part 8 #2288

- src/course-outline/section-card/SectionCard.test.tsx
- src/course-outline/subsection-card/SubsectionCard.test.tsx
- src/course-outline/unit-card/UnitCard.test.tsx
- src/library-authoring/collections/CollectionDetails.test.tsx
- src/library-authoring/component-info/ComponentPreview.test.tsx
This makes some minor typing improvements in our test code, seen while reviewing https://github.com/openedx/frontend-app-authoring/pull/2324
Specifically instead of just `{...} as XBlock` which is an unsafe cast, we can use `{...} satisfies Partial<XBlock> as XBlock` which is a safer cast that lets you omit fields but requires that the fields you do include have the correct type.
Private ref FAL-4228 
No runtime changes so no manual testing needed; make sure tests are green.
> refactor: minor typing improvements

- src/constants.ts
- src/data/constants.ts
- src/data/slice.ts
- src/data/thunks.ts
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.tsx
- src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.tsx
- src/group-configurations/data/api.js
- src/group-configurations/data/selectors.js
- src/group-configurations/data/selectors.ts
- src/group-configurations/data/slice.test.ts
- src/group-configurations/data/slice.ts
- src/group-configurations/data/thunk.ts
- src/store.ts
- src/studio-home/StudioHome.tsx
- src/studio-home/__mocks__/studioHomeMock.ts
- src/studio-home/data/selectors.js
- src/studio-home/data/selectors.ts
- src/studio-home/data/slice.ts
- src/studio-home/factories/mockApiResponses.tsx
- src/studio-home/tabs-section/courses-tab/index.test.tsx
- src/studio-home/tabs-section/courses-tab/index.tsx
- src/testUtils.tsx
This PR adds some TypeScript types to the global redux state that's in `src/store.ts`. I've only added types for a few parts of the state but already it's caught quite a few bugs in the code, which I've tried to fix in this PR.
n/a
Shouldn't have any runtime effects.
Private ref MNG-4670
> Add TypeScript types to the redux state

- src/course-outline/card-header/TitleButton.tsx
- src/course-outline/card-header/TitleLink.tsx
In a previous PR #2374 some of the styling applied in addition to truncation was lost. This restores that.
Private-ref: https://tasks.opencraft.com/browse/BB-9925
> fix: Restore styling for header title and button

- src/editors/sharedComponents/SelectionModal/GalleryCard.jsx
- src/editors/sharedComponents/SelectionModal/index.scss
Ticket: [TNL2-54](https://2u-internal.atlassian.net/browse/TNL2-54)
This PR fixes tinyMCE images previews in image selection modal.
**Before:**
<video src="https://github.com/user-attachments/assets/613504bd-fb1f-41b6-8c11-97073a71762e" controls></video>
**After:**
<video src="https://github.com/user-attachments/assets/7a4e4802-c966-4ffb-9616-904deccf5c6c" controls></video>
> fix: tinyMCE images previews in image selection modal

- .env
- .env.development
- .env.test
- src/course-team/course-team-sidebar/CourseTeamSideBar.test.jsx
- src/course-team/course-team-sidebar/CourseTeamSidebar.jsx
- src/course-team/course-team-sidebar/messages.js
- src/index.jsx
- src/setupTest.js
- This update introduces a new help section on the Course Teams page to provide quick access to support for bulk user access operations.
**Jira**
- [TNL2-309](https://2u-internal.atlassian.net/browse/TNL2-309)
**Related PR**
- https://github.com/edx/edx-internal/pull/13194
**Screenshot**
> feat: add new help section in course teams page

- src/constants.ts
- src/optimizer-page/CourseOptimizerPage.tsx
- src/optimizer-page/scan-results/BrokenLinkTable.tsx
- src/optimizer-page/scan-results/ScanResults.tsx
- src/optimizer-page/scan-results/messages.js
Tickets: [TNL2-363](https://2u-internal.atlassian.net/browse/TNL2-363), [TNL2-364](https://2u-internal.atlassian.net/browse/TNL2-364)
In this PR:
- don't show `Scan results` heading until there are some results to show.
- change spinner from paragon with spinner icon which looks better than spinner itself.
- disable `update all` button when single update prev Link is in progress.
Before:
<video src="https://github.com/user-attachments/assets/9706accb-e7eb-4fc3-803e-ca8117005949" controls></video>
After:
<video src="https://github.com/user-attachments/assets/1382386e-e414-4777-989f-abbe6638418b" controls></video>
> fix: course optimizer issues

- .github/workflows/validate.yml
- src/library-authoring/component-info/ComponentManagement.test.tsx
As a first step in the upgrade to Node 24, add it to the CI matrix as a non-blocking test.
See [the tracking issue](https://github.com/openedx/frontend-app-authoring/issues/2177) for further information.
> test: Add Node 24 to CI matrix

- src/container-comparison/ChildrenPreview.tsx
- src/container-comparison/CompareContainersWidget.test.tsx
- src/container-comparison/CompareContainersWidget.tsx
- src/container-comparison/ContainerRow.test.tsx
- src/container-comparison/ContainerRow.tsx
- src/container-comparison/data/api.mock.ts
- src/container-comparison/data/apiHooks.ts
- src/container-comparison/index.scss
- src/container-comparison/messages.ts
- src/container-comparison/types.ts
- src/container-comparison/utils.test.ts
- src/container-comparison/utils.ts
- src/course-outline/data/apiHooks.ts
- src/course-outline/hooks.jsx
- src/course-outline/section-card/SectionCard.test.tsx
- src/course-outline/subsection-card/SubsectionCard.test.tsx
- src/course-outline/unit-card/UnitCard.test.tsx
- src/course-unit/data/api.ts
- src/course-unit/data/thunk.js
- src/course-unit/data/types.ts
- src/course-unit/preview-changes/index.test.tsx
- src/course-unit/preview-changes/index.tsx
- src/data/types.ts
- src/generic/key-utils.test.ts
- src/generic/key-utils.ts
- src/index.scss
- src/library-authoring/component-comparison/CompareChangesWidget.tsx
- src/library-authoring/component-comparison/messages.ts
- src/library-authoring/data/api.mocks.ts
Container sync preview implemented as describe in https://github.com/openedx/frontend-app-authoring/issues/2176
https://github.com/user-attachments/assets/72785f59-f993-4550-bec1-ae77e4325527
**Limitations:**
* No easy way to distinguish containers that have only their name updated vs changes in their children. The version is updated in following cases, on container name change, on children order change and addition or deletion of a child component.
- Which user roles will this change impact? Author.
* https://github.com/openedx/frontend-app-authoring/issues/2176
* Depends on https://github.com/openedx/edx-platform/pull/37375
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-4246
* Checkout edx-platform and this PR.
* Create sections, subsections, …
> feat: container library-course sync diff prevew [FC-0097]
